'use strict';
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanAppsCenter=ui;})(typeof window==='undefined'?null:window,function(){
 const APP='titan-cloudflared',PATH='/api/app-install',STATUS=PATH+'?app='+APP;
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const cloud='<svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M10 29h20a6 6 0 0 0 .3-12 10 10 0 0 0-19-3A7.5 7.5 0 0 0 10 29Z" stroke="currentColor" stroke-width="2"/><path d="m16 23 4-4 4 4m-4-4v15" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>';
 const STEPS=[['docker','Docker prüfen'],['files','Dateien und Compose erstellen'],['pull','Container-Image laden'],['create','Container erstellen'],['start','Container starten'],['connection','Cloudflare-Verbindung prüfen'],['proxy','Lokalen Zugang einrichten'],['public_check','Öffentlichen Zugang prüfen']];
 const stepStatus={pending:'Ausstehend',running:'Läuft',completed:'Erledigt',failed:'Fehlgeschlagen',skipped:'Übersprungen'};
 let cleanup=null;
 function url(value,publicOnly=false){try{const parsed=new URL(value);return (publicOnly?parsed.protocol==='https:':['http:','https:'].includes(parsed.protocol))&&!parsed.username&&!parsed.password?parsed.href:'';}catch{return '';}}
 // Hydration deliberately excludes recipes, options, environment and credentials.
 // Even an accidentally expanded server response cannot serialize a token here.
 function state(context={},redact=value=>String(value??'')){
  const admin=context.admin===true,demo=!!context.demo,source=admin?(context.installation||{}):{},runtime=source.runtime||{},setup=source.setup||{},remote=source.remote||{};
  const rows=Array.isArray(context.installed)?context.installed:context.installed?.installed||[];
  return {admin,demo:demo||!!source.demo,details_open:context.details_open===true||!!source.installed||rows.some(row=>row.id===APP)||['running','failed','interrupted'].includes(source.status),installed:rows.filter(row=>row&&typeof row.id==='string').map(row=>({id:row.id,name:redact(row.name||row.id),status:redact(row.status||row.phase||'')})),installation:{
   revision:typeof source.revision==='string'?source.revision:'',status:['idle','running','completed','failed','interrupted'].includes(source.status)?source.status:'idle',current_step:STEPS.some(([key])=>key===source.current_step)?source.current_step:'',resumable:!!source.resumable,installed:!!source.installed||rows.some(row=>row.id===APP),available:source.available!==false,message:redact(source.message),
   setup:{phase:redact(setup.phase),needs_domain:!!setup.needs_domain},
   runtime:{state:['missing','running','stopped','blocked'].includes(runtime.state)?runtime.state:'missing',cloudflare_connected:runtime.cloudflare_connected===true,public_ready:runtime.public_ready===true,public_origin:url(runtime.public_origin||remote.public_origin,true),service_url:url(runtime.service_url||setup.service_url),enabled:runtime.enabled===true,message:redact(runtime.message)},
   steps:STEPS.map(([id,label])=>{const row=(Array.isArray(source.steps)?source.steps:[]).find(item=>item.id===id)||{};return {id,label:redact(row.label||label),status:Object.hasOwn(stepStatus,row.status)?row.status:'pending',message:redact(row.message),started_at:typeof row.started_at==='number'?row.started_at:null,finished_at:typeof row.finished_at==='number'?row.finished_at:null};}),
   diagnosis:{checked_at:typeof source.diagnosis?.checked_at==='number'?source.diagnosis.checked_at:null,checks:(Array.isArray(source.diagnosis?.checks)?source.diagnosis.checks:[]).map(row=>({name:redact(row.name),message:redact(row.message),ok:row.ok===true?true:row.ok===false?false:null}))}
  }};
 }
 function summary(value){const {runtime:r,setup,status,installed}=value;if(status==='running')return ['working','Installation läuft','Die Einrichtung läuft auf deinem NAS weiter, auch wenn du dieses Fenster schließt.'];if(status==='failed'||status==='interrupted')return ['warning',status==='failed'?'Installation fehlgeschlagen':'Installation unterbrochen','Die ausgeführten Schritte bleiben sichtbar. Prüfe den Verlauf und setze die Einrichtung fort.'];if(r.public_ready)return ['ready','Öffentlicher Zugang geprüft','Connector und öffentliche Titan-Adresse wurden erfolgreich geprüft.'];if(r.state==='stopped')return ['neutral','App gestoppt','Starte den Connector, um die Verbindung wiederherzustellen.'];if(r.cloudflare_connected)return ['warning',setup.needs_domain||!r.public_origin?'Öffentliche Adresse ergänzen':'Öffentliche Route prüfen','Der Connector ist verbunden. Der öffentliche Zugang ist noch nicht bestätigt.'];if(installed)return ['warning','Verbindung prüfen',r.message||'Die App ist installiert. Eine Cloudflare-Verbindung ist noch nicht bestätigt.'];return ['neutral','Noch nicht installiert','Verbinde Titan mit deinem Cloudflare-Tunnel.'];}
 function timeline(value){return `<ol class="ac-steps" aria-label="Tatsächliche Installationsschritte">${value.steps.map((step,index)=>`<li class="ac-step is-${step.status}" data-app-step="${step.id}"><span class="ac-step-symbol" aria-hidden="true">${step.status==='completed'?'✓':step.status==='failed'?'!':step.status==='running'?'◌':step.status==='skipped'?'–':index+1}</span><div><div class="ac-step-title"><strong>${esc(step.label)}</strong><span>${stepStatus[step.status]}</span></div>${step.message?`<p>${esc(step.message)}</p>`:''}${step.finished_at?`<small>Abgeschlossen ${esc(new Date(step.finished_at*1000).toLocaleString('de-DE'))}</small>`:''}</div></li>`).join('')}</ol>`;}
 function render(context={}){
  const data=state(context),value=data.installation,{runtime:r}=value,[tone,title,description]=summary(value),locked=!data.admin||data.demo||value.status==='running',disabled=locked?'disabled':'',other=data.installed.filter(row=>row.id!==APP);
  return `<section class="apps-center" data-apps-center data-config="${esc(JSON.stringify(data))}">
   <header class="ac-heading"><div><h1>Apps</h1><p>Docker-Compose-Apps für dein NAS.</p></div><a class="button small" href="#docker">Docker verwalten →</a></header>
   ${data.demo?'<p class="ac-notice" role="note">Demo · Installationen und App-Änderungen sind in der Vorschau deaktiviert.</p>':''}
   <article class="ac-app-card"><span class="ac-app-icon">${cloud}</span><div class="ac-app-copy"><span class="ac-eyebrow">NETZWERK · DOCKER COMPOSE</span><h2>Cloudflare Tunnel</h2><p>Titan über deine eigene HTTPS-Adresse erreichen.</p><span class="ac-badge is-${tone}">${esc(data.admin?title:value.installed?'Installiert':'Administrator erforderlich')}</span></div><button class="button ${value.installed||!data.admin?'':'primary'}" type="button" data-apps-open aria-controls="ac-cloudflare-details" aria-expanded="${data.details_open}">${value.installed||!data.admin||data.details_open?'Details':'Installieren'}</button></article>
   <section class="ac-detail" id="ac-cloudflare-details" data-apps-detail aria-label="Cloudflare Tunnel verwalten" tabindex="-1" ${data.details_open?'':'hidden'}>
   ${!data.admin?'<div class="ac-restricted"><strong>Administrator erforderlich</strong><p>Ein Administrator kann Cloudflare Tunnel installieren und den öffentlichen NAS-Zugang verwalten.</p></div>':`
    <div class="ac-detail-heading"><div><h3>Cloudflare Tunnel</h3><p>Eigene Compose-App · kein zusätzliches Verwaltungspasswort erforderlich.</p></div><button class="button small" type="button" data-apps-refresh ${data.demo?'disabled':''}>Status aktualisieren</button></div>
    <div class="ac-status is-${tone}" data-apps-status role="status" tabindex="-1"><span aria-hidden="true">${tone==='ready'?'✓':tone==='working'?'◌':tone==='warning'?'!':'○'}</span><div><strong>${esc(title)}</strong><p>${esc(description)}</p></div></div>
    ${!value.available&&!data.demo?'<p class="ac-notice is-warning">Docker ist derzeit nicht bereit. Die Installation prüft und richtet die erforderliche Docker-Komponente ein.</p>':''}
    <div class="ac-runtime" aria-label="Verbindungsstatus"><div><span>Connector</span><strong>${r.cloudflare_connected?'Mit Cloudflare verbunden':r.state==='running'?'Gestartet · Verbindung ausstehend':r.state==='stopped'?'Gestoppt':'Noch nicht verbunden'}</strong></div><div><span>Öffentlicher Zugang</span><strong>${r.public_ready?'Geprüft erreichbar':'Noch nicht bestätigt'}</strong></div></div>
    ${value.installed?`<div class="ac-actions"><button class="button" type="button" data-apps-lifecycle="start" ${locked||r.state==='running'?'disabled':''}>Starten</button><button class="button" type="button" data-apps-lifecycle="stop" ${locked||r.state!=='running'?'disabled':''}>Stoppen</button>${value.resumable?`<button class="button primary" type="button" data-apps-resume ${disabled}>Einrichtung fortsetzen</button>`:''}</div>`:value.resumable?`<div class="ac-actions"><button class="button primary" type="button" data-apps-resume ${disabled}>Einrichtung fortsetzen</button></div>`:''}
    <div class="ac-detail-grid"><div class="ac-configuration">${value.installed?'<details class="ac-reconnect"><summary>Token ändern oder erneut verbinden</summary>':''}<form class="ac-install-form" data-apps-install-form><h4>${value.installed?'Tunnel erneut verbinden':'Tunnel installieren'}</h4><p>Füge den Connector-Token aus deinem Cloudflare-Tunnel ein. Titan erstellt die Compose-Dateien und startet die App.</p><label for="ac-tunnel-token">Tunnel-Token<input id="ac-tunnel-token" type="password" name="tunnel_token" required maxlength="4096" autocomplete="off" spellcheck="false" placeholder="Nur den Token einfügen" ${disabled}></label><small>Der Token wird geschützt auf deinem NAS gespeichert und hier nie wieder angezeigt.</small>${!value.installed?`<label for="ac-public-origin">Öffentliche Titan-Adresse <span>optional</span><input id="ac-public-origin" type="url" name="public_origin" placeholder="https://nas.example.de" value="${esc(r.public_origin)}" ${disabled}></label><small>Du kannst die HTTPS-Adresse auch nach der Installation ergänzen.</small>`:''}<div class="ac-actions"><button class="button primary" type="submit" ${disabled}>${value.installed?'Erneut verbinden':'Installieren & verbinden'}</button><a class="ac-text-link" href="https://one.dash.cloudflare.com/" target="_blank" rel="noopener noreferrer">Cloudflare öffnen ↗</a></div><details class="ac-token-help"><summary>Wo finde ich den Token?</summary><p>Öffne deinen Tunnel im Cloudflare-Dashboard und kopiere den Tunnel-Token aus der Connector-Einrichtung. Füge den Token ohne Installationsbefehl ein.</p></details></form>${value.installed?'</details>':''}
     <section class="ac-route"><h4>Öffentliche Route</h4><p>Ordne deinen öffentlichen Hostnamen in Cloudflare dem lokalen HTTP-Ziel von Titan zu.</p>${r.service_url?`<div class="ac-service"><span>Service URL in Cloudflare</span><code>${esc(r.service_url)}</code></div>`:'<p class="ac-muted">Das lokale Ziel erscheint nach der Installation.</p>'}<p class="ac-muted">Der Tunnel-Token kann die Route in deinem Cloudflare-Konto nicht anlegen.</p>${value.installed?`<form data-apps-address-form><label for="ac-route-origin">Öffentliche Titan-Adresse<input id="ac-route-origin" type="url" name="public_origin" required placeholder="https://nas.example.de" value="${esc(r.public_origin)}" ${disabled}></label><div class="ac-actions"><button class="button primary" type="submit" ${disabled}>Adresse speichern & prüfen</button>${r.public_origin&&r.enabled?`<a class="button" href="${esc(r.public_origin)}" target="_blank" rel="noopener noreferrer">Zugang öffnen ↗</a>`:''}</div></form>`:''}</section>
    </div><section class="ac-history" aria-label="Installationsverlauf"><h4>Installationsschritte</h4><p>Hier siehst du die tatsächlichen Ergebnisse auf deinem NAS.</p><div data-apps-timeline>${timeline(value)}</div></section></div>
    ${value.diagnosis.checks.length?`<details class="ac-diagnosis"><summary>Ergebnis der Verbindungsprüfung</summary>${value.diagnosis.checks.map(check=>`<p><strong>${check.ok===true?'✓':check.ok===false?'!':'—'} ${esc(check.name)}</strong><br>${esc(check.message)}</p>`).join('')}</details>`:''}
    <p class="ac-operation" data-apps-operation role="status" aria-live="polite"></p><p class="ac-notice is-error" data-apps-error role="alert" hidden></p>
   `}</section>
   <section class="ac-existing"><div class="ac-section-heading"><div><h2>Weitere installierte Apps <span>${other.length}</span></h2><p>Vorhandene Compose-Pakete bleiben hier verwaltbar.</p></div></div>${other.length?`<div class="ac-installed-list">${other.map(row=>`<article class="ac-installed-app"><span class="ac-existing-icon" aria-hidden="true">▦</span><div><strong>${esc(row.name)}</strong><small>${esc(row.status||'Installiert')}</small></div><button class="button small" type="button" data-apps-package="${esc(row.id)}">Verwalten</button></article>`).join('')}</div>`:'<p class="ac-empty">Noch keine weiteren Apps installiert.</p>'}</section>
  </section>`;
 }
 function dispose(){cleanup?.();cleanup=null;}
 function mount(scope,ctx={}){
  dispose();let panel=scope?.querySelector('[data-apps-center]');if(!panel)return null;
  let data=state(JSON.parse(panel.dataset.config)),alive=true,busy=false,progressRequest=null,pollTimer=null,serial=0,secret='';
  // The server enforces permissions too. Do not allow hydrated markup to grant them.
  if(ctx.admin!==undefined)data.admin=ctx.admin===true;if(ctx.demo!==undefined)data.demo=!!ctx.demo||data.demo;
  const controller=new AbortController(),view=scope.ownerDocument?.defaultView||globalThis,query=selector=>panel.querySelector(selector),request=(path,body)=>ctx.api(path,body,{signal:controller.signal});
  const redact=value=>secret?String(value??'').split(secret).join('[Token ausgeblendet]'):String(value??'');
  function normalize(value){return state({...data,installation:value},redact);}
  function lock(){for(const node of panel.querySelectorAll('button,input'))node.disabled=busy||!data.admin||data.demo||data.installation.status==='running';const refresh=query('[data-apps-refresh]');if(refresh)refresh.disabled=busy||!data.admin||data.demo;for(const node of panel.querySelectorAll('[data-apps-package]'))node.disabled=busy;const open=query('[data-apps-open]');if(open)open.disabled=false;const start=query('[data-apps-lifecycle="start"]'),stop=query('[data-apps-lifecycle="stop"]');if(start)start.disabled ||= data.installation.runtime.state==='running';if(stop)stop.disabled ||= data.installation.runtime.state!=='running';}
  function replace(value){if(!alive)return;const focused=scope.ownerDocument.activeElement,focusKey=panel.contains(focused)?focused?.getAttribute('data-apps-lifecycle')||focused?.getAttribute('name')||'':'';data=normalize(value);const holder=panel.parentElement;panel.outerHTML=render(data);panel=holder.querySelector('[data-apps-center]');lock();if(focusKey){const target=[...panel.querySelectorAll('input,button')].find(node=>node.getAttribute('name')===focusKey||node.getAttribute('data-apps-lifecycle')===focusKey);if(target&&!target.disabled)target.focus();}}
  function showError(error){if(!alive)return;const message=redact(error?.message||'Die App-Aktion konnte nicht abgeschlossen werden.'),node=query('[data-apps-error]');if(node){node.hidden=false;node.textContent=message;}else ctx.toast?.(message,true);const operation=query('[data-apps-operation]');if(operation)operation.textContent='';}
  function progress(){if(!alive||progressRequest)return progressRequest||Promise.resolve();const generation=serial;progressRequest=request(STATUS).then(value=>{if(alive&&busy&&generation===serial)replace(value);}).catch(()=>{}).finally(()=>{progressRequest=null;});return progressRequest;}
  function schedule(){if(!alive||busy||pollTimer!==null||data.demo||!data.admin||data.installation.status!=='running')return;pollTimer=view.setTimeout(async()=>{pollTimer=null;const generation=serial;try{const value=await request(STATUS);if(alive&&!busy&&generation===serial){replace(value);schedule();}}catch(error){if(alive&&error.name!=='AbortError'){showError(error);schedule();}}},2000);}
  async function run(kind,form){
   if(!alive||busy||!data.admin||data.demo||data.installation.status==='running'&&kind!=='refresh')return;
   const hadFocus=panel.contains(scope.ownerDocument.activeElement);let body,path=PATH,operation=kind;if(kind==='install'){const input=form.elements.tunnel_token;secret=input.value.trim();input.value='';if(!secret){showError(Error('Füge den Tunnel-Token ein.'));return;}body={app:APP,options:{tunnel_token:secret,public_origin:form.elements.public_origin?.value.trim()||data.installation.runtime.public_origin||''},expected_revision:data.installation.revision};}
   else if(kind==='address'){path+='/address';body={app:APP,public_origin:form.elements.public_origin.value.trim(),expected_revision:data.installation.revision};}
   else if(kind==='resume'){path+='/resume';body={app:APP,expected_revision:data.installation.revision};}
   else if(kind==='refresh')path=STATUS;
   busy=true;serial++;if(pollTimer!==null){view.clearTimeout(pollTimer);pollTimer=null;}lock();const error=query('[data-apps-error]');if(error)error.hidden=true;const indicator=query('[data-apps-operation]');if(indicator)indicator.textContent=kind==='refresh'?'Status wird geladen …':kind==='start'?'App wird gestartet …':kind==='stop'?'App wird gestoppt …':'Die Einrichtung läuft auf deinem NAS …';
   try{
    if(kind==='start'||kind==='stop'){await ctx.action('app_action',{app:APP,action:kind},{wait:true,signal:controller.signal});}
    else{const accepted=await request(path,body);if(!alive)return;if(kind==='refresh'){replace(accepted);return;}await progress();if(!alive)return;const wait=ctx.waitForJob||((result,options)=>view.TitanJobs.wait(ctx.api,result.job,options));await wait(accepted,{signal:controller.signal,onProgress:()=>void progress()});}
    if(!alive)return;serial++;const fresh=await request(STATUS);if(!alive)return;replace(fresh);Promise.resolve().then(()=>ctx.onAppsChanged?.()).catch(()=>{});ctx.toast?.(kind==='stop'?'Cloudflare Tunnel gestoppt.':fresh.runtime?.public_ready?'Öffentlicher Titan-Zugang geprüft.':fresh.setup?.needs_domain?'Connector verbunden. Ergänze die öffentliche Adresse.':operation==='start'?'Cloudflare Tunnel gestartet.':'App-Aktion abgeschlossen. Prüfe den Verbindungsstatus.');
   }catch(error){if(alive&&error.name!=='AbortError'){serial++;try{const fresh=await request(STATUS);if(alive)replace(fresh);}catch{}if(alive)showError(error);}}
   finally{busy=false;secret='';if(alive){lock();schedule();if(hadFocus&&scope.ownerDocument.activeElement===scope.ownerDocument.body)query('[data-apps-status]')?.focus();}}
  }
  const submit=event=>{if(event.target.matches?.('[data-apps-install-form]')){event.preventDefault();void run('install',event.target);}else if(event.target.matches?.('[data-apps-address-form]')){event.preventDefault();void run('address',event.target);}};
  function showDetail(){const detail=query('[data-apps-detail]');if(!detail)return;data.details_open=true;panel.setAttribute('data-config',JSON.stringify(data));detail.hidden=false;const open=query('[data-apps-open]');if(open){open.setAttribute('aria-expanded','true');open.textContent='Details';}detail.focus();detail.scrollIntoView?.({block:'nearest'});}
  const click=event=>{const node=event.target.closest?.('[data-apps-open],[data-apps-refresh],[data-apps-resume],[data-apps-lifecycle],[data-apps-package]');if(!node||!panel.contains(node)||node.disabled)return;event.preventDefault();if(node.hasAttribute('data-apps-open'))showDetail();else if(node.hasAttribute('data-apps-package')){const id=node.dataset.appsPackage;if(data.installed.some(row=>row.id===id&&id!==APP))try{Promise.resolve(ctx.openPackage?.(id)).catch(showError);}catch(error){showError(error);}}else void run(node.hasAttribute('data-apps-resume')?'resume':node.dataset.appsLifecycle||'refresh');};
  scope.addEventListener('submit',submit);scope.addEventListener('click',click);if(!data.admin)replace(data.installation);lock();schedule();const instance={refresh:()=>run('refresh'),showDetail,dispose(){if(!alive)return;alive=false;serial++;controller.abort();if(pollTimer!==null)view.clearTimeout(pollTimer);scope.removeEventListener('submit',submit);scope.removeEventListener('click',click);for(const node of panel.querySelectorAll('input[type="password"]'))node.value='';secret='';}};cleanup=instance.dispose;return instance;
 }
 return {render,mount,dispose,state,timeline,publicUrl:value=>url(value,true)};
});
