'use strict';
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanControlPanel=ui;})(typeof window==='undefined'?null:window,function(){
 const groups=[
  ['Dateien und Zugriff',[
   ['shares','Freigegebene Ordner','shares','Ordner, SMB-Zugriff und Berechtigungen'],
   ['users','Benutzer','users','Konten, Kennwörter und Zugriffsrechte'],
   ['groups','Gruppen und Rechte','users','Mitgliedschaften und vererbte Zugriffe']]],
  ['System',[
   ['general','Allgemein','settings','Servername und Zugriff'],
   ['security','Sicherheit','settings','Anmeldeschutz, Zwei-Faktor-Anmeldung und Sitzungen'],
   ['updates','Updates & Rollback','updates','Titan, System und Sicherheitsupdates'],
   ['monitoring','Systemzustand','monitoring','Dienste, Laufwerke und Warnungen'],
   ['components','Komponenten','control','Docker, QEMU und Systemdienste']]],
  ['Anwendungen und Wartung',[
   ['services','Dienste','services','Start, Stopp und Autostart'],
   ['backups','Datensicherung','backups','Sicherungsziel, Zeitplan und Versionen'],
   ['logs','Protokoll','logs','Anmeldungen und Verwaltungsaktionen']]]
 ];
 const items=groups.flatMap(group=>group[1]),pages=new Set(items.map(item=>item[0]).filter(id=>!['general','components'].includes(id)));
 const tileArtwork={shares:'shares',users:'users',groups:'groups',general:'settings',security:'security',updates:'updates',monitoring:'monitoring',components:'services',services:'services',backups:'backups',logs:'logs'};
 const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function resolve(hash){const [root,query]=String(hash||'').replace(/^#/,'').split('?');if(!['settings','control'].includes(root))return null;const value=new URLSearchParams(query||'').get('section')||'';const section=items.some(item=>item[0]===value)?value:'';return {section,page:pages.has(section)?section:'settings'};}
 function link(id){return '#settings'+(id?'?section='+id:'');}
 function internal(hash){const root=String(hash).replace(/^#/,'').split('?')[0];return pages.has(root)?link(root):hash;}
 function deviceOverview(symbol,esc){
  const metric=(id,name,target)=>`<a class="cp-device-metric" href="${target}"><span>${name}<strong data-cp-metric="${id}">—</strong></span><div class="cp-device-meter" role="meter" aria-label="${name}" aria-valuemin="0" aria-valuemax="100"><i data-cp-meter="${id}"></i></div><small data-cp-metric-note="${id}">Wird geladen …</small></a>`;
  return `<aside class="cp-sidebar cp-device-sidebar" aria-label="Dein Titan"><div class="cp-device-preview" aria-hidden="true"><span class="cp-preview-greeting">Dein Zuhause für Daten</span><div class="cp-preview-widgets"><i></i><i></i><i></i></div><div class="cp-preview-apps">${['files','apps','docker','vms','settings'].map(id=>`<span>${symbol(id)}</span>`).join('')}</div><div class="cp-preview-dock"><i></i><i></i><i></i><i></i></div></div><div class="cp-device-identity"><img src="/logo.svg" alt="" width="34" height="34"><div><h2 data-cp-device-name>Titan</h2><span data-cp-device-label>Dein persönlicher Server</span></div></div><dl class="cp-device-facts"><div><dt>Version</dt><dd data-cp-device-version>—</dd></div><div><dt>Adresse</dt><dd data-cp-device-address>—</dd></div><div><dt>Laufzeit</dt><dd data-cp-device-uptime>—</dd></div></dl><div class="cp-device-power"><button type="button" data-action="logout">Abmelden</button><button type="button" data-action="system-reboot">Neustart</button><button type="button" data-action="system-shutdown" class="danger">Ausschalten</button></div><div class="cp-device-metrics">${metric('storage','Speicher','#storage')}${metric('memory','Arbeitsspeicher','#resources')}${metric('cpu','CPU','#resources')}</div><a class="cp-open-resources" href="#resources">${symbol('monitoring')}<span>Live-Auslastung öffnen</span><span aria-hidden="true">↗</span></a><p class="cp-metrics-status" data-cp-metrics-status role="status"></p></aside>`;
 }
 function render(section,content,{icon,esc=escape}={}){
  const selected=items.find(item=>item[0]===section),symbol=id=>typeof icon==='function'?icon(id):'';
  const tileIcon=(id,glyph)=>Object.hasOwn(tileArtwork,id)?`<img class="cp-tile-artwork" src="/app-icons/titan-${tileArtwork[id]}.svg" alt="" width="32" height="32" draggable="false">`:symbol(glyph);
  const nav=`<aside class="cp-sidebar"><a class="cp-home ${section?'':'active'}" href="#settings" ${section?'':'aria-current="page"'}>${symbol('control')}<span>Alle Einstellungen</span></a>${groups.map(([title,children])=>`<section><h2>${esc(title)}</h2>${children.map(([id,name,glyph])=>`<a href="${link(id)}" ${id===section?'class="active" aria-current="page"':''}>${tileIcon(id,glyph)}<span>${esc(name)}</span></a>`).join('')}</section>`).join('')}</aside>`;
  const tile=([id,name,glyph,description])=>`<div class="cp-tile" data-cp-item data-search="${esc((name+' '+description).toLocaleLowerCase('de-DE'))}"><a href="${link(id)}"><span class="cp-color-icon" data-app="${glyph}" aria-hidden="true">${tileIcon(id,glyph)}</span><span class="cp-setting-copy"><strong>${esc(name)}</strong><small>${esc(description)}</small></span><span class="cp-row-arrow" aria-hidden="true">›</span></a><button type="button" class="cp-pin" data-cp-pin="${id}" aria-label="${esc(name)} als Favorit merken" aria-pressed="false" title="Als Favorit merken">☆</button></div>`;
  const hub=`<div class="cp-overview" data-cp-overview><header class="cp-overview-heading"><h1>Einstellungen</h1><details class="cp-overview-options"><summary class="button small" aria-label="Weitere Einstellungsaktionen">···</summary><div><a href="/api/diagnostics?download=1">Diagnose herunterladen</a><span>Darstellung der Einstellungen</span><div class="cp-view-switch" role="group" aria-label="Ansicht der Einstellungen"><button type="button" data-cp-view="list" aria-pressed="true">Liste</button><button type="button" data-cp-view="grid" aria-pressed="false">Symbole</button></div></div></details></header><div class="cp-overview-tools"><div class="cp-category-tabs" role="tablist" aria-label="Einstellungen filtern">${[['all','Alle'],['0','Zugriff'],['1','System'],['2','Wartung']].map(([key,label])=>`<button type="button" role="tab" data-cp-category-filter="${key}" aria-selected="${key==='all'}" tabindex="${key==='all'?0:-1}">${label}</button>`).join('')}</div><label class="cp-search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><span class="sr-only">Einstellungen durchsuchen</span><input type="search" placeholder="Suchen …" data-cp-search maxlength="200"></label></div><section class="cp-category cp-favorites" data-cp-favorites hidden><h2>Favoriten</h2><div class="cp-favorites-grid" data-cp-favorite-items></div></section>${groups.map(([title,children],index)=>`<section class="cp-category" data-cp-category="${index}"><h2>${esc(title)}</h2><div class="cp-icon-grid">${children.map(tile).join('')}</div></section>`).join('')}<p class="empty" data-cp-empty hidden>Keine passende Einstellung gefunden.</p></div>`;
  return `<section class="cp-window cp-designed" data-control-panel data-section="${esc(section)}" data-view="list"><header class="cp-toolbar"><a href="#settings" class="button small" aria-label="Alle Einstellungen anzeigen">${symbol('control')}<span>Alle Einstellungen</span></a><span class="cp-current">${esc(selected?.[1]||'Übersicht')}</span><label class="cp-mobile-select"><span class="sr-only">Einstellungsbereich</span><select data-cp-select><option value="">Übersicht</option>${items.map(([id,name])=>`<option value="${id}" ${id===section?'selected':''}>${esc(name)}</option>`).join('')}</select></label><a class="button small cp-diagnostics" href="/api/diagnostics?download=1">Diagnose</a></header><div class="cp-layout ${section?'':'cp-device-layout'}">${section?nav:deviceOverview(symbol,esc)}<div class="cp-content" tabindex="-1">${section?content:hub}</div></div></section>`;
 }
 const allowed=new Set(items.map(item=>item[0]));
 function normalizePreferences(value){return {view:value?.view==='grid'?'grid':'list',favorites:Array.isArray(value?.favorites)?[...new Set(value.favorites.filter(id=>allowed.has(id)))].slice(0,items.length):[]};}
 function readPreferences(storage,userName){try{return normalizePreferences(JSON.parse(storage.getItem('titan.control-panel.'+encodeURIComponent(userName||'local'))));}catch{return normalizePreferences(null);}}
 function writePreferences(storage,userName,value){try{storage.setItem('titan.control-panel.'+encodeURIComponent(userName||'local'),JSON.stringify(normalizePreferences(value)));return true;}catch{return false;}}
 let mounted=null;
 function dispose(){mounted?.();mounted=null;}
 const measured=value=>typeof value==='number'&&Number.isFinite(value)&&value>=0;
 function compactBytes(value){if(!measured(value))return '—';const units=['B','KB','MB','GB','TB','PB'],index=Math.min(units.length-1,Math.floor(Math.log(Math.max(1,value))/Math.log(1024)));return (value/1024**index).toLocaleString('de-DE',{maximumFractionDigits:index>1?1:0})+' '+units[index];}
 function deviceValues(status={}){const used=status.memory_occupied??status.memory_used,storage=status.storage||{},percent=(value,total)=>measured(value)&&measured(total)&&total>0?Math.min(100,value/total*100):null;return {name:status.hostname||'Titan',uptime:measured(status.uptime)?status.uptime<3600?Math.floor(status.uptime/60)+' Min.':status.uptime<86400?Math.floor(status.uptime/3600)+' Std. '+Math.floor(status.uptime%3600/60)+' Min.':Math.floor(status.uptime/86400)+' Tage '+Math.floor(status.uptime%86400/3600)+' Std.':'—',cpu:{percent:measured(status.cpu_percent)?Math.min(100,status.cpu_percent):null,value:measured(status.cpu_percent)?status.cpu_percent.toLocaleString('de-DE',{maximumFractionDigits:1})+' %':'—',note:measured(status.cpus)?status.cpus+' logische CPUs':'Messung wird ermittelt'},memory:{percent:percent(used,status.memory_total),value:compactBytes(used),note:compactBytes(status.memory_total)+' gesamt'},storage:{percent:percent(storage.used,storage.total),value:compactBytes(storage.used),note:compactBytes(storage.total)+' gesamt'}};}
 function mount(scope,{userName='local',api,session={}}={}){
  dispose();const root=scope?.querySelector('[data-control-panel]');if(!root)return;
  const win=root.ownerDocument.defaultView,doc=root.ownerDocument,listeners=[];let storage,alive=true,busy=false,timer=null,category='all',displayName='';try{storage=win.localStorage;}catch{}
  const state=readPreferences(storage,userName),search=root.querySelector('[data-cp-search]');
  const listen=(node,type,fn)=>{if(!node)return;node.addEventListener(type,fn);listeners.push([node,type,fn]);};
  function filter(){if(!search)return;const words=String(search.value||'').toLocaleLowerCase('de-DE').trim().split(/\s+/).filter(Boolean);let count=0;
   root.querySelectorAll('[data-cp-category]').forEach(group=>{let visible=0;group.querySelectorAll('[data-cp-item]').forEach(item=>{item.hidden=!(category==='all'||group.dataset.cpCategory===category)||!words.every(word=>item.dataset.search.includes(word));if(!item.hidden){visible++;count++;}});group.hidden=!visible;});
   const favorites=root.querySelector('[data-cp-favorites]');if(favorites)favorites.hidden=Boolean(words.length)||category!=='all'||!state.favorites.length;const empty=root.querySelector('[data-cp-empty]');if(empty)empty.hidden=count>0;
  }
  function update(){root.dataset.view=state.view;root.querySelectorAll('[data-cp-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.cpView===state.view)));
   root.querySelectorAll('[data-cp-pin]').forEach(button=>{const active=state.favorites.includes(button.dataset.cpPin);button.setAttribute('aria-pressed',String(active));button.textContent=active?'★':'☆';const name=items.find(item=>item[0]===button.dataset.cpPin)?.[1]||'';button.setAttribute('aria-label',name+(active?' aus Favoriten entfernen':' als Favorit merken'));button.title=active?'Aus Favoriten entfernen':'Als Favorit merken';});
   const favoriteItems=root.querySelector('[data-cp-favorite-items]');if(favoriteItems)favoriteItems.innerHTML=state.favorites.map(id=>{const item=items.find(item=>item[0]===id);return `<a class="cp-favorite-link" href="${link(id)}"><strong>${escape(item[1])}</strong><span aria-hidden="true">↗</span></a>`;}).join('');filter();
  }
  function setText(selector,value){const node=root.querySelector(selector);if(node&&node.textContent!==String(value))node.textContent=String(value);}
  function paint(status){if(!alive)return;const values=deviceValues(status);setText('[data-cp-device-name]',displayName||values.name);setText('[data-cp-device-uptime]',values.uptime);for(const id of ['cpu','memory','storage']){const metric=values[id];setText(`[data-cp-metric="${id}"]`,metric.value);setText(`[data-cp-metric-note="${id}"]`,metric.note);const meter=root.querySelector(`[data-cp-meter="${id}"]`);if(meter){meter.style.width=(metric.percent??0)+'%';const element=meter.parentElement;if(metric.percent===null)element.removeAttribute('aria-valuenow');else element.setAttribute('aria-valuenow',String(Math.round(metric.percent)));element.setAttribute('aria-valuetext',metric.percent===null?'Nicht verfügbar':Math.round(metric.percent)+' Prozent');}}setText('[data-cp-metrics-status]',session.demo?'Demo · Beispieldaten':'');}
  async function refresh(){if(!alive||busy||doc.hidden||!api)return;if(root.isConnected===false){dispose();return;}busy=true;try{const status=await api('/api/status');paint(status);}catch{if(alive)setText('[data-cp-metrics-status]','Live-Werte momentan nicht erreichbar');}finally{busy=false;}}
  listen(search,'input',filter);listen(search,'keydown',event=>{if(event.key==='Escape'&&search.value){event.preventDefault();search.value='';filter();}});
  const categories=[...root.querySelectorAll('[data-cp-category-filter]')];
  function chooseCategory(button){category=button.dataset.cpCategoryFilter;for(const item of categories){item.setAttribute('aria-selected',String(item===button));item.tabIndex=item===button?0:-1;}filter();}
  categories.forEach((button,index)=>{listen(button,'click',()=>chooseCategory(button));listen(button,'keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?categories.length-1:(index+(event.key==='ArrowLeft'?-1:1)+categories.length)%categories.length;chooseCategory(categories[next]);categories[next].focus();});});
  root.querySelectorAll('[data-cp-pin]').forEach(button=>listen(button,'click',()=>{const id=button.dataset.cpPin;state.favorites=state.favorites.includes(id)?state.favorites.filter(value=>value!==id):[...state.favorites,id];writePreferences(storage,userName,state);update();}));
  root.querySelectorAll('[data-cp-view]').forEach(button=>listen(button,'click',()=>{state.view=button.dataset.cpView==='grid'?'grid':'list';writePreferences(storage,userName,state);update();}));
  listen(root.querySelector('[data-cp-select]'),'change',event=>{win.location.hash=link(event.target.value);});
  listen(doc,'pointerdown',event=>{const menu=root.querySelector('.cp-overview-options');if(menu?.open&&!menu.contains(event.target))menu.open=false;});listen(doc,'keydown',event=>{const menu=root.querySelector('.cp-overview-options');if(event.key==='Escape'&&menu?.open){menu.open=false;menu.querySelector('summary')?.focus();event.preventDefault();}});
  update();setText('[data-cp-device-version]',session.version?'v'+session.version:'—');setText('[data-cp-device-address]',win.location?.hostname||'—');setText('[data-cp-device-label]',session.demo?'Demo · Beispieldaten':'Dein persönlicher Server');
  if(root.querySelector('.cp-device-sidebar')&&api){void refresh();void api('/api/settings').then(settings=>{if(alive){displayName=settings.hostname||'Titan';setText('[data-cp-device-name]',displayName);}}).catch(()=>{});timer=win.setInterval(refresh,8000);listen(doc,'visibilitychange',()=>{if(!doc.hidden)void refresh();});}
  const cleanup=()=>{if(!alive)return;alive=false;if(timer!==null)win.clearInterval(timer);for(const[node,type,fn]of listeners)node.removeEventListener(type,fn);};mounted=cleanup;return {filter,paint,refresh,dispose};
 }
 return {groups,resolve,internal,render,mount,normalizePreferences,readPreferences,writePreferences,dispose,deviceValues,compactBytes};
});
