'use strict';
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanShortcuts=ui;})(typeof window==='undefined'?null:window,function(){
 const validKey=key=>typeof key==='string'&&/^(?:(tool|app):[a-zA-Z0-9_-]{1,64}|vm:[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12})$/.test(key);
 const idOf=row=>typeof row==='string'?row:row.id;
 const desktopPreferences=value=>({background_click:value?.background_click==='minimize'?'minimize':'none',dock_auto_hide:value?.dock_auto_hide===true,transparency:Number.isInteger(value?.transparency)&&value.transparency>=0&&value.transparency<=100?value.transparency:40,color_mode:['light','dark','system'].includes(value?.color_mode)?value.color_mode:'dark'});
 const defaults=['tool:files','tool:docker','tool:settings','tool:apps','tool:storage'];
 function normalize(value={},allowed=[]){
  const seen=new Set(),folders=new Set(),tools=new Set(allowed),hidden=new Set(value.hidden||[]);
  const take=key=>validKey(key)&&!seen.has(key)&&(key.startsWith('app:')||key.startsWith('vm:')||tools.has(key))&&!hidden.has(key)?(seen.add(key),true):false;
  const input=value.version===2||value.items?.length?value.items:defaults;
  const items=[];for(const row of Array.isArray(input)?input:[]){if(typeof row==='string'){if(take(row))items.push(row);}else if(row&&/^folder-[a-z0-9-]{1,40}$/.test(row.id)&&!folders.has(row.id)){folders.add(row.id);items.push({id:row.id,name:String(row.name||'Ordner').slice(0,40),items:(Array.isArray(row.items)?row.items:[]).filter(take)});}}
  const positions={};for(const row of items){const key=idOf(row),p=value.positions?.[key];if(p&&Number.isInteger(p.x)&&Number.isInteger(p.y)&&p.x>=0&&p.y>=0&&p.x<32&&p.y<128)positions[key]={x:p.x,y:p.y};}
  if(!value.docker_added&&items.length&&tools.has('tool:docker')&&!has(items,'tool:docker')&&!hidden.has('tool:docker'))items.push('tool:docker');
  return {version:2,items,positions,desktop:desktopPreferences(value.desktop),docker_added:true,icon_size:['small','medium','large'].includes(value.icon_size)?value.icon_size:'medium',widgets:value.widgets||{visible:true,collapsed:false,items:['cpu','ram','health']}};
 }
 function place(items,positions,columns,rows){const used=new Set(),out={};columns=Math.max(1,columns);rows=Math.max(1,rows);for(const item of items){const key=idOf(item),preferred=positions[key];let x=preferred?Math.min(columns-1,preferred.x):0,y=preferred?Math.min(rows-1,preferred.y):0;while(used.has(x+','+y)){y++;if(y>=rows){y=0;x++;}if(x>=columns){x=0;rows++;y=rows-1;}}used.add(x+','+y);out[key]={x,y};}return out;}
 function remove(items,key){return items.filter(row=>idOf(row)!==key).map(row=>typeof row==='string'?row:{...row,items:row.items.filter(id=>id!==key)});}
 function group(items,source,target){if(source===target||!validKey(source))return items;const next=remove(items,source),dest=next.find(row=>idOf(row)===target);if(!dest)return items;if(typeof dest==='object')dest.items.push(source);else next.splice(next.indexOf(dest),1,{id:'folder-'+Date.now().toString(36),name:'Ordner',items:[dest,source]});return next;}
 const has=(items,key)=>items.some(row=>row===key||typeof row==='object'&&row.items.includes(key));
 function safeUrl(value){try{const url=new URL(value);return ['http:','https:'].includes(url.protocol)&&!url.username&&!url.password?url.href:'';}catch{return '';}}
 async function mount(surface,{tools,user,icon,esc,api,toast,open,menu,action,confirm}){
  const doc=surface.ownerDocument,win=doc.defaultView;let alive=true,opened=null,contextKey=null,contextOrigin=null,contextDialog=null,contextAnchor=null,gesture=null,blockClick=0,suppressed=null,revision=0,saving=false,failed=false,readonly=false,apps=[],appsLoading=true,vmsLoading=true,appsBusy=false,vmsBusy=false,layout;const pendingApps=new Map();const actionController=new AbortController();
  const entries=new Map(tools.map(([id,name,detail])=>['tool:'+id,{name,detail,glyph:id,href:'#'+id}]));
  const requests=await Promise.allSettled([api('/api/launcher-layout')]);
  layout=normalize(requests[0].status==='fulfilled'?requests[0].value:{},tools.map(t=>'tool:'+t[0]));
  if(requests[0].status==='rejected'){readonly=true;toast('Desktop-Einstellungen konnten nicht geladen werden. Änderungen werden erst nach erneutem Laden gespeichert.',true);}
  function updateVMs(data){for(const key of entries.keys())if(key.startsWith('vm:'))entries.delete(key);for(const vm of data?.vms||[]){const key='vm:'+vm.id;if(validKey(key))entries.set(key,{name:vm.display_name||vm.name,detail:'VM-Konsole öffnen',glyph:'vms',vm:vm.id,href:'#vms?vm='+encodeURIComponent(vm.id)+'&tab=console'});}}
  async function refreshVMs(){if(vmsBusy||user.role!=='admin'&&!user.permissions?.vms?.allowed)return;vmsBusy=true;try{const data=await api('/api/vms');if(alive){vmsLoading=false;updateVMs(data);if(!gesture&&!folderDialog.open&&context.hidden)render();}}catch{vmsLoading=false;if(alive&&!gesture&&!folderDialog.open&&context.hidden)render();}finally{vmsBusy=false;}}
  function updateApps(data){for(const key of entries.keys())if(key.startsWith('app:'))entries.delete(key);apps=data?.installed||[];for(const app of apps){const key='app:'+app.id;if(!validKey(key))continue;const endpoint=(app.container?.endpoints||app.endpoints||[]).find(e=>e.scope==='lan'&&safeUrl(e.url));const primary=app.web_state||app.container?.web_state||app.container?.state||app.state,running=app.web_available===true||app.container?.web_available===true;entries.set(key,{name:app.name||app.id,detail:running?'Im neuen Tab öffnen':app.web_message||app.status||'App ist gestoppt',glyph:'apps',app:app.id,url:running?safeUrl(endpoint?.url):'',state:primary,active:['running','restarting','paused'].includes(app.state||app.container?.state)||(app.services||[]).some(service=>['running','restarting','paused'].includes(service.state)),web_message:app.web_message||app.container?.web_message});}}
  // VM discovery can be slow when libvirt is starting. Render the desktop first.
  if(user.role!=='admin'){const permitted=key=>!key.startsWith('app:')||Boolean(user.permissions?.apps?.allowed);const vmAllowed=key=>!key.startsWith('vm:')||Boolean(user.permissions?.vms?.allowed);layout.items=layout.items.filter(row=>typeof row!=='string'||permitted(row)&&vmAllowed(row)).map(row=>typeof row==='string'?row:{...row,items:row.items.filter(key=>permitted(key)&&vmAllowed(key))});}
  const context=doc.createElement('div');context.className='shortcut-context desktop-quick-actions';context.setAttribute('role','menu');context.hidden=true;doc.body.append(context);
  const folderDialog=doc.createElement('dialog');folderDialog.className='desktop-folder-dialog';folderDialog.setAttribute('aria-label','Desktop-Ordner');doc.body.append(folderDialog);
  surface.setAttribute('tabindex','0');const content=doc.createElement('div');content.className='desktop-shortcuts-layer';surface.append(content);
  const entry=key=>entries.get(key)||((key.startsWith('vm:')?vmsLoading:appsLoading)?{name:key.startsWith('vm:')?'Virtuelle Maschine':key.replace(/^app:/,''),detail:'Status wird geladen …',glyph:key.startsWith('vm:')?'vms':'apps'}:null)||{name:key.startsWith('vm:')?'VM nicht verfügbar':key.replace(/^app:/,''),detail:key.startsWith('vm:')?'VM nicht mehr verfügbar. Verknüpfung entfernen oder VM-Verwaltung öffnen.':'App nicht verfügbar',glyph:key.startsWith('vm:')?'vms':'apps'};
  function image(key){const item=entry(key);return item.app&&win.TitanArtwork?win.TitanArtwork.render(item.app):win.TitanArtwork?.tool(item.glyph)||icon(item.glyph);}
  function card(row){const folder=typeof row==='object',key=idOf(row),item=folder?{name:row.name}:entry(key),tag=item.app&&item.url?'a':'button',link=tag==='a'?` href="${esc(item.url)}" target="_blank" rel="noopener noreferrer" draggable="false"`:'';return `<div class="desktop-shortcut" data-shortcut="${esc(key)}" ${item.app&&pendingApps.has(item.app)?'aria-busy="true"':''}><${tag}${link} class="shortcut-open" data-shortcut-open="${esc(key)}" aria-label="${esc(item.name)}" title="${esc(folder?'Ordner öffnen':item.detail||item.name)}"><span class="${folder?'shortcut-folder-icon':'desktop-app-icon'}" data-app="${esc(item.glyph||'files')}">${folder?row.items.slice(0,4).map(id=>'<span>'+image(id)+'</span>').join(''):image(key)}</span><span class="shortcut-label">${esc(item.name)}</span></${tag}><button class="shortcut-more" data-shortcut-more="${esc(key)}" aria-haspopup="menu" aria-expanded="false" aria-label="${esc(item.name)}: Schnellaktionen" title="Schnellaktionen">⋯</button></div>`;}
  let displayed={},renderedMarkup=null;
  const cell=()=>({small:92,medium:128,large:144}[layout.icon_size]||108);
  function position(){if(!alive)return;surface.dataset.iconSize=layout.icon_size;const size=cell(),cols=Math.max(1,Math.floor(surface.clientWidth/size)),top=Number(surface.dataset.widgetDefaultBottom??260),start=Math.ceil((Math.max(130,top)+18)/size),columns=Math.min(cols,Math.max(1,layout.items.length)),left=Math.max(0,Math.floor((cols-columns)/2)),seeded={...layout.positions};let index=0;for(const row of layout.items){const key=idOf(row);if(!seeded[key]){seeded[key]={x:left+index%columns,y:start+Math.floor(index/columns)};index++;}}const rows=Math.max(start+Math.ceil(layout.items.length/columns),Math.floor(surface.clientHeight/size),1);displayed=place(layout.items,seeded,cols,rows);surface.querySelectorAll('[data-shortcut]').forEach(node=>{const p=displayed[node.dataset.shortcut];node.style.left=p.x*size+'px';node.style.top=p.y*size+'px';node.style.transform='';node.classList.remove('shortcut-dragging');node.classList.remove('shortcut-group-target');});}
  function welcome(){const now=new Date(),hour=now.getHours(),salutation=hour<5?'Gute Nacht':hour<11?'Guten Morgen':hour<18?'Guten Tag':'Guten Abend',date=new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'numeric',month:'long'}).format(now);return `<header class="desktop-welcome"><img class="desktop-welcome-mark" src="/brand/titan-wordmark.svg" alt="Titan" width="220" height="44" draggable="false"><h1>${salutation}, ${esc(user.name)}.</h1><p>${esc(date)}</p></header>`;}
  function render(){if(!alive)return;const focused=surface.contains(doc.activeElement)?doc.activeElement:null,focusKey=focused?.closest('[data-shortcut]')?.dataset.shortcut,more=focused?.hasAttribute('data-shortcut-more'),markup=welcome()+layout.items.map(card).join('')+`<div class="desktop-personalize"><button type="button" data-widgets-picker aria-label="Widgets hinzufügen">${icon('plus')}<span>Widgets hinzufügen</span></button><button type="button" data-desktop-customize aria-haspopup="menu" aria-label="Desktop anpassen">${icon('settings')}<span>Desktop anpassen</span></button></div><div class="desktop-save-state" role="status">${readonly?'Einstellungen nicht geladen':failed?'Änderungen noch nicht gespeichert':''}${failed?'<button type="button" data-desktop-retry>Erneut speichern</button>':''}</div><span class="desktop-watermark">Titan</span>`;if(markup!==renderedMarkup){content.innerHTML=markup;renderedMarkup=markup;}position();if(opened)renderFolder();if(focusKey&&doc.activeElement!==focused)surface.querySelector(`[data-shortcut-${more?'more':'open'}="${focusKey}"]`)?.focus({preventScroll:true});}
  async function persist(){if(readonly)return;if(saving)return;saving=true;let savedRevision;try{do{savedRevision=revision;const value=JSON.parse(JSON.stringify(layout));await api('/api/launcher-layout',value);}while(alive&&savedRevision!==revision);failed=false;}catch(error){failed=true;if(alive)toast(error.message||'Desktop konnte nicht gespeichert werden.',true);}finally{saving=false;if(alive){const status=surface.querySelector('.desktop-save-state');if(status)status.innerHTML=failed?'Änderungen noch nicht gespeichert <button type="button" data-desktop-retry>Erneut speichern</button>':'';}}}
  function change(){const roots=new Set(layout.items.map(idOf));for(const key of Object.keys(layout.positions))if(!roots.has(key))delete layout.positions[key];revision++;render();void persist();}
  function syncMenuPin(key){doc.querySelectorAll(`[data-menu-add="${key}"]`).forEach(node=>{node.disabled=has(layout.items,key)||readonly;node.textContent=has(layout.items,key)?'Auf dem Desktop':'Zum Desktop hinzufügen';});}
  function add(key){if(readonly||!entries.has(key)||has(layout.items,key))return false;layout.items.push(key);change();syncMenuPin(key);return true;}
  function erase(key){if(readonly)return;const focused=doc.activeElement?.closest('[data-shortcut]')?.dataset.shortcut===key;layout.items=remove(layout.items,key);delete layout.positions[key];change();syncMenuPin(key);if(focused)(opened?folderDialog.querySelector('button'):surface.querySelector('[data-shortcut-open]')||surface)?.focus();}
  function renderFolder(){const folder=layout.items.find(row=>row.id===opened);if(!folder){folderDialog.close();opened=null;return;}folderDialog.innerHTML=`<header><h2>${esc(folder.name)}</h2><button type="button" class="button" data-folder-close>Schließen</button></header><div class="folder-shortcuts">${folder.items.map(card).join('')||'<p>Dieser Ordner ist leer. Ziehe eine Verknüpfung auf ihn.</p>'}</div><form data-folder-name><label>Ordnername<input name="name" value="${esc(folder.name)}" maxlength="40" required></label><button class="button" type="submit">Umbenennen</button></form>`;}
  function openItem(key){const folder=layout.items.find(row=>row.id===key);if(folder){opened=key;renderFolder();folderDialog.showModal();return;}const item=entry(key);if(item.app){if(item.url)win.open(item.url,'_blank','noopener,noreferrer');else toast(item.web_message||'Diese App hat keinen erreichbaren Webzugang. Öffne ihre Verwaltung.',true);}else if(item.href)open(item.href);}
  function closeContext(restore=true){if(context.hidden)return;context.hidden=true;contextOrigin?.setAttribute?.('aria-expanded','false');if(restore&&contextOrigin?.isConnected!==false)contextOrigin?.focus?.({preventScroll:true});}
  function dispatch(name,detail={}){doc.dispatchEvent(new win.CustomEvent(name,{bubbles:true,detail}));}
  function menuButton(command,label,{glyph='apps',detail='',disabled=false,extra='',role='menuitem',checked}={}){return `<button type="button" role="${role}" data-context="${command}" ${disabled?'disabled':''} ${checked===undefined?'':`aria-checked="${checked}"`} ${extra}><span class="quick-action-icon" aria-hidden="true">${icon(glyph)}</span><span class="quick-action-copy"><strong>${esc(label)}</strong>${detail?`<small>${esc(detail)}</small>`:''}</span></button>`;}
  function positionContext(){
   if(!alive||context.hidden||!contextAnchor)return;const dialog=contextDialog?.getBoundingClientRect(),left=Math.max(8,dialog?dialog.left+8:8),top=Math.max(8,dialog?dialog.top+8:8),right=Math.min(win.innerWidth-8,dialog?dialog.right-8:win.innerWidth-8),bottom=Math.min(win.innerHeight-8,dialog?dialog.bottom-8:win.innerHeight-8);
   context.style.maxWidth=Math.max(0,right-left)+'px';context.style.maxHeight=Math.max(0,bottom-top)+'px';context.style.left=left+'px';context.style.top=top+'px';const rect=context.getBoundingClientRect(),x=Math.max(left,Math.min(contextAnchor.x,right-rect.width)),y=Math.max(top,Math.min(contextAnchor.y,bottom-rect.height));
   // A transformed modal can establish the fixed-position containing block.
   // Correct against measured viewport coordinates, including that offset.
   context.style.left=left+x-rect.left+'px';context.style.top=top+y-rect.top+'px';
  }
  function showContext(key,x,y,origin=null){
   closeContext(false);contextKey=key;contextOrigin=origin||doc.activeElement;contextOrigin?.setAttribute?.('aria-expanded','true');contextDialog=origin?.closest('dialog')||(folderDialog.open?folderDialog:null);(contextDialog||doc.body).append(context);
   const folder=layout.items.find(row=>row.id===key),item=key?entry(key):null,inMenu=!!origin?.closest('.desktop-menu-entry'),present=key&&has(layout.items,key),canManage=!!item?.app&&(user.role==='admin'||user.permissions?.apps?.allowed),section=(label,body)=>`<div class="quick-action-group" role="group" aria-label="${label}">${body}</div>`;
   context.setAttribute('aria-label',key?(folder?.name||item.name)+': Schnellaktionen':'Desktop anpassen');
   const header=`<header class="quick-action-heading"><span class="quick-action-avatar" aria-hidden="true">${key?(folder?icon('files'):image(key)):icon('settings')}</span><div><strong>${esc(key?(folder?.name||item.name):'Dein Desktop')}</strong><small>${esc(key?(folder?'Desktop-Ordner':item.app?(item.active?'App ist gestartet':'App ist gestoppt'):'Titan-Werkzeug'):'So, wie du ihn brauchst')}</small></div></header>`;
   if(key){
    const launch=menuButton('open','Öffnen',{glyph:'apps',detail:folder?'Ordner ansehen':item.app?'Weboberfläche in neuem Tab':item.detail});
    const manage=canManage?menuButton('manage','Einstellungen & Details',{glyph:'settings',detail:'Konfiguration, Verbindungen und Protokolle'}):'';
    const lifecycle=canManage&&action?menuButton('app-'+(item.active?'stop':'start'),item.active?'App stoppen':'App starten',{glyph:'power',detail:item.active?'Alle zugehörigen Dienste anhalten':'Gesamtes App-Paket starten',disabled:pendingApps.has(item.app)}):'';
    const placement=folder?menuButton('rename','Ordner umbenennen',{glyph:'files',disabled:readonly})+menuButton('dissolve','Ordner auflösen',{glyph:'apps',detail:'Verknüpfungen bleiben auf dem Desktop',disabled:readonly}):`${!inMenu&&present?`${!layout.items.includes(key)?menuButton('move','Auf Desktop verschieben',{glyph:'apps',disabled:readonly}):''}${layout.items.filter(row=>typeof row==='object'&&row.id!==opened).map(row=>menuButton('into','In Ordner: '+row.name,{glyph:'files',disabled:readonly,extra:`data-folder-target="${esc(row.id)}"`})).join('')}`:''}${menuButton(present?'remove':'pin',present?'Vom Desktop entfernen':'Zum Desktop hinzufügen',{glyph:present?'trash':'plus',detail:present?'Nur die Verknüpfung entfernen':'Als eigene Verknüpfung ablegen',disabled:readonly})}`;
    const uninstall=canManage&&action&&confirm?section('App entfernen',menuButton('app-remove','App deinstallieren …',{glyph:'trash',detail:'Mit Bestätigung · gespeicherte Daten bleiben',disabled:pendingApps.has(item.app),extra:'class="danger"'})):'';
    context.innerHTML=header+section('Öffnen und verwalten',launch+manage+lifecycle)+section('Desktop',placement)+uninstall;
   }else{
    const widgets=menuButton('widgets','Widgets hinzufügen',{glyph:'resources',detail:user.role==='admin'?'CPU, Arbeitsspeicher, Uhr und mehr':'Uhr und Datum auf deinem Desktop'});
    const shortcuts=menuButton('add','App-Verknüpfung hinzufügen',{glyph:'apps',detail:'Anwendungen aus dem Hauptmenü auswählen'});
    const folder=menuButton('folder','Neuer Ordner',{glyph:'files',detail:'Deine Verknüpfungen gemeinsam ordnen',disabled:readonly});
    const appearance=menuButton('appearance','Darstellung & Desktop',{glyph:'settings',detail:'Design, Transparenz und Desktop-Verhalten'});
    const sizes=`<div class="quick-icon-sizes" role="group" aria-label="Symbolgröße"><span>Symbolgröße</span>${['small','medium','large'].map((size,index)=>`<button type="button" role="menuitemradio" aria-checked="${layout.icon_size===size}" data-context="size" data-icon-size="${size}" ${readonly?'disabled':''}>${['Klein','Mittel','Groß'][index]}</button>`).join('')}</div>`;
    context.innerHTML=header+section('Hinzufügen',widgets+shortcuts+folder)+section('Personalisieren',appearance+sizes);
   }
   contextAnchor={x,y};context.hidden=false;positionContext();context.querySelector('button:not(:disabled)')?.focus({preventScroll:true});win.requestAnimationFrame?.(()=>positionContext());
  }
  async function click(event){
   const button=event.target.closest('button');if(!button||button.disabled||context.contains(button)&&event.currentTarget!==context)return;const key=button.dataset.shortcutOpen;
   if(key){openItem(key);return;}if(button.dataset.shortcutMore){const r=button.getBoundingClientRect();showContext(button.dataset.shortcutMore,r.left,r.bottom,button);return;}
   if(button.hasAttribute('data-desktop-customize')){const r=button.getBoundingClientRect();showContext(null,r.left,r.top,button);return;}if(button.hasAttribute('data-desktop-retry'))void persist();if(button.hasAttribute('data-folder-close'))folderDialog.close();
   const cmd=button.dataset.context;if(!cmd)return;const selected=contextKey,dialog=contextDialog;closeContext();
   if(cmd==='size'){if(readonly)return;layout.icon_size=button.dataset.iconSize;change();return;}
   if(cmd.startsWith('app-')){dialog?.close();await appCommand(selected,cmd.slice(4));return;}
   if(cmd==='widgets'){dialog?.close();dispatch('titan-widgets-picker',{trigger:contextOrigin});return;}if(cmd==='appearance'){dialog?.close();dispatch('titan-desktop-preferences',{trigger:contextOrigin});return;}if(cmd==='add'){dialog?.close();menu();return;}
   if(cmd==='open'||cmd==='rename'){dialog?.close();openItem(selected);if(cmd==='rename')folderDialog.querySelector('input')?.focus();return;}
   if(cmd==='manage'){dialog?.close();open('#docker?app='+encodeURIComponent(entry(selected).app));return;}
   if(readonly)return;
   if(cmd==='pin')add(selected);if(cmd==='remove')erase(selected);
   if(cmd==='into'){layout.items=group(layout.items,selected,button.dataset.folderTarget);delete layout.positions[selected];change();}
   if(cmd==='move'){layout.items=remove(layout.items,selected);layout.items.push(selected);change();}
   if(cmd==='folder'){const folder={id:'folder-'+Date.now().toString(36),name:'Neuer Ordner',items:[]};layout.items.push(folder);opened=folder.id;change();folderDialog.showModal();}
   if(cmd==='dissolve'){const folder=layout.items.find(row=>row.id===selected);layout.items=layout.items.flatMap(row=>row===folder?folder.items:[row]);delete layout.positions[selected];change();}
  }
  async function appCommand(key,command){const item=entry(key);if(!item.app||pendingApps.has(item.app)||!action)return;if(command==='remove'&&!await confirm('Diese App stoppen und deinstallieren? Konfiguration und Nutzdaten bleiben erhalten.'))return;if(folderDialog.open)folderDialog.close();pendingApps.set(item.app,true);render();toast(command==='remove'?'App wird deinstalliert …':command==='stop'?'App wird gestoppt …':'App wird gestartet …');try{await action('app_action',{app:item.app,action:command},{wait:true,signal:actionController.signal});if(!alive)return;if(command==='remove')erase(key);updateApps(await api('/api/apps'));render();toast(command==='remove'?'App deinstalliert. Deine Daten bleiben erhalten.':command==='stop'?'App gestoppt.':'App gestartet.');}catch(error){if(alive&&error.name!=='AbortError')toast(error.message,true);}finally{pendingApps.delete(item.app);if(alive)render();}}
  function targetOf(target){
   const control=target.closest('button,a,input,select,textarea,[contenteditable],[role="button"]'),launch=target.closest('[data-menu-launch]');
   if(launch&&entries.has(launch.dataset.menuLaunch)&&launch.closest('.desktop-menu-entry')&&(!control||control===launch))return {key:launch.dataset.menuLaunch,node:launch,origin:launch,canDrag:false};
   const node=target.closest('[data-shortcut]');if(!node||!surface.contains(node)&&!folderDialog.contains(node))return null;
   const origin=node.querySelector('[data-shortcut-open]');if(control&&control!==origin)return null;
   return {key:node.dataset.shortcut,node,origin,canDrag:surface.contains(node)&&!readonly};
  }
  function backgroundOf(target){return target===surface||target===surface.parentElement||target===doc.querySelector('.desktop-window-layer')||target.matches?.('.desktop-watermark');}
  function suppress(key){blockClick=Date.now()+800;suppressed={key,until:blockClick};}
  function blockActivation(event){if(!suppressed||Date.now()>=suppressed.until)return;const target=targetOf(event.target);if(suppressed.key===null?!backgroundOf(event.target):target?.key!==suppressed.key)return;event.preventDefault();event.stopImmediatePropagation();}
  function contextmenu(event){
   if(context.contains(event.target))return;const target=targetOf(event.target);
   if(target){event.preventDefault();showContext(target.key,event.clientX,event.clientY,target.origin);return;}
   if(backgroundOf(event.target)&&!event.target.closest('button,a,input,select,textarea,[contenteditable]')){event.preventDefault();showContext(null,event.clientX,event.clientY,surface);}
  }
  function outside(event){if(!context.hidden&&!context.contains(event.target)&&!event.target.closest('[data-shortcut-more]'))closeContext(false);}
  function menuContextClick(event){const trigger=event.target.closest('[data-menu-context]');if(!trigger||trigger.disabled||!entries.has(trigger.dataset.menuContext))return;event.preventDefault();const r=trigger.getBoundingClientRect();showContext(trigger.dataset.menuContext,r.left,r.bottom,trigger);}
  function clearHold(g){if(g?.timer!==undefined){(win.clearTimeout||clearTimeout)(g.timer);delete g.timer;}}
  function down(event){
   if(event.defaultPrevented||event.button!==0||event.isPrimary===false||gesture)return;const target=targetOf(event.target)||(backgroundOf(event.target)?{key:null,node:surface,origin:surface,canDrag:false}:null);if(!target)return;
   const g=gesture={...target,x:event.clientX,y:event.clientY,id:event.pointerId,dragging:false,held:false,group:null,groupAt:0};
   if(event.pointerType==='touch'||event.pointerType==='pen')g.timer=(win.setTimeout||setTimeout)(()=>{
    if(!alive||gesture!==g||g.dragging)return;g.held=true;delete g.timer;suppress(g.key);showContext(g.key,g.x,g.y,g.origin);
   },550);
  }
  function move(event){if(!gesture||gesture.id!==event.pointerId)return;const g=gesture;if(g.held){event.preventDefault();return;}if(!g.dragging&&Math.hypot(event.clientX-g.x,event.clientY-g.y)<9)return;clearHold(g);if(!g.canDrag){gesture=null;return;}event.preventDefault();if(!g.dragging){closeContext(false);g.dragging=true;g.preview=doc.createElement('div');g.preview.className='desktop-drop-preview';g.preview.setAttribute('aria-hidden','true');surface.append(g.preview);g.node.classList.add('shortcut-dragging');surface.setPointerCapture?.(event.pointerId);}
   g.node.style.transform=`translate3d(${event.clientX-g.x}px,${event.clientY-g.y}px,0)`;const area=surface.getBoundingClientRect(),cols=Math.max(1,Math.floor(surface.clientWidth/cell())),rows=Math.max(1,Math.floor(surface.clientHeight/cell()));g.preview.style.left=Math.max(0,Math.min(cols-1,Math.floor((event.clientX-area.left+surface.scrollLeft)/cell())))*cell()+'px';g.preview.style.top=Math.max(0,Math.min(rows-1,Math.floor((event.clientY-area.top+surface.scrollTop)/cell())))*cell()+'px';
   g.node.style.pointerEvents='none';const target=doc.elementFromPoint(event.clientX,event.clientY)?.closest('[data-shortcut]');g.node.style.pointerEvents='';let groupKey=null;if(target&&target!==g.node&&validKey(g.key)){const r=target.getBoundingClientRect();if(event.clientX>r.left+r.width*.2&&event.clientX<r.right-r.width*.2&&event.clientY>r.top+8&&event.clientY<r.bottom-15)groupKey=target.dataset.shortcut;}
   if(g.group!==groupKey){surface.querySelectorAll('.shortcut-group-target').forEach(n=>n.classList.remove('shortcut-group-target'));g.group=groupKey;g.groupAt=Date.now();}
   if(groupKey&&Date.now()-g.groupAt>=500)target.classList.add('shortcut-group-target');}
  function end(event){if(!gesture||gesture.id!==event.pointerId)return;const g=gesture;gesture=null;clearHold(g);g.preview?.remove();if(surface.hasPointerCapture?.(event.pointerId))surface.releasePointerCapture?.(event.pointerId);if(g.held){suppress(g.key);return;}if(!g.dragging)return;suppress(g.key);if(event.type==='pointercancel'){render();return;}if(g.group&&Date.now()-g.groupAt>=500){const next=group(layout.items,g.key,g.group);const old=displayed[g.group];layout.items=next;const folder=next.find(row=>typeof row==='object'&&row.items.includes(g.key));if(folder&&old)layout.positions[folder.id]=old;delete layout.positions[g.key];}else{const r=surface.getBoundingClientRect(),cols=Math.max(1,Math.floor(surface.clientWidth/cell())),rows=Math.max(1,Math.floor(surface.clientHeight/cell()));const target={x:Math.max(0,Math.min(cols-1,Math.floor((event.clientX-r.left+surface.scrollLeft)/cell()))),y:Math.max(0,Math.min(rows-1,Math.floor((event.clientY-r.top+surface.scrollTop)/cell())))};const other=Object.keys(displayed).find(key=>key!==g.key&&displayed[key].x===target.x&&displayed[key].y===target.y);if(other)layout.positions[other]=displayed[g.key];layout.positions[g.key]=target;}change();}
  function keydown(event){
   if(!context.hidden&&event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();closeContext();return;}
   if(!context.hidden&&context.contains(event.target)){
    const buttons=[...context.querySelectorAll('button:not(:disabled)')],index=buttons.indexOf(doc.activeElement);
    if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();event.stopImmediatePropagation();buttons[event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();return;}
    if(event.key==='Escape'||event.key==='Tab'){event.preventDefault();event.stopImmediatePropagation();closeContext();return;}
   }
   if(event.key==='Escape'&&gesture){event.preventDefault();event.stopImmediatePropagation();cancelGesture();return;}
   const target=targetOf(event.target)||(backgroundOf(event.target)?{key:null,node:surface,origin:surface,canDrag:false}:null);if(!target)return;
   if(event.key==='ContextMenu'||event.shiftKey&&event.key==='F10'){event.preventDefault();const r=target.node.getBoundingClientRect();showContext(target.key,r.left,r.bottom,target.origin);return;}
   if(!surface.contains(target.node)&&!folderDialog.contains(target.node))return;
   if(event.key==='Delete'&&target.key){event.preventDefault();erase(target.key);}
   if(event.altKey&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)&&target.canDrag){event.preventDefault();const key=target.key,p=displayed[key],cols=Math.max(1,Math.floor(surface.clientWidth/cell())),rows=Math.max(1,Math.floor(surface.clientHeight/cell()));layout.positions[key]={x:Math.max(0,Math.min(cols-1,p.x+(event.key==='ArrowRight'?1:event.key==='ArrowLeft'?-1:0))),y:Math.max(0,Math.min(rows-1,p.y+(event.key==='ArrowDown'?1:event.key==='ArrowUp'?-1:0)))};change();surface.querySelector(`[data-shortcut-open="${key}"]`)?.focus();}
  }
  function submit(event){if(!event.target.matches('[data-folder-name]'))return;event.preventDefault();if(readonly)return;const name=event.target.elements.name.value.trim();if(!name)return;layout.items.find(row=>row.id===opened).name=name;change();}
  const preventDrag=event=>event.preventDefault();
  const cancelGesture=()=>{if(!gesture)return;clearHold(gesture);gesture.preview?.remove();if(surface.hasPointerCapture?.(gesture.id))surface.releasePointerCapture?.(gesture.id);if(gesture.dragging||gesture.held)suppress(gesture.key);gesture=null;render();};
  const listeners=[[surface,'dragstart',preventDrag],[surface,'click',click],[folderDialog,'click',click],[context,'click',click],[doc,'click',menuContextClick],[folderDialog,'submit',submit],[doc,'contextmenu',contextmenu],[doc,'pointerdown',outside],[doc,'pointerdown',down],[doc,'pointermove',move],[doc,'pointerup',end],[doc,'pointercancel',end],[doc,'keydown',keydown,true],[doc,'titan-widget-layout',position],[win,'click',blockActivation,true],[win,'blur',cancelGesture],[doc,'visibilitychange',cancelGesture]];
  listeners.forEach(([node,event,fn,capture])=>node.addEventListener?.(event,fn,capture));folderDialog.addEventListener('close',()=>{opened=null;closeContext(false);doc.body.append(context);});const observer=new win.ResizeObserver(()=>{position();positionContext();});observer.observe(surface);observer.observe(context);render();void refreshApps();void refreshVMs();
  const liveTimer=setInterval(()=>{if(alive&&!gesture&&!doc.hidden&&context.hidden&&!pendingApps.size)void refreshApps();},15000);
  async function refreshApps(){if(appsBusy||user.role!=='admin'&&!user.permissions?.apps?.allowed)return;appsBusy=true;try{const result=await api('/api/apps');if(alive){appsLoading=false;updateApps(result);if(!gesture&&!folderDialog.open&&context.hidden)render();}}catch{appsLoading=false;if(alive&&!gesture&&!folderDialog.open&&context.hidden)render();}finally{appsBusy=false;}}
  return {desktop:()=>({...layout.desktop}),desktopWritable:()=>!readonly,setDesktop:value=>{if(readonly||!alive)return false;layout.desktop=desktopPreferences({...layout.desktop,...value});revision++;void persist();return true;},showDesktopMenu:trigger=>{const r=(trigger||surface).getBoundingClientRect();showContext(null,r.left+16,r.top+16,trigger||surface);},backgroundClickAllowed:()=>!gesture&&Date.now()>=blockClick,add,contains:key=>has(layout.items,key),entries:()=>[...entries.entries()],open:openItem,refreshApps,refreshVMs,widgets:()=>layout.widgets,setWidgets:value=>{if(readonly||!alive)return false;layout.widgets=value;change();return true;},destroy(){alive=false;actionController.abort();clearInterval(liveTimer);clearHold(gesture);gesture?.preview?.remove();observer.disconnect();listeners.forEach(([node,event,fn,capture])=>node.removeEventListener?.(event,fn,capture));context.remove();folderDialog.remove();content.remove();}};
 }
 return {normalize,place,remove,group,safeUrl,mount};
});
