'use strict';
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanWidgets=ui;})(typeof window==='undefined'?null:window,function(){
 const names={cpu:'CPU',ram:'Arbeitsspeicher',health:'Systemstatus',notifications:'Benachrichtigungen',activity:'Aktivität',clock:'Uhr'};
 const descriptions={cpu:'Die aktuelle Auslastung deines Prozessors.',ram:'Belegter und verfügbarer Arbeitsspeicher.',health:'Verbindung und Zustand deiner NAS-Dienste.',notifications:'Offene Meldungen und Fehler auf einen Blick.',activity:'Laufende und wartende Aufträge.',clock:'Uhrzeit und Datum in deiner lokalen Zeitzone.'};
 const symbols={cpu:'▦',ram:'▥',health:'♡',notifications:'♧',activity:'☷',clock:'◷'};
 const validPosition=p=>p&&['x','y'].every(k=>Number.isInteger(p[k])&&p[k]>=0&&p[k]<=1000);
 function normalize(value={}){
  const out={visible:value.visible!==false,collapsed:value.collapsed===true,items:[...new Set(Array.isArray(value.items)?value.items:['cpu','ram','health'])].filter(k=>Object.hasOwn(names,k))};
  if(validPosition(value.position))out.position={x:value.position.x,y:value.position.y};
  const positions={};for(const key of out.items)if(validPosition(value.positions?.[key]))positions[key]={x:value.positions[key].x,y:value.positions[key].y};
  if(Object.keys(positions).length)out.positions=positions;return out;
 }
 const clamp=(value,max)=>Math.max(0,Math.min(Math.max(0,max),value));
 function placement(position,area,width,height){return {left:area.left+Math.max(0,area.width-width)*(position?.x??1000)/1000,top:area.top+Math.max(0,area.height-height)*(position?.y??0)/1000};}
 function coordinates(left,top,area,width,height){const dx=Math.max(0,area.width-width),dy=Math.max(0,area.height-height);return {x:dx?Math.round(clamp(left-area.left,dx)/dx*1000):0,y:dy?Math.round(clamp(top-area.top,dy)/dy*1000):0};}
 function metrics(status={}){const total=status.memory_total,used=status.memory_occupied??status.memory_used;return {cpu:typeof status.cpu_percent==='number'&&status.cpu_percent>=0&&status.cpu_percent<=100?status.cpu_percent:null,ram:Number.isFinite(total)&&total>0&&Number.isFinite(used)&&used>=0&&used<=total?used/total*100:null};}
 function health(status){if(!status)return 'Wird geladen';const services=Object.values(status.service_details||{}).filter(s=>s.relevant===true||s.relevant===undefined&&s.installed);if(services.some(s=>!s.active))return 'Dienste prüfen';if(Object.keys(status.telemetry_errors||{}).length)return 'Messhinweise vorhanden';return 'Verbunden';}
 function mount({doc,user,api,esc,bytes,preferences,save,open,jobs}){
  const win=doc.defaultView,toggle=doc.querySelector('#widgets-toggle'),admin=user.role==='admin',choices=Object.keys(names).filter(key=>admin||key==='clock');
  let prefs=normalize(!admin&&!Array.isArray(preferences?.items)?{...preferences,items:['clock']}:preferences),alive=true,busy=false,status=null,error=false,alerts=null,activity=[],gesture=null,pickerOrigin=null;
  const hadItems=prefs.items.length>0;prefs.items=prefs.items.filter(key=>choices.includes(key));if(!admin&&hadItems&&!prefs.items.length)prefs.items=['clock'];if(prefs.positions)for(const key of Object.keys(prefs.positions))if(!prefs.items.includes(key))delete prefs.positions[key];
  const cards=new Map(),config=doc.createElement('dialog');config.className='widget-settings widget-gallery';config.setAttribute('aria-label','Widgets hinzufügen');doc.body.append(config);
  if(toggle){toggle.hidden=false;toggle.setAttribute('aria-label','Widgets hinzufügen');toggle.setAttribute('title','Widgets hinzufügen');toggle.setAttribute('aria-haspopup','dialog');toggle.setAttribute('aria-expanded','false');toggle.removeAttribute('aria-pressed');}
  function area(){const rect=doc.querySelector('#desktop-surface')?.getBoundingClientRect();return rect&&rect.width>0&&rect.height>0?{left:rect.left+8,top:rect.top+8,width:Math.max(0,rect.width-16),height:Math.max(0,rect.height-16)}:{left:8,top:70,width:Math.max(0,win.innerWidth-16),height:Math.max(0,win.innerHeight-126)};}
  function point(key,node,index){const available=area(),rect=node.getBoundingClientRect();if(prefs.positions?.[key])return placement(prefs.positions[key],available,rect.width,rect.height);if(index===0&&prefs.position)return placement(prefs.position,available,rect.width,rect.height);const gap=14,start=clamp(190-available.top,available.height-rect.height),rows=Math.max(1,Math.floor((available.height-start+gap)/(rect.height+gap))),columns=Math.max(1,Math.floor((available.width+gap)/(rect.width+gap))),column=Math.floor(index/rows)%columns,row=index%rows;return {left:available.left+Math.max(0,available.width-rect.width-column*(rect.width+gap)),top:available.top+Math.max(0,Math.min(available.height-rect.height,start+row*(rect.height+gap)))};}
  function positionCards(){if(!alive)return;let index=0;for(const [key,node]of cards){const available=area();node.style.maxHeight=Math.max(90,available.height)+'px';const p=point(key,node,index++);node.style.left=p.left+'px';node.style.top=p.top+'px';node.style.right='auto';node.style.bottom='auto';}}
  function values(key){
   if(key==='clock'){const now=new Date();return {value:new Intl.DateTimeFormat('de-DE',{hour:'2-digit',minute:'2-digit'}).format(now),caption:new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'numeric',month:'long'}).format(now)};}
   if(key==='cpu'||key==='ram'){const value=metrics(status||{})[key];return {value:error||value===null?'—':value.toLocaleString('de-DE',{maximumFractionDigits:1})+' %',progress:!error&&value!==null?value:0,caption:error?'Messwert nicht verfügbar':key==='ram'&&status?bytes(status.memory_occupied??status.memory_used)+' / '+bytes(status.memory_total):value===null?'Messwert wird geladen':'Prozessorauslastung'};}
   if(key==='health')return {value:error?'Verbindung unterbrochen':health(status),caption:'Systemübersicht öffnen'};
   if(key==='notifications'){const list=Array.isArray(alerts)?alerts:alerts?.alerts||[],unread=list.filter(a=>a.active!==false&&!a.acknowledged),severe=unread.filter(a=>['error','critical'].includes(a.severity));return {value:alerts===null?'—':unread.length,caption:alerts===null?'Meldungen werden geladen':severe.length?severe.length+' Fehler · Meldungen ansehen':'Offene Meldungen'};}
   return {value:activity.filter(j=>['running','queued'].includes(j.status)).length,caption:'Laufende Aufträge ansehen'};
  }
  function content(key){
   const item=values(key),body=`<strong data-widget-value>${esc(item.value)}</strong>${item.progress!==undefined?`<progress max="100" value="${item.progress}" aria-label="${names[key]}"></progress>`:''}<small data-widget-caption>${esc(item.caption)}</small>`;
   if(key==='clock')return `<div class="widget-clock">${body.replace('<small data-widget-caption>','<span data-widget-caption>').replace('</small>','</span>')}</div>`;
   return `<button type="button" ${key==='activity'?'data-widget-jobs':`data-widget-open="${key==='cpu'||key==='ram'?'resources':'monitoring'}"`} class="${key==='cpu'||key==='ram'?'widget-metric':''}">${body}</button>`;
  }
  function render(){
   if(!alive)return;if(gesture){positionCards();return;}
   // Reconcile the selected cards once. Polling changes text/progress only:
   // pointer targets, keyboard focus and the card's entrance animation persist.
   for(const [key,node]of cards)if(!prefs.visible||!prefs.items.includes(key)){node.remove();cards.delete(key);}
   if(prefs.visible)for(const key of prefs.items){
    let node=cards.get(key);
    if(!node){node=doc.createElement('aside');node.className='desktop-widget desktop-widget-card';node.dataset.widgetCard=key;node.setAttribute('data-widget-card',key);node.setAttribute('aria-label',names[key]+' Widget');node.innerHTML=`<header><button type="button" class="widget-move-handle" data-widget-move="${key}" aria-label="${names[key]} verschieben. Pfeiltasten bewegen, Umschalt bewegt in kleinen Schritten." title="Widget verschieben · auch mit Pfeiltasten"><span aria-hidden="true">⠿</span></button><strong>${names[key]}</strong><button type="button" class="widget-remove" data-widget-remove="${key}" aria-label="${names[key]} vom Desktop entfernen" title="Widget entfernen">×</button></header><div class="widget-content"></div>`;doc.body.append(node);cards.set(key,node);}
    const body=node.querySelector('.widget-content');
    if(node.dataset.widgetCollapsed!==String(prefs.collapsed)){body.innerHTML=prefs.collapsed?`<button type="button" class="widget-expand" data-widget-expand="${key}">Widget anzeigen</button>`:content(key);node.dataset.widgetCollapsed=String(prefs.collapsed);}
    if(!prefs.collapsed){const item=values(key);body.querySelector('[data-widget-value]').textContent=String(item.value);body.querySelector('[data-widget-caption]').textContent=String(item.caption);const progress=body.querySelector('progress');if(progress)progress.value=item.progress;}
   }
   positionCards();
  }
  function renderGallery(focusKey=null){
   const count=prefs.items.length;config.innerHTML=`<header class="widget-gallery-heading"><div><span class="widget-gallery-kicker">Dein Desktop</span><h2>Widgets hinzufügen</h2><p>Wähle aus, was du auf deinem Desktop sehen möchtest. Jede Karte lässt sich einzeln verschieben.</p></div><button type="button" class="widget-gallery-close" data-widget-picker-close aria-label="Widget-Auswahl schließen">×</button></header><p class="widget-gallery-state" role="status">${count?count+' Widget'+(count===1?'':'s')+(prefs.visible?' auf deinem Desktop':' ausgewählt · ausgeblendet'):'Noch keine Widgets auf dem Desktop'}</p><div class="widget-gallery-grid">${choices.map(key=>{const selected=prefs.items.includes(key),visible=selected&&prefs.visible;return `<article class="widget-choice" data-widget-choice="${key}" data-selected="${selected}"><div class="widget-choice-preview" aria-hidden="true"><span>${symbols[key]}</span><i></i><i></i></div><h3>${names[key]}</h3><p>${descriptions[key]}</p><span class="widget-choice-state">${selected?(visible?'Auf dem Desktop':'Ausgeblendet'):'Zum Desktop hinzufügen'}</span><div class="widget-choice-actions"><button type="button" class="button ${visible?'':'primary'}" data-widget-${visible?'remove':'add'}="${key}">${visible?'Entfernen':selected?'Anzeigen':'+ Hinzufügen'}</button>${selected&&!visible?`<button type="button" class="button" data-widget-remove="${key}">Entfernen</button>`:''}</div></article>`;}).join('')}</div><footer><button type="button" class="button primary" data-widget-picker-close>Fertig</button>${count&&prefs.visible?'<button type="button" class="button" data-widget-hide>Alle ausblenden</button>':''}</footer>`;
   if(focusKey)config.querySelector(`[data-widget-choice="${focusKey}"]`)?.querySelector('button')?.focus({preventScroll:true});
  }
  function commit(next,focusKey=null){const previous=prefs;prefs=normalize(next);if(save({...prefs,items:[...prefs.items],...(prefs.positions?{positions:JSON.parse(JSON.stringify(prefs.positions))}:{})})===false){prefs=previous;return false;}render();if(config.open)renderGallery(focusKey);void refresh();return true;}
  function openPicker(trigger=null){if(!alive)return false;pickerOrigin=trigger||doc.activeElement||toggle;renderGallery();if(!config.open)config.showModal();toggle?.setAttribute('aria-expanded','true');config.querySelector('[data-widget-add],[data-widget-remove],button')?.focus();return true;}
  function closePicker(){config.close();}
  function click(event){
   const b=event.target.closest('button');if(!b||b.disabled)return;const card=b.closest('[data-widget-card]');if(!config.contains(b)&&(!card||cards.get(card.dataset.widgetCard)!==card))return;
   if(b.hasAttribute('data-widget-picker-close')){closePicker();return;}
   if(b.hasAttribute('data-widget-hide')){commit({...prefs,visible:false});closePicker();return;}
   if(b.dataset.widgetAdd){const key=b.dataset.widgetAdd;if(!choices.includes(key))return;commit({...prefs,items:[...new Set([...prefs.items,key])],visible:true,collapsed:false},key);return;}
   if(b.dataset.widgetRemove){const key=b.dataset.widgetRemove;if(!choices.includes(key))return;const items=prefs.items.filter(item=>item!==key),positions={...prefs.positions};delete positions[key];commit({...prefs,items,positions,visible:items.length?prefs.visible:false},key);if(!config.open)(cards.values().next().value?.querySelector('[data-widget-move]')||toggle)?.focus({preventScroll:true});return;}
   if(b.hasAttribute('data-widget-expand')){commit({...prefs,collapsed:false});return;}
   if(b.dataset.widgetOpen)open('#'+b.dataset.widgetOpen);if(b.hasAttribute('data-widget-jobs'))jobs();
  }
  async function refresh(){if(!alive||busy||doc.hidden||!prefs.visible||prefs.collapsed||!admin||!prefs.items.some(key=>key!=='clock'))return;busy=true;try{const data=await api('/api/status');if(alive){status=data;error=false;render();}}catch{if(alive){error=true;render();}}finally{busy=false;}}
  function down(e){const handle=e.target.closest('[data-widget-move]');if(!handle||e.button!==0||e.isPrimary===false||gesture)return;const key=handle.dataset.widgetMove,node=cards.get(key);if(!node)return;e.preventDefault();handle.focus();const rect=node.getBoundingClientRect();gesture={id:e.pointerId,key,node,handle,x:e.clientX,y:e.clientY,left:rect.left,top:rect.top,before:prefs.positions?.[key]?{...prefs.positions[key]}:null};node.classList.add('widget-moving');handle.setPointerCapture?.(e.pointerId);}
  function move(e){if(!gesture||e.pointerId!==gesture.id)return;e.preventDefault();const g=gesture,rect=g.node.getBoundingClientRect();prefs.positions={...prefs.positions,[g.key]:coordinates(g.left+e.clientX-g.x,g.top+e.clientY-g.y,area(),rect.width,rect.height)};positionCards();}
  function end(e){if(!gesture||e&&e.pointerId!==gesture.id)return;const g=gesture;gesture=null;if(g.handle.hasPointerCapture?.(g.id))g.handle.releasePointerCapture?.(g.id);const next=normalize(prefs);prefs.positions={...prefs.positions};if(g.before)prefs.positions[g.key]=g.before;else delete prefs.positions[g.key];if(e?.type==='pointercancel'||!commit(next))render();cards.get(g.key)?.querySelector('[data-widget-move]')?.focus({preventScroll:true});}
  function keydown(e){if(gesture&&e.key==='Escape'){e.preventDefault();end({pointerId:gesture.id,type:'pointercancel'});return;}const handle=e.target.closest('[data-widget-move]');if(!handle||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;const key=handle.dataset.widgetMove,node=cards.get(key);if(!node)return;e.preventDefault();const rect=node.getBoundingClientRect(),step=e.shiftKey?4:24;commit({...prefs,positions:{...prefs.positions,[key]:coordinates(rect.left+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0),rect.top+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0),area(),rect.width,rect.height)}});cards.get(key)?.querySelector('[data-widget-move]')?.focus({preventScroll:true});}
  const delegate=e=>{const trigger=e.target.closest('[data-widgets-picker]');if(trigger){e.preventDefault();openPicker(trigger);}},pickerEvent=e=>openPicker(e.detail?.trigger),toggleClick=()=>openPicker(toggle),blur=()=>{if(gesture)end({pointerId:gesture.id,type:'pointercancel'});},onClose=()=>{toggle?.setAttribute('aria-expanded','false');const hiddenDialog=pickerOrigin?.closest('dialog');(pickerOrigin?.isConnected&&(!hiddenDialog||hiddenDialog.open)?pickerOrigin:toggle)?.focus?.({preventScroll:true});};
  const listeners=[[doc,'click',delegate],[doc,'click',click],[doc,'pointerdown',down],[doc,'keydown',keydown],[doc,'pointermove',move],[doc,'pointerup',end],[doc,'pointercancel',end],[doc,'visibilitychange',refresh],[doc,'titan-widgets-picker',pickerEvent],[win,'resize',positionCards],[win,'blur',blur],[config,'close',onClose],...(toggle?[[toggle,'click',toggleClick]]:[])];
  listeners.forEach(([node,event,fn])=>node.addEventListener(event,fn));const timer=win.setInterval(()=>{void refresh();if(prefs.items.includes('clock')&&!gesture)render();},10000);render();void refresh();
  return {openPicker,updateJobs(value){if(admin){activity=value;render();}},updateAlerts(value){if(admin){alerts=value;render();}},destroy(){alive=false;gesture=null;win.clearInterval(timer);listeners.forEach(([node,event,fn])=>node.removeEventListener(event,fn));for(const node of cards.values())node.remove();cards.clear();config.remove();}};
 }
 return {normalize,placement,coordinates,metrics,health,mount};
});
