'use strict';
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanWidgets=ui;})(typeof window==='undefined'?null:window,function(){
 const names={cpu:'CPU',ram:'Arbeitsspeicher',health:'Systemstatus',notifications:'Benachrichtigungen',activity:'Aktivität'};
 function normalize(value={}){const out={visible:value.visible!==false,collapsed:value.collapsed===true,items:[...new Set(Array.isArray(value.items)?value.items:['cpu','ram','health'])].filter(k=>Object.hasOwn(names,k))};if(value.position&&['x','y'].every(k=>Number.isInteger(value.position[k])&&value.position[k]>=0&&value.position[k]<=1000))out.position={x:value.position.x,y:value.position.y};return out;}
 const clamp=(value,max)=>Math.max(0,Math.min(Math.max(0,max),value));
 function placement(position,area,width,height){return {left:area.left+Math.max(0,area.width-width)*(position?.x??1000)/1000,top:area.top+Math.max(0,area.height-height)*(position?.y??0)/1000};}
 function coordinates(left,top,area,width,height){const dx=Math.max(0,area.width-width),dy=Math.max(0,area.height-height);return {x:dx?Math.round(clamp(left-area.left,dx)/dx*1000):0,y:dy?Math.round(clamp(top-area.top,dy)/dy*1000):0};}
 function metrics(status={}){const total=status.memory_total,used=status.memory_occupied??status.memory_used;return {cpu:typeof status.cpu_percent==='number'&&status.cpu_percent>=0&&status.cpu_percent<=100?status.cpu_percent:null,ram:Number.isFinite(total)&&total>0&&Number.isFinite(used)&&used>=0&&used<=total?used/total*100:null};}
 function health(status){if(!status)return 'Wird geladen';const services=Object.values(status.service_details||{}).filter(s=>s.relevant===true||s.relevant===undefined&&s.installed);if(services.some(s=>!s.active))return 'Dienste prüfen';if(Object.keys(status.telemetry_errors||{}).length)return 'Messhinweise vorhanden';return 'Verbunden';}
 function mount({doc,user,api,esc,bytes,preferences,save,open,jobs}){
  const toggle=doc.querySelector('#widgets-toggle');if(user.role!=='admin'){toggle.hidden=true;return {destroy(){}};}toggle.hidden=false;
  const win=doc.defaultView,box=doc.createElement('aside'),config=doc.createElement('dialog');box.className='desktop-widget';box.setAttribute('aria-label','Statuswidget');config.className='widget-settings';doc.body.append(box);doc.body.append(config);
  let prefs=normalize(preferences),alive=true,busy=false,status=null,error=false,alerts=null,activity=[],gesture=null;
  function area(){const rect=doc.querySelector('#desktop-surface')?.getBoundingClientRect();return rect&&rect.width>0&&rect.height>0?{left:rect.left+8,top:rect.top+8,width:Math.max(0,rect.width-16),height:Math.max(0,rect.height-16)}:{left:8,top:70,width:Math.max(0,win.innerWidth-16),height:Math.max(0,win.innerHeight-126)};}
  function positionBox(){if(!alive||box.hidden)return;const available=area();box.style.maxHeight=Math.max(64,available.height)+'px';const rect=box.getBoundingClientRect(),point=placement(prefs.position,available,rect.width,rect.height);box.style.left=point.left+'px';box.style.top=point.top+'px';box.style.right='auto';box.style.bottom='auto';}
  function render(){if(!alive)return;if(gesture){positionBox();return;}const focused=box.contains(doc.activeElement)?[...box.querySelectorAll('button')].indexOf(doc.activeElement):-1;box.hidden=!prefs.visible;toggle.setAttribute('aria-pressed',String(prefs.visible));const values=metrics(status||{});
   box.innerHTML=`<header><button type="button" class="widget-move-handle" data-widget-move aria-label="Statuswidget verschieben. Pfeiltasten bewegen, Umschalt bewegt in kleinen Schritten." title="Widget verschieben · auch mit Pfeiltasten"><span aria-hidden="true">⠿</span></button><button data-widget-collapse aria-expanded="${!prefs.collapsed}">${prefs.collapsed?'▴':'▾'} Status</button><button data-widget-settings aria-label="Widgets auswählen" title="Widgets auswählen">⚙</button></header><div class="widget-content" ${prefs.collapsed?'hidden':''}>${prefs.items.map(key=>{
    if(key==='cpu'||key==='ram'){const value=values[key];return `<button class="widget-metric" data-widget-open="resources"><span>${names[key]}</span><strong>${error?'—':value===null?'—':value.toLocaleString('de-DE',{maximumFractionDigits:1})+' %'}</strong><progress max="100" value="${!error&&value!==null?value:0}" aria-label="${names[key]}"></progress>${key==='ram'&&status&&!error?`<small>${esc(bytes(status.memory_occupied??status.memory_used))} / ${esc(bytes(status.memory_total))}</small>`:''}</button>`;}
    if(key==='health')return `<button data-widget-open="monitoring"><span>Systemstatus</span><strong>${error?'Verbindung unterbrochen':health(status)}</strong></button>`;
    if(key==='notifications'){const list=Array.isArray(alerts)?alerts:alerts?.alerts||[],unread=list.filter(a=>a.active!==false&&!a.acknowledged),severe=unread.filter(a=>['error','critical'].includes(a.severity));return `<button data-widget-open="monitoring"><span>Benachrichtigungen</span><strong>${alerts===null?'Wird geladen':unread.length+' Meldungen'}</strong>${severe.length?`<small>${severe.length} Fehler · Jetzt prüfen</small>`:''}</button>`;}
    return `<button data-widget-jobs><span>Aktivität</span><strong>${activity.filter(j=>['running','queued'].includes(j.status)).length} laufend</strong></button>`;
   }).join('')||'<p>Über ⚙ Widgets auswählen.</p>'}${error?'<p role="status">Messwerte derzeit nicht verfügbar.</p>':''}</div>`;
   positionBox();if(focused>=0)box.querySelectorAll('button')[focused]?.focus();
  }
  async function refresh(){if(!alive||busy||doc.hidden||!prefs.visible||prefs.collapsed)return;busy=true;try{const data=await api('/api/status');if(alive){status=data;error=false;render();}}catch{if(alive){error=true;render();}}finally{busy=false;}}
  function changed(){save({...prefs,items:[...prefs.items],...(prefs.position?{position:{...prefs.position}}:{})});render();void refresh();}
  function click(e){const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-widget-collapse')){prefs.collapsed=!prefs.collapsed;changed();}if(b.dataset.widgetOpen)open('#'+b.dataset.widgetOpen);if(b.hasAttribute('data-widget-jobs'))jobs();if(b.hasAttribute('data-widget-settings')){config.innerHTML=`<form><h2>Widgets auswählen</h2>${Object.entries(names).map(([key,name])=>`<label><input type="checkbox" name="widget" value="${key}" ${prefs.items.includes(key)?'checked':''}>${name}</label>`).join('')}<div><button class="button primary" type="submit">Speichern</button><button class="button" type="button" data-widget-cancel>Abbrechen</button></div></form>`;config.showModal();config.querySelector('input')?.focus();}if(b.hasAttribute('data-widget-cancel'))config.close();}
  function down(e){const handle=e.target.closest('[data-widget-move]');if(!handle||e.button!==0||e.isPrimary===false||gesture)return;e.preventDefault();handle.focus();const rect=box.getBoundingClientRect();gesture={id:e.pointerId,handle,x:e.clientX,y:e.clientY,left:rect.left,top:rect.top,before:prefs.position?{...prefs.position}:undefined};box.classList.add('widget-moving');handle.setPointerCapture?.(e.pointerId);}
  function move(e){if(!gesture||e.pointerId!==gesture.id)return;e.preventDefault();const rect=box.getBoundingClientRect();prefs.position=coordinates(gesture.left+e.clientX-gesture.x,gesture.top+e.clientY-gesture.y,area(),rect.width,rect.height);positionBox();}
  function end(e){if(!gesture||e&&e.pointerId!==gesture.id)return;const g=gesture;gesture=null;if(g.handle.hasPointerCapture?.(g.id))g.handle.releasePointerCapture?.(g.id);box.classList.remove('widget-moving');if(e?.type==='pointercancel'){if(g.before)prefs.position=g.before;else delete prefs.position;render();return;}changed();box.querySelector('[data-widget-move]')?.focus({preventScroll:true});}
  function keydown(e){if(gesture&&e.key==='Escape'){e.preventDefault();end({pointerId:gesture.id,type:'pointercancel'});return;}if(!e.target.closest('[data-widget-move]')||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const rect=box.getBoundingClientRect(),step=e.shiftKey?4:24;prefs.position=coordinates(rect.left+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0),rect.top+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0),area(),rect.width,rect.height);changed();box.querySelector('[data-widget-move]')?.focus({preventScroll:true});}
  const toggleClick=()=>{prefs.visible=!prefs.visible;changed();};const submit=e=>{e.preventDefault();prefs.items=[...config.querySelectorAll('input:checked')].map(n=>n.value);config.close();changed();};
  const blur=()=>{if(gesture)end({pointerId:gesture.id,type:'pointercancel'});};
  const listeners=[[box,'click',click],[box,'pointerdown',down],[box,'keydown',keydown],[config,'click',click],[config,'submit',submit],[toggle,'click',toggleClick],[doc,'pointermove',move],[doc,'pointerup',end],[doc,'pointercancel',end],[doc,'visibilitychange',refresh],[win,'resize',positionBox],[win,'blur',blur]];
  listeners.forEach(([node,event,fn])=>node.addEventListener(event,fn));const observer=win.ResizeObserver?new win.ResizeObserver(positionBox):null;observer?.observe(box);const timer=win.setInterval(refresh,10000);render();void refresh();
  return {updateJobs(value){activity=value;render();},updateAlerts(value){alerts=value;render();},destroy(){alive=false;gesture=null;observer?.disconnect();win.clearInterval(timer);listeners.forEach(([node,event,fn])=>node.removeEventListener(event,fn));box.remove();config.remove();}};
 }
 return {normalize,placement,coordinates,metrics,health,mount};
});
