'use strict';
(function(root){let current=null;
 const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function ports(value){return Object.entries(value||{}).map(([target,bindings])=>bindings?.map(b=>`${b.HostIp||'NAS'}:${b.HostPort} → ${target}`).join(' · ')||target+' intern').join(' · ');}
 function parsePorts(text){return String(text).split(/\r?\n/).map(v=>v.trim()).filter(Boolean).map(v=>{const m=v.match(/^(\d{1,5}):(\d{1,5})(?:\/(tcp|udp))?$/);if(!m)throw Error('Ports zeilenweise als 8080:80/tcp eingeben.');return {published:Number(m[1]),target:Number(m[2]),protocol:m[3]||'tcp'};});}
 function parseEnv(text){const result={};for(const row of String(text).split(/\r?\n/).filter(v=>v.trim())){const i=row.indexOf('=');if(i<1||!/^[A-Za-z_][A-Za-z0-9_]{0,63}$/.test(row.slice(0,i)))throw Error('Umgebung zeilenweise als NAME=Wert eingeben.');const key=row.slice(0,i);if(Object.hasOwn(result,key))throw Error('Umgebungsvariable doppelt: '+key);Object.defineProperty(result,key,{value:row.slice(i+1),enumerable:true,writable:true,configurable:true});}return result;}
 const valid=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
 function metric(m,bytes){return `<span>CPU <strong>${valid(m?.cpu_percent)?m.cpu_percent.toLocaleString('de-DE',{maximumFractionDigits:1})+' %':'—'}</strong></span><span>RAM gesamt <strong>${valid(m?.memory_bytes)?safe(bytes(m.memory_bytes)):'—'}</strong></span>`;}
 function dispose(){current?.();current=null;}
 async function mount(container,{api,action,dialog,askYesNo,toast,bytes}){dispose();if(!container)return;let alive=true,busy=false,data={containers:[],images:[],volumes:[],networks:[]},view='containers',query='',sort='az',metrics={},refreshing=false;
  const button=(label,op,id='',kind='')=>`<button type="button" class="button small ${kind}" data-engine-action="${op}" data-engine-id="${safe(id)}">${label}</button>`;
  function render(){if(!alive)return;
   const rows=(data.containers||[]).filter(c=>[c.name,c.image,c.state,...c.networks.map(n=>n.name)].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='az'?a.name.localeCompare(b.name,'de'):sort==='za'?b.name.localeCompare(a.name,'de'):String(b.created).localeCompare(String(a.created)));
   const tabs=[['containers','Container'],['images','Images'],['networks','Netzwerke'],['volumes','Volumes']];
   let content='';
   if(view==='containers')content=`<div class="engine-filter"><input type="search" data-engine-search placeholder="Container suchen" aria-label="Container suchen" value="${safe(query)}"><select data-engine-sort aria-label="Container sortieren"><option value="az" ${sort==='az'?'selected':''}>Name A–Z</option><option value="za" ${sort==='za'?'selected':''}>Name Z–A</option><option value="new" ${sort==='new'?'selected':''}>Neueste zuerst</option></select></div><div class="engine-container-list">${rows.map(c=>`<article class="engine-container"><div class="engine-container-heading"><div><h3>${safe(c.name)}</h3><code>${safe(c.image)}</code></div><span class="pill ${c.state==='running'?'':'gray'}">${safe(c.state==='running'?'Läuft':c.state==='exited'?'Gestoppt':c.state)}${c.health?' · '+safe(c.health):''}</span></div><div class="app-live-grid" data-engine-metric="${safe(c.id)}">${metric(metrics[c.id],bytes)}</div><div class="engine-facts"><span>${safe(c.networks.map(n=>n.name+': '+(n.ipv4||n.ipv6||'—')).join(' · ')||'Kein Netzwerk')}</span><span>${safe(ports(c.ports)||'Keine freigegebenen Ports')}</span></div><div class="engine-actions">${button(c.state==='running'?'Stoppen':'Starten',c.state==='running'?'stop':'start',c.id)}${c.state==='running'?button('Neustarten','restart',c.id):''}${button('Details & Logs','details',c.id,'primary')}<details><summary class="button small">Weitere Aktionen</summary><div>${button('Entfernen','remove',c.id,'danger')}${c.managed_app?`<button class="button small" data-action="app-manage" data-id="${safe(c.managed_app)}">App-Einstellungen</button>`:''}</div></details></div></article>`).join('')||'<p class="empty">Keine Container gefunden. Lege einen Container mit einem Docker-Image an.</p>'}</div>`;
   if(view==='images')content=`<div class="engine-resource-list">${data.images.map(row=>`<article><div><strong>${safe(row.Repository)}:${safe(row.Tag)}</strong><small>${safe(row.Size)} · ${safe(row.CreatedSince)}</small></div>${button('Entfernen','image-remove',row.ID,'danger')}</article>`).join('')||'<p class="empty">Noch keine Images geladen.</p>'}</div>`;
   if(view==='volumes')content=`<p class="hint">Volumes bewahren Daten auch nach dem Entfernen eines Containers. Benutzte Volumes können nicht entfernt werden.</p><div class="engine-resource-list">${data.volumes.map(row=>`<article><div><strong>${safe(row.Name)}</strong><small>Treiber: ${safe(row.Driver)}</small></div>${button('Entfernen','volume-remove',row.Name,'danger')}</article>`).join('')||'<p class="empty">Noch keine Volumes angelegt.</p>'}</div>`;
   if(view==='networks')content=`<div class="engine-resource-list">${data.networks.map(row=>`<article><div><strong>${safe(row.Name)}</strong><small>${safe(row.Driver)} · ${safe(row.Scope)}</small></div></article>`).join('')}</div><button class="button" data-action="app-networks">Netzwerke erstellen & verwalten</button>`;
   container.innerHTML=`<section class="engine-workbench"><div class="engine-toolbar"><div role="tablist" aria-label="Docker-Bereiche">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${view===id}" data-engine-tab="${id}" class="button small ${view===id?'primary':''}">${label} <small>${data[id]?.length||0}</small></button>`).join('')}</div><div class="engine-toolbar-actions">${button('Aktualisieren','refresh')}${button(view==='images'?'Image laden':view==='volumes'?'Volume erstellen':'Container erstellen',view==='images'?'pull':view==='volumes'?'volume-create':'create','','primary')}</div></div><p class="hint" role="status" data-engine-status>${busy?'Aktion läuft …':data.available===false?safe(data.error||'Docker nicht erreichbar.'):'Direkte Docker-Verwaltung · Änderungen und Nutzdaten bleiben auf deinem NAS.'}</p>${content}</section>`;
  }
  async function refresh(force=false){if(refreshing||!alive||container.ownerDocument.hidden)return;refreshing=true;try{const next=await api('/api/docker-engine');if(!alive)return;const changed=JSON.stringify(next)!==JSON.stringify(data);data=next;if(force||changed)render();const values=await api('/api/docker-metrics');if(!alive)return;metrics=values.containers||{};container.querySelectorAll('[data-engine-metric]').forEach(node=>node.innerHTML=metric(metrics[node.dataset.engineMetric],bytes));}catch(error){if(alive){const status=container.querySelector('[data-engine-status]');if(status)status.textContent=error.message;}}finally{refreshing=false;}}
  const field=(label,name,type='text',value='',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${safe(value)}" ${extra}></label>`;
  const end=text=>`<div class="form-actions"><button type="button" class="button" data-action="close">Abbrechen</button><button type="submit" class="button primary">${text}</button></div>`;
  const select=(label,key,values)=>`<label class="field">${label}<select name="${key}">${values.map(([id,text])=>`<option value="${safe(id)}">${safe(text)}</option>`).join('')}</select></label>`;
  function create(){dialog('Container erstellen',`<form><div class="form-grid">${field('Name','name','text','','required maxlength="48"')}${field('Docker-Image','image','text','','required placeholder="nginx:stable"')}${select('Netzwerk','network',[['bridge','Bridge (Standard)'],['host','Host'],['none','Ohne Netzwerk'],...data.networks.filter(v=>!['bridge','host','none'].includes(v.Name)).map(v=>[v.Name,v.Name])])}${select('Neustartregel','restart',[['unless-stopped','Sofern nicht manuell gestoppt'],['always','Immer'],['on-failure','Bei Fehler'],['no','Nicht automatisch']])}${field('RAM-Limit (MiB)','memory_mb','number','1024','min="64" required')}${field('CPU-Limit','cpus','number','2','min="1" required')}${select('Datenvolume','volume',[['','Kein Volume'],...data.volumes.map(v=>[v.Name,v.Name])])}${field('Datenziel im Container','target','text','/data')}</div><label class="field">Ports · eine Zuordnung je Zeile<textarea name="ports" rows="3" placeholder="8080:80/tcp"></textarea></label><p class="hint">Bei Host/Ohne Netzwerk das Portfeld leer lassen. Ein fehlendes Image wird beim Erstellen geladen.</p><label class="field">Umgebung · NAME=Wert je Zeile<textarea name="environment" rows="4" autocomplete="off" spellcheck="false" placeholder="TZ=Europe/Berlin"></textarea></label><details><summary>USB / GPU durchreichen</summary><div class="tile-picker-options">${(data.devices||[]).map(v=>`<label><input type="checkbox" name="devices" value="${safe(v.id)}">${safe(v.label)} · ${safe(v.kind)}</label>`).join('')||'<p class="hint">Keine kompatiblen Geräte erkannt.</p>'}</div></details>${end('Erstellen & starten')}</form>`,async form=>{const config=Object.fromEntries(form);config.devices=form.getAll("devices");config.ports=parsePorts(config.ports);config.environment=parseEnv(config.environment);config.memory_mb=Number(config.memory_mb);config.cpus=Number(config.cpus);await action('docker_container_create',{config});});}
  async function click(event){const tab=event.target.closest('[data-engine-tab]');if(tab){view=tab.dataset.engineTab;render();return;}const control=event.target.closest('[data-engine-action]');if(!control||busy)return;const op=control.dataset.engineAction,id=control.dataset.engineId;
   try{if(op==='refresh'){await refresh(true);return;}if(op==='create'){create();return;}if(op==='pull'){dialog('Docker-Image laden',`<form>${field('Image mit Tag','image','text','','required placeholder="nginx:stable"')}${end('Laden')}</form>`,async form=>action('docker_image_pull',{image:form.get('image')}));return;}if(op==='volume-create'){dialog('Datenvolume erstellen',`<form>${field('Volume-Name','resource','text','','required')}${end('Erstellen')}</form>`,async form=>action('docker_resource',{kind:'volume',action:'create',resource:form.get('resource')}));return;}
    if(op==='details'){const result=await api('/api/docker-container?container='+encodeURIComponent(id)),c=result.container;dialog('Container · '+c.name,`<dl class="engine-details"><dt>Image</dt><dd>${safe(c.image)}</dd><dt>Status</dt><dd>${safe(c.state)}</dd><dt>Neustartregel</dt><dd>${safe(c.restart||'no')}</dd><dt>Netzwerk</dt><dd>${safe(c.networks.map(n=>n.name+' · '+(n.ipv4||n.ipv6||'—')).join(' / '))}</dd><dt>Ports</dt><dd>${safe(ports(c.ports)||'—')}</dd><dt>Daten</dt><dd>${c.mounts.map(m=>`${safe(m.source)} → ${safe(m.target)} (${m.writable?'Lesen/Schreiben':'Lesen'})`).join('<br>')||'—'}</dd></dl><h3>Letzte 150 Logzeilen</h3><pre class="code" tabindex="0">${safe(result.logs||'Keine Logs vorhanden.')}</pre>${button('Logs aktualisieren','details',id)}`);return;}
    if(['remove','image-remove','volume-remove'].includes(op)&&!await askYesNo(op==='volume-remove'?'Volume und seine Daten unwiderruflich löschen?':op==='image-remove'?'Dieses unbenutzte Image entfernen?':'Container entfernen? Volumes bleiben erhalten.'))return;
    busy=true;control.disabled=true;if(op==='image-remove'||op==='volume-remove')await action('docker_resource',{kind:op==='image-remove'?'image':'volume',action:'remove',resource:id});else await action('docker_container_action',{container:id,action:op});
   }catch(error){toast(error.message,true);}finally{busy=false;control.disabled=false;}
  }
  function input(event){if(event.target.matches('[data-engine-search]')){query=event.target.value;const q=query.toLowerCase();for(const node of container.querySelectorAll('.engine-container'))node.hidden=!node.textContent.toLowerCase().includes(q);}if(event.target.matches('[data-engine-sort]')){sort=event.target.value;render();}}
  // Dialog buttons live outside the workbench. One delegated listener supports
  // log refresh and is always removed on navigation/logout.
  const doc=container.ownerDocument;doc.addEventListener('click',click);container.addEventListener('input',input);container.addEventListener('change',input);render();const timer=setInterval(()=>refresh(),5000);current=()=>{alive=false;clearInterval(timer);doc.removeEventListener('click',click);container.removeEventListener('input',input);container.removeEventListener('change',input);};await refresh(true);
 }
 const api={mount,dispose,ports,parsePorts,parseEnv,metric};if(root)root.TitanDocker=api;if(typeof module==='object')module.exports=api;
})(typeof window==='undefined'?null:window);
