'use strict';
// Destination browsing only. Existing submit handlers retain all write checks.
(function(root,factory){const picker=factory();if(typeof module==='object'&&module.exports)module.exports=picker;if(root)root.TitanFolderPicker=picker;})(typeof window==='undefined'?null:window,function(){
 const instances=new Map(),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function normalize(value){const path=String(value??'');if(path.startsWith('/')||path.includes('\0')||path.split('/').includes('..')||path.length>4096)throw new Error('Ein gültiger relativer Zielordner ist erforderlich.');return path.split('/').filter(part=>part&&part!=='.').join('/');}
 function leaf(value){const name=String(value??'');if(!name||name==='.'||name==='..'||name.includes('/')||name.includes('\0')||name.length>255)throw new Error('Ein einzelner gültiger Zielname ist erforderlich.');return name;}
 const fieldName=value=>/^[A-Za-z][A-Za-z0-9_]*$/.test(value||'')?value:'destination';
 function render(options={}){const pathField=fieldName(options.pathField||'destination'),shareField=fieldName(options.shareField||'destination_share'),leafField=options.leafField?fieldName(options.leafField):'',path=normalize(options.initialPath||'');return `<section class="folder-picker" data-folder-picker data-path-field="${pathField}" data-share-field="${shareField}" data-leaf-field="${leafField}" data-initial-path="${esc(path)}" aria-label="Zielordner auswählen"><input type="hidden" name="${pathField}" value="${esc(path)}"><div class="folder-picker-header"><strong>Zielordner</strong><button type="button" class="button small" data-folder-picker-reload>↻</button></div><div class="folder-picker-breadcrumbs" data-folder-picker-breadcrumbs></div><p class="folder-picker-current">Ausgewählt: <strong data-folder-picker-current>${esc(path||'Hauptordner')}</strong></p><p class="hint" role="status" aria-live="polite" data-folder-picker-status>Ordner werden geladen …</p><div class="folder-picker-list" data-folder-picker-list></div><div class="folder-picker-pages" data-folder-picker-pages></div><p class="hint">Ein Ordnerklick öffnet und wählt diesen Zielordner. Bestehende Dateien werden nicht überschrieben.</p></section>`;}
 function disposeWithin(root){for(const[node,state]of instances)if(node.isConnected===false||node===root||root?.contains?.(node)){state.destroy();instances.delete(node);}}
 function mount(scope,options={}){
  const node=scope?.querySelector('[data-folder-picker]');if(!node||!options.api)return null;instances.get(node)?.destroy();
  const controller=new AbortController(),doc=scope.ownerDocument,pathField=fieldName(options.pathField||node.dataset.pathField),shareField=fieldName(options.shareField||node.dataset.shareField),leafField=options.leafField||node.dataset.leafField;
  const destination=scope.querySelector(`[name="${pathField}"]`),share=scope.querySelector(`[name="${shareField}"]`),name=leafField?scope.querySelector(`[name="${fieldName(leafField)}"]`):null;
  if(!destination||!share)return null;
  const status=node.querySelector('[data-folder-picker-status]'),list=node.querySelector('[data-folder-picker-list]'),crumbs=node.querySelector('[data-folder-picker-breadcrumbs]'),current=node.querySelector('[data-folder-picker-current]'),pages=node.querySelector('[data-folder-picker-pages]');
  let path=normalize(options.initialPath??node.dataset.initialPath??''),offset=0,alive=true,pending=false,valid=false,generation=0,lastShare=String(share.value||'');
  const listen=(target,type,callback,capture=false)=>target?.addEventListener(type,callback,{signal:controller.signal,capture});
  function value(){let ok=true;try{const result=name?[path,leaf(name.value)].filter(Boolean).join('/'):path;if(result.length>4096)throw new Error('Der Zielpfad ist zu lang.');destination.value=result;}catch{destination.value='';ok=false;}current.textContent=(share.value==='@system'?'/':'')+(path||'Hauptordner');return ok;}
  function breadcrumbs(){const parts=path.split('/').filter(Boolean);crumbs.innerHTML=`<button type="button" class="button small" data-folder-picker-path="">Hauptordner</button>${parts.map((part,index)=>`<span aria-hidden="true">/</span><button type="button" class="button small" data-folder-picker-path="${esc(parts.slice(0,index+1).join('/'))}">${esc(part)}</button>`).join('')}`;}
  async function load(next=path,page=0){const mine=++generation;pending=true;valid=false;list.innerHTML='';pages.innerHTML='';status.textContent='Ordner werden geladen …';
   try{path=normalize(next);offset=page;value();breadcrumbs();const result=await options.api('/api/files?'+new URLSearchParams({share:share.value,path,offset:String(offset),limit:'200'}));if(!alive||mine!==generation)return;
    if(!result||!Array.isArray(result.entries))throw new Error('Ungültige Ordnerliste.');if(share.value==='@system'&&typeof result.path==='string'){path=normalize(result.path);value();breadcrumbs();}
    const folders=result.entries.filter(entry=>entry&&entry.directory&&!entry.symlink&&entry.readable!==false&&typeof entry.name==='string'&&entry.name!=='.'&&entry.name!=='..'&&!entry.name.includes('/')&&!entry.name.includes('\0')&&entry.name.length<=255);
    list.innerHTML=folders.map(entry=>`<button type="button" class="folder-picker-folder" data-folder-picker-path="${esc([path,entry.name].filter(Boolean).join('/'))}"><span aria-hidden="true">▱</span><span>${esc(entry.name)}</span><span aria-hidden="true">›</span></button>`).join('');
    status.textContent=folders.length?`${folders.length} Unterordner auf dieser Seite. Der oben angezeigte Ordner ist bereits ausgewählt.`:'Keine Unterordner auf dieser Seite. Der oben angezeigte Ordner ist ausgewählt.';
    pages.innerHTML=`<button type="button" class="button small" data-folder-picker-offset="${Math.max(0,offset-200)}" ${offset?'':'disabled'}>← Zurück</button><button type="button" class="button small" data-folder-picker-offset="${offset+200}" ${result.has_more?'':'disabled'}>Weitere Einträge →</button>`;valid=true;
   }catch(error){if(alive&&mine===generation){status.textContent=error.message||'Zielordner nicht verfügbar. Wähle einen anderen Ort oder lade erneut.';valid=false;}}finally{if(mine===generation)pending=false;}
  }
  listen(node,'click',event=>{const folder=event.target.closest?.('[data-folder-picker-path]'),pager=event.target.closest?.('[data-folder-picker-offset]'),reload=event.target.closest?.('[data-folder-picker-reload]');if(folder&&!folder.disabled){event.preventDefault();load(folder.dataset.folderPickerPath,0);}else if(pager&&!pager.disabled){event.preventDefault();load(path,Number(pager.dataset.folderPickerOffset));}else if(reload){event.preventDefault();load(path,offset);}});
  listen(share,'change',()=>{if(String(share.value)!==lastShare){lastShare=String(share.value);load('',0);}});listen(name,'input',value);
  // Capture on the dialog/area before its original form callback can run.
  listen(scope,'submit',event=>{if(!node.closest?.('form')?.contains?.(event.target)&&event.target!==node.closest?.('form'))return;if(pending||!valid){event.preventDefault();event.stopImmediatePropagation();status.textContent=pending?'Bitte warten, bis der Zielordner geladen wurde.':'Zuerst einen verfügbaren Zielordner auswählen.';return;}if(name){try{leaf(name.value);if(!value())throw new Error('Der Zielpfad ist zu lang.');}catch(error){destination.value='';event.preventDefault();event.stopImmediatePropagation();status.textContent=error.message;}}},true);
  const state={load,value:()=>destination.value,valid:()=>valid&&!pending,destroy(){alive=false;generation++;controller.abort();}};instances.set(node,state);load();return state;
 }
 return {render,mount,disposeWithin,normalize,leaf};
});
