'use strict';
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanMenu=ui;})(typeof window==='undefined'?null:window,function(){
 function normalize(rows,keys){const allowed=new Set(keys),seen=new Set();const take=k=>{if(typeof k==='string'&&allowed.has(k)&&!seen.has(k)){seen.add(k);return true;}return false;};const ids=new Set();const out=[];for(const row of Array.isArray(rows)?rows:[]){if(typeof row==='string'){if(take(row))out.push(row);}else if(row&&typeof row.id==='string'&&/^folder-[a-z0-9-]{1,40}$/.test(row.id)&&!ids.has(row.id)&&typeof row.name==='string'&&Array.isArray(row.items)){ids.add(row.id);out.push({id:row.id,name:row.name.slice(0,40)||'Ordner',items:row.items.filter(take)});}}for(const key of keys)if(take(key))out.push(key);return out;}
 function extract(rows,key){for(let i=0;i<rows.length;i++){const row=rows[i];if(row===key||row.id===key)return rows.splice(i,1)[0];if(typeof row==='object'){const j=row.items.indexOf(key);if(j>=0)return row.items.splice(j,1)[0];}}return null;}
 function move(rows,key,target,group=false){const next=JSON.parse(JSON.stringify(rows));if(key===target)return next;const source=extract(next,key);if(!source)return next;const folder=next.find(r=>r.id===target);if(group&&folder&&typeof source==='string')folder.items.push(source);else{const parent=next.find(r=>typeof r==='object'&&r.items.includes(target));if(parent&&typeof source==='string'){parent.items.splice(parent.items.indexOf(target),0,source);return next;}const index=next.findIndex(r=>r===target||r.id===target);if(group&&typeof source==='string'&&index>=0&&typeof next[index]==='string'){next[index]={id:'folder-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),name:'Ordner',items:[next[index],source]};}else next.splice(index<0?next.length:index,0,source);}return next;}
 async function mount(container,{tools,apps=[],user,esc,icon,api,toast}){
  if(!container)return;let alive=true,editing=false,busy=false,opened=null,drag=null,naming=null,sortable=null,groupTarget=null,groupTimer=null;
  const entries=tools.map(([id,name,detail])=>({id:'tool:'+id,name,detail,href:'#'+id,glyph:id}));
  for(const app of apps)if(/^[a-zA-Z0-9_-]{1,64}$/.test(app.id))entries.push({id:'app:'+app.id,name:app.name||app.id,detail:app.state==='running'?'Läuft · Verwalten und öffnen':'Gestoppt · Verwalten',href:'#docker',glyph:'apps',app:app.id});
  const map=new Map(entries.map(x=>[x.id,x]));let rows=entries.map(x=>x.id),hidden=[];try{const saved=await api('/api/launcher-layout');rows=normalize(saved.items,rows);hidden=Array.isArray(saved.hidden)?saved.hidden.filter(key=>map.has(key)):saved.items?.length?[]:['tool:shares','tool:backups','tool:services','tool:terminal','tool:updates','tool:control'];}catch{toast?.('Menü-Anordnung konnte nicht geladen werden.',true);}
  if(!container.isConnected)return;
  function controls(id){return editing?`<div class="menu-item-controls"><button type="button" data-menu-drag="${esc(id)}" aria-label="Ziehen oder in Ordner gruppieren">⠿</button><button type="button" data-menu-step="${esc(id)}" data-direction="-1" aria-label="Nach vorne">←</button><button type="button" data-menu-step="${esc(id)}" data-direction="1" aria-label="Nach hinten">→</button><select data-menu-folder="${esc(id)}" aria-label="In Ordner verschieben"><option value="">Verschieben …</option><option value="root">Hauptmenü</option>${rows.filter(r=>typeof r==='object'&&r.id!==id).map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}</select></div>`:'';}
  function card(row){if(typeof row==='string'){const app=map.get(row);if(!app)return '';return `<div class="menu-item" data-menu-item="${esc(row)}"><a class="desktop-app-link" href="${esc(app.href)}" ${app.app?'data-action="app-manage" data-id="'+esc(app.app)+'"':''}><span class="desktop-app-icon" data-app="${esc(app.glyph)}">${app.app&&window.TitanArtwork?window.TitanArtwork.render(app.app):icon(app.glyph)}</span><span class="desktop-app-name">${esc(app.name)}</span><span class="desktop-app-detail">${esc(app.detail)}</span></a>${controls(row)}</div>`;}return `<div class="menu-item" data-menu-item="${esc(row.id)}"><button type="button" class="desktop-app-link menu-folder" data-menu-open="${esc(row.id)}"><span class="menu-folder-preview">${row.items.slice(0,4).map(k=>`<span>${icon(map.get(k)?.glyph||'apps')}</span>`).join('')||icon('files')}</span><span class="desktop-app-name">${esc(row.name)}</span><span class="desktop-app-detail">${row.items.length} Anwendungen</span></button>${controls(row.id)}${editing?`<button class="button small" data-menu-rename="${esc(row.id)}">Umbenennen</button><button class="button small" data-menu-dissolve="${esc(row.id)}">Ordner auflösen</button>`:''}</div>`;}
  function render(){sortable?.destroy();sortable=null;if(!alive||!container.isConnected)return;const folder=rows.find(r=>r.id===opened);container.innerHTML=`<div class="menu-toolbar"><h2 class="desktop-section-heading" id="desktop-apps-title">${folder?esc(folder.name):'Deine Anwendungen'}</h2><div>${folder?'<button class="button small" data-menu-back>Zurück</button>':''}<button class="button small" data-menu-edit>${editing?'Fertig':'Anordnen'}</button>${editing?'<button class="button small" data-menu-new>Neuer Ordner</button>':''}</div></div>${naming?`<form data-menu-name-form class="inline-form"><label>Ordnername <input name="folder_name" maxlength="40" required value="${esc(naming.value)}"></label><button class="button small primary" type="submit">Speichern</button><button class="button small" type="button" data-menu-name-cancel>Abbrechen</button></form>`:''}${editing?`<details class="menu-suggestions"><summary class="button small">Werkzeuge & Apps auswählen</summary><div class="tile-picker">${entries.map(item=>`<label><input type="checkbox" data-menu-visible="${esc(item.id)}" ${hidden.includes(item.id)?'':'checked'}>${esc(item.name)}</label>`).join('')}</div></details>`:''}${editing?'<p class="hint">Icons am Griff ziehen. Kurz mittig über einer App halten, bis sie grün markiert ist: Ordner erstellen. Änderungen werden automatisch gespeichert.</p>':''}<div class="desktop-apps menu-grid">${(folder?folder.items:rows).filter(row=>editing||typeof row!=='string'||!hidden.includes(row)).map(card).join('')}</div><span role="status" class="hint">${busy?'Anordnung wird gespeichert …':''}</span>`;attachDrag();}
  async function persist(redraw=true){busy=true;if(redraw)render();try{await api('/api/launcher-layout',{items:rows,hidden});}catch(error){toast?.(error.message||'Speichern fehlgeschlagen.',true);}finally{busy=false;if(redraw)render();}}
  function change(next){if(busy)return;rows=next;void persist();}
  function click(e){const button=e.target.closest('button');if(!button||busy)return;if(button.hasAttribute('data-menu-edit')){editing=!editing;render();}else if(button.dataset.menuOpen){opened=button.dataset.menuOpen;render();}else if(button.hasAttribute('data-menu-back')){opened=null;render();}else if(button.hasAttribute('data-menu-new')){naming={id:null,value:'Neuer Ordner'};render();}else if(button.hasAttribute('data-menu-name-cancel')){naming=null;render();}else if(button.dataset.menuRename){const folder=rows.find(r=>r.id===button.dataset.menuRename);naming={id:folder.id,value:folder.name};render();}else if(button.dataset.menuDissolve){const i=rows.findIndex(r=>r.id===button.dataset.menuDissolve);rows.splice(i,1,...rows[i].items);opened=null;void persist();}else if(button.dataset.menuStep){const key=button.dataset.menuStep,folder=rows.find(r=>r.id===opened),list=folder?folder.items:rows,i=list.findIndex(r=>r===key||r.id===key),j=i+Number(button.dataset.direction);if(i>=0&&j>=0&&j<list.length){[list[i],list[j]]=[list[j],list[i]];void persist();}}}
  function submit(e){if(!e.target.matches('[data-menu-name-form]'))return;e.preventDefault();if(busy||!naming)return;const name=new FormData(e.target).get('folder_name')?.trim();if(!name)return;if(naming.id)rows.find(r=>r.id===naming.id).name=name.slice(0,40);else rows.push({id:'folder-'+Date.now().toString(36),name:name.slice(0,40),items:[]});naming=null;void persist();}
  function select(e){const visibility=e.target.closest('[data-menu-visible]');if(visibility&&!busy){hidden=hidden.filter(key=>key!==visibility.dataset.menuVisible);if(!visibility.checked)hidden.push(visibility.dataset.menuVisible);void persist();return;}const control=e.target.closest('[data-menu-folder]');if(!control||!control.value||busy)return;change(move(rows,control.dataset.menuFolder,control.value==='root'?'':control.value,true));}
  function clearGroup(){clearTimeout(groupTimer);groupTimer=null;groupTarget=null;container.querySelectorAll('.menu-group-ready').forEach(node=>node.classList.remove('menu-group-ready'));}
  function attachDrag(){const Sortable=container.ownerDocument.defaultView?.Sortable,grid=container.querySelector('.menu-grid');if(!editing||!Sortable||!grid)return;
   sortable=new Sortable(grid,{draggable:'[data-menu-item]',handle:'[data-menu-drag]',animation:container.ownerDocument.defaultView?.matchMedia?.("(prefers-reduced-motion: reduce)").matches?0:220,easing:'cubic-bezier(.2,.8,.2,1)',forceFallback:true,fallbackOnBody:true,fallbackTolerance:5,ghostClass:'layout-placeholder',fallbackClass:'layout-floating',scroll:true,scrollSensitivity:70,scrollSpeed:12,
    onMove(event,original){const point=original.touches?.[0]||original,r=event.relatedRect,target=event.related?.dataset.menuItem,source=event.dragged?.dataset.menuItem;const central=point.clientX>r.left+r.width*.25&&point.clientX<r.right-r.width*.25&&point.clientY>r.top+r.height*.25&&point.clientY<r.bottom-r.height*.25;
     if(!opened&&target&&source!==target&&typeof rows.find(row=>row===source||row.id===source)==='string'&&central){if(groupTarget?.id!==target){clearGroup();groupTarget={id:target,ready:false};groupTimer=setTimeout(()=>{if(groupTarget?.id===target){groupTarget.ready=true;event.related.classList.add('menu-group-ready');}},650);}return false;}clearGroup();},
    onEnd(event){const source=event.item.dataset.menuItem,target=groupTarget?.ready?groupTarget.id:null;clearGroup();if(target){rows=move(rows,source,target,true);void persist();return;}const ordered=[...grid.querySelectorAll('[data-menu-item]')].map(node=>node.dataset.menuItem);const folder=rows.find(row=>row.id===opened);if(folder)folder.items=ordered;else{const mapped=new Map(rows.map(row=>[typeof row==='string'?row:row.id,row]));rows=ordered.map(id=>mapped.get(id)).filter(Boolean);}void persist(false);}
   });
  }
  function down(e){if(sortable)return;const handle=e.target.closest('[data-menu-drag]');if(!handle||busy)return;e.preventDefault();drag={key:handle.dataset.menuDrag,id:e.pointerId,x:e.clientX,y:e.clientY};handle.closest('[data-menu-item]').classList.add('menu-dragging');handle.setPointerCapture?.(e.pointerId);}
  function up(e){if(!drag||drag.id!==e.pointerId)return;const source=drag;drag=null;container.querySelectorAll('.menu-dragging,.menu-drop-target').forEach(el=>el.classList.remove('menu-dragging','menu-drop-target'));if(Math.hypot(e.clientX-source.x,e.clientY-source.y)<8)return;const target=container.ownerDocument.elementFromPoint(e.clientX,e.clientY)?.closest('[data-menu-item]');if(!target)return;const rect=target.getBoundingClientRect(),group=e.clientX>rect.left+rect.width*.25&&e.clientX<rect.right-rect.width*.25;change(move(rows,source.key,target.dataset.menuItem,group));}
  function pointermove(e){if(!drag)return;container.querySelectorAll('.menu-drop-target').forEach(el=>el.classList.remove('menu-drop-target'));container.ownerDocument.elementFromPoint(e.clientX,e.clientY)?.closest('[data-menu-item]')?.classList.add('menu-drop-target');}
  function cancel(){drag=null;container.querySelectorAll('.menu-dragging,.menu-drop-target').forEach(el=>el.classList.remove('menu-dragging','menu-drop-target'));}
  container.addEventListener('submit',submit);container.addEventListener('click',click);container.addEventListener('change',select);container.addEventListener('pointermove',pointermove);container.addEventListener('pointercancel',cancel);container.addEventListener('pointerdown',down);container.addEventListener('pointerup',up);render();return {destroy(){alive=false;sortable?.destroy();clearGroup();container.removeEventListener('submit',submit);container.removeEventListener('click',click);container.removeEventListener('change',select);container.removeEventListener('pointermove',pointermove);container.removeEventListener('pointercancel',cancel);container.removeEventListener('pointerdown',down);container.removeEventListener('pointerup',up);}};
 }
 return {normalize,move,extract,mount};
});
