'use strict';
/* Original gallery over Titan's authenticated, per-user file API. */
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanPhotos=ui;})(typeof window==='undefined'?null:window,function(){
 const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const LIMIT=48,PREVIEW_LIMIT=24*1024*1024,THUMB_LIMIT=4*1024*1024;
 function fileUrl(share,path,preview=false){return '/api/file?'+new URLSearchParams({share,path,...(preview?{preview:'1'}:{})});}
 function canPreview(row,limit=PREVIEW_LIMIT){return !row.directory&&/\.(jpe?g|png|gif|webp)$/i.test(row.name||'')&&Number.isFinite(row.size)&&row.size>=0&&row.size<=limit;}
 function query({share,path='',search='',offset=0}){return '/api/files?'+new URLSearchParams({share,path,search:search.slice(0,200),offset:String(Math.max(0,offset)),limit:String(LIMIT),recursive:'1',type:'image'});}
 function createLoader(api,receive){let serial=0,controller=null,alive=true;return {async load(state){const id=++serial;controller?.abort();controller=new AbortController();receive({loading:true});try{const data=await api(query(state),undefined,{signal:controller.signal});if(alive&&id===serial)receive({loading:false,data});}catch(error){if(alive&&id===serial&&error.name!=='AbortError')receive({loading:false,error:error.message||'Fotos konnten nicht geladen werden.'});}},dispose(){alive=false;serial++;controller?.abort();}};}
 function cards(entries,share){return entries.map((row,index)=>`<button type="button" class="photo-card" data-photo="${index}" aria-label="${escape(row.name)} öffnen"><span class="photo-thumbnail">${canPreview(row,THUMB_LIMIT)?`<img src="${escape(fileUrl(share,row.path,true))}" alt="" loading="lazy" decoding="async">`:'<span class="photo-file-placeholder" aria-hidden="true">▧</span>'}</span><strong>${escape(row.name)}</strong><small>${escape(row.path)}</small></button>`).join('');}
 function render(){return `<section class="photos-app" aria-label="Fotos"><header class="photos-heading"><img src="/app-icons/titan-photos.svg" alt="" width="64" height="64"><div><p class="eyebrow">DEINE SAMMLUNG</p><h1>Fotos</h1><p>Bilder aus deinen Freigaben. Privat auf deinem NAS.</p></div></header><form class="photos-filter" data-photo-filters><label>Freigabe<select data-photo-share aria-label="Foto-Freigabe" disabled><option>Wird geladen …</option></select></label><label>Ordner<input data-photo-path placeholder="Alle Unterordner" aria-label="Foto-Ordner" maxlength="4096"></label><label class="photos-search">Suche<input type="search" data-photo-search placeholder="Dateiname suchen …" maxlength="200" aria-label="Fotos durchsuchen"></label><button class="button primary" type="submit">Anzeigen</button></form><p class="photos-status" role="status" aria-live="polite" data-photo-status>Freigaben werden geladen …</p><p class="notice" data-photo-warning hidden></p><div class="photos-grid" data-photo-grid></div><footer class="photos-pagination"><button type="button" class="button" data-photo-prev disabled>Zurück</button><span data-photo-page></span><button type="button" class="button" data-photo-next disabled>Weiter</button></footer><p class="photos-note">JPEG, PNG, GIF und WebP direkt ansehen. Andere Formate herunterladen. Große Bilder werden erst beim Öffnen geladen. Die Suche ist auf die ausgewählte Freigabe begrenzt.</p></section>`;}
 let current;
 function mount(root,{api,toast}={}){
  current?.dispose();const app=root.querySelector('.photos-app');if(!app)return;
  const doc=root.ownerDocument,select=app.querySelector('[data-photo-share]'),form=app.querySelector('form'),grid=app.querySelector('[data-photo-grid]'),status=app.querySelector('[data-photo-status]'),warning=app.querySelector('[data-photo-warning]'),previous=app.querySelector('[data-photo-prev]'),next=app.querySelector('[data-photo-next]'),page=app.querySelector('[data-photo-page]');
  let alive=true,entries=[],state={share:'',path:'',search:'',offset:0},selected=0,opener=null,busy=false;
  const initial=new AbortController(),viewer=doc.createElement('dialog');viewer.className='photo-viewer';viewer.setAttribute('aria-label','Fotoansicht');doc.body.append(viewer);
  function close(){viewer.close();viewer.innerHTML='';if(opener?.isConnected)opener.focus();}
  function show(index){selected=index;const row=entries[index];if(!row)return;viewer.innerHTML=`<header><div><strong>${escape(row.name)}</strong><small>${index+1} / ${entries.length}</small></div><button type="button" class="button" data-photo-close aria-label="Fotoansicht schließen">Schließen</button></header><div class="photo-stage">${canPreview(row)?`<img src="${escape(fileUrl(state.share,row.path,true))}" alt="${escape(row.name)}"><p data-photo-load-error hidden>Dieses Bild konnte nicht angezeigt werden. Du kannst die Originaldatei herunterladen.</p>`:'<p>Für dieses Format oder diese Dateigröße steht keine direkte Vorschau zur Verfügung. Die Originaldatei bleibt unverändert.</p>'}</div><footer><button class="button" type="button" data-photo-back ${index===0?'disabled':''}>Vorheriges</button><a class="button" href="${escape(fileUrl(state.share,row.path))}" download>Original herunterladen</a><button class="button" type="button" data-photo-forward ${index===entries.length-1?'disabled':''}>Nächstes</button></footer>`;const img=viewer.querySelector('img');if(img)img.onerror=()=>{img.hidden=true;viewer.querySelector('[data-photo-load-error]').hidden=false;};if(!viewer.open)viewer.showModal();viewer.querySelector('[data-photo-close]').focus();}
  const loader=createLoader(api,result=>{
   busy=result.loading;form.querySelector('button').disabled=busy;previous.disabled=true;next.disabled=true;grid.setAttribute('aria-busy',String(busy));
   if(busy){entries=[];grid.innerHTML='';warning.hidden=true;status.textContent='Fotos werden gesucht …';page.textContent='';return;}
   if(result.error){status.textContent=result.error;return;}
   const data=result.data;entries=Array.isArray(data.entries)?data.entries.filter(row=>!row.directory&&typeof row.path==='string'&&typeof row.name==='string'):[];grid.innerHTML=cards(entries,state.share);
   const total=Number(data.total)||0;status.textContent=entries.length?`${state.offset+1}–${state.offset+entries.length} von ${total} Bildern${data.truncated?' (Teilergebnis)':''}`:'Keine Bilder gefunden. Wähle eine andere Freigabe oder einen anderen Ordner.';
   warning.hidden=!data.warning&&!data.truncated;warning.textContent=data.warning||(data.truncated?'Die Suche ist begrenzt. Bitte wähle einen kleineren Ordner.':'');previous.disabled=state.offset===0;next.disabled=!(data.has_more??state.offset+LIMIT<total);page.textContent=entries.length?'Seite '+(Math.floor(state.offset/LIMIT)+1):'';
  });
  function load(){if(state.share)void loader.load({...state});}
  function submit(event){event.preventDefault();state={share:select.value,path:app.querySelector('[data-photo-path]').value.trim(),search:app.querySelector('[data-photo-search]').value.trim(),offset:0};load();}
  function change(){state={...state,share:select.value,path:'',offset:0};app.querySelector('[data-photo-path]').value='';load();}
  function click(event){const target=event.target.closest('button');if(!target||busy)return;if(target.hasAttribute('data-photo')){opener=target;show(Number(target.dataset.photo));}else if(target===previous&&!previous.disabled){state.offset=Math.max(0,state.offset-LIMIT);load();}else if(target===next&&!next.disabled){state.offset+=LIMIT;load();}}
  function viewerClick(event){const target=event.target.closest('button');if(target?.hasAttribute('data-photo-close'))close();else if(target?.hasAttribute('data-photo-back')&&selected>0)show(selected-1);else if(target?.hasAttribute('data-photo-forward')&&selected<entries.length-1)show(selected+1);}
  function keys(event){if(event.key==='ArrowLeft'&&selected>0){event.preventDefault();show(selected-1);}if(event.key==='ArrowRight'&&selected<entries.length-1){event.preventDefault();show(selected+1);}}
  function cancel(event){event.preventDefault();close();}
  function imageError(event){if(event.target.tagName==='IMG'){event.target.hidden=true;event.target.parentElement.classList.add('photo-unavailable');}}
  form.addEventListener('submit',submit);select.addEventListener('change',change);app.addEventListener('click',click);grid.addEventListener('error',imageError,true);viewer.addEventListener('click',viewerClick);viewer.addEventListener('keydown',keys);viewer.addEventListener('cancel',cancel);
  void api('/api/shares',undefined,{signal:initial.signal}).then(shares=>{if(!alive)return;select.innerHTML=shares.map(share=>`<option value="${escape(share.name)}">${escape(share.name)}</option>`).join('');select.disabled=!shares.length;if(!shares.length){status.textContent='Noch keine freigegebenen Foto-Ordner. Lege im Dateimanager oder in den Einstellungen eine Freigabe an.';form.querySelector('button').disabled=true;return;}state.share=shares[0].name;load();}).catch(error=>{if(alive&&error.name!=='AbortError'){status.textContent=error.message;form.querySelector('button').disabled=true;toast?.(error.message,true);}});
  current={dispose(){alive=false;initial.abort();loader.dispose();if(viewer.open)viewer.close();viewer.remove();form.removeEventListener('submit',submit);select.removeEventListener('change',change);app.removeEventListener('click',click);grid.removeEventListener('error',imageError,true);}};return current;
 }
 return {render,mount,dispose(){current?.dispose();current=null;},fileUrl,canPreview,query,createLoader,cards};
});
