'use strict';
(function(root,factory){const ui=factory();if(typeof module==='object')module.exports=ui;if(root)root.TitanRemoteAccess=ui;})(typeof window==='undefined'?null:window,function(){
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const phases={preparing:'Einrichtung wird vorbereitet',installing:'Connector wird installiert',connecting:'Verbindung zu Cloudflare wird hergestellt',configuring:'Lokaler Zugang wird eingerichtet',checking:'Öffentlicher Zugang wird geprüft',ready:'Öffentlicher Zugang geprüft',needs_route:'Cloudflare-Route prüfen',needs_domain:'Öffentliche Adresse ergänzen',failed:'Einrichtung fehlgeschlagen',interrupted:'Einrichtung unterbrochen',stopped:'Connector ist gestoppt',removed:'Connector wurde entfernt',blocked:'Einrichtung derzeit nicht möglich',disconnected:'Cloudflare-Verbindung unterbrochen',disabled:'Öffentlicher Zugang deaktiviert'};
 const cloud='<svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M8 23h17a5 5 0 0 0 .3-10 8 8 0 0 0-15.5-2.3A6.2 6.2 0 0 0 8 23Z" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><path d="m13 18 3-3 3 3m-3-3v11" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>';
 let cleanup=null;
 function publicUrl(value){try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:'';}catch{return '';}}
 function checks(diagnosis){return diagnosis?.checks?.length?`<div class="remote-checks" role="status">${diagnosis.checks.map(check=>`<p><strong>${check.ok===true?'✓':check.ok===false?'!':'—'} ${esc(check.name)}</strong><br>${esc(check.message)}</p>`).join('')}<small>Prüfung: ${esc(new Date(diagnosis.checked_at*1000).toLocaleString('de-DE'))}</small></div>`:'<p class="hint">Mit „Verbindung prüfen“ testest du auch den öffentlichen Zugang.</p>';}
 function progress(setup={}){
  const phase=setup.phase||'',connected=setup.cloudflare_connected===true,ready=phase==='ready';
  return `<div class="tunnel-progress ${ready?'is-ready':setup.running?'is-running':phase==='failed'?'is-failed':''}" data-tunnel-progress role="status"><span class="tunnel-progress-symbol" aria-hidden="true">${ready?'✓':setup.running?'◌':connected?'↗':'○'}</span><div><strong>${esc(phases[phase]||'Noch nicht eingerichtet')}</strong><p>${esc(setup.message||(setup.running?'Du kannst dieses Fenster schließen. Die Einrichtung läuft weiter.':'Tunnel-Token einfügen und mit deinem Cloudflare-Tunnel verbinden.'))}</p>${connected&&!ready?'<small>Connector verbunden · öffentlicher Zugang noch nicht bestätigt</small>':''}</div></div>`;
 }
 function render(data){
  const remote=data.remote||{},setup=data.setup||{},disabled=data.demo||setup.running?'disabled':'',target=setup.service_url||'http://127.0.0.1:5102',origin=publicUrl(remote.public_origin),configured=!!setup.connector;
  const badge=setup.running?'Einrichtung läuft':({ready:'Geprüft',failed:'Fehlgeschlagen',interrupted:'Unterbrochen',disconnected:'Getrennt',disabled:'Deaktiviert',stopped:'Gestoppt',removed:'Nicht installiert',needs_domain:'Adresse fehlt',needs_route:'Route prüfen',blocked:'Prüfung nötig'}[setup.phase]||(configured?'Connector eingerichtet':'Nicht eingerichtet'));
  const safe={revision:data.revision,remote,setup,diagnosis:data.diagnosis,connectors:data.connectors||[],apps:data.apps||[],demo:!!data.demo};
  return `<section class="panel remote-access" data-remote-access data-config="${esc(JSON.stringify(safe))}">
   <header class="tunnel-heading"><span class="tunnel-brand">${cloud}</span><div><h2>Cloudflare Tunnel</h2><p>Dein NAS von unterwegs erreichen</p></div><span class="pill ${setup.phase==='ready'?'':'gray'}">${esc(badge)}</span></header>
   ${data.demo?'<p class="notice">Vorschau: In der Demo wird kein Tunnel verbunden.</p>':''}
   ${progress(setup)}
   ${(data.connectors||[]).some(row=>row.id!=='titan-cloudflared')?'<p class="hint">Schon ein Connector für denselben Tunnel aktiv? Nach der Umstellung den alten Connector in Docker stoppen, damit Cloudflare keine Anfragen an dessen abweichendes lokales Ziel verteilt.</p>':''}
   <form data-tunnel-form class="tunnel-connect-form"><div class="tunnel-step-heading"><span>1</span><div><h3>${configured?'Tunnel verbinden oder Token erneuern':'Tunnel verbinden'}</h3><p>Titan installiert und startet den Connector automatisch. Ein zusätzliches Verwaltungspasswort ist nicht nötig.</p></div></div>
    <label>Tunnel-Token<input type="password" name="token" autocomplete="off" spellcheck="false" maxlength="4096" required placeholder="Token aus Cloudflare hier einfügen" ${disabled}><small>Der Token wird geschützt auf deinem NAS gespeichert und hier nicht wieder angezeigt.</small></label>
    ${configured?`<input type="hidden" name="public_origin" value="${esc(remote.public_origin||'')}">`:`<label>Öffentliche Titan-Adresse <span class="field-optional">optional</span><input type="url" name="public_origin" placeholder="https://nas.example.de" value="${esc(remote.public_origin||'')}" ${disabled}><small>Die Adresse deines Tunnels, falls du sie schon in Cloudflare eingerichtet hast.</small></label>`}
    <div class="tunnel-connect-actions"><button class="button primary" type="submit" ${disabled}>${configured?'Tunnel verbinden':'Tunnel einrichten'}</button><details class="tunnel-token-help"><summary>Wo finde ich den Token?</summary><p>Öffne deinen Tunnel in <a href="https://one.dash.cloudflare.com/" target="_blank" rel="noopener noreferrer">Cloudflare ↗</a> und kopiere den Tunnel-Token aus der Connector-Einrichtung. Füge nur den Token ein, keinen Installationsbefehl.</p></details></div>
   </form>
   <section class="tunnel-route"><div class="tunnel-step-heading"><span>2</span><div><h3>Öffentliche Route</h3><p>Wenn die Route bereits auf dieses Ziel zeigt, übernimmt Titan die restliche lokale Einrichtung und prüft den Zugang.</p></div></div><div class="tunnel-route-target"><span>Service URL in Cloudflare</span><code>${esc(target)}</code></div><p class="hint">Fehlt die Route noch, ordne deinen öffentlichen Hostnamen in Cloudflare diesem HTTP-Ziel zu. Der Tunnel-Token kann diese Cloudflare-Einstellung nicht selbst ändern.</p>
    ${configured?`<form data-tunnel-domain-form class="tunnel-domain-form"><label>Öffentliche Titan-Adresse<input type="url" name="public_origin" required placeholder="https://nas.example.de" value="${esc(remote.public_origin||'')}" ${disabled}></label><button class="button primary" type="submit" ${disabled}>Adresse übernehmen und prüfen</button></form>`:''}
    <div class="tunnel-check-actions"><button class="button" type="button" data-remote-diagnose ${!remote.enabled||data.demo||setup.running?'disabled':''}>Verbindung prüfen</button><button class="button" type="button" data-remote-refresh ${data.demo?'disabled':''}>Status aktualisieren</button>${origin&&remote.enabled?`<a class="button" href="${esc(origin)}" target="_blank" rel="noopener noreferrer">Öffentlichen Zugang öffnen ↗</a>`:''}</div>
   </section>
   <details class="tunnel-advanced"><summary>Erweiterte Einstellungen und vorhandene Connectoren</summary><form data-remote-form><label class="checkbox-row"><input type="checkbox" name="enabled" ${remote.enabled?'checked':''} ${disabled}>Öffentlichen Titan-Zugang aktivieren</label><div class="web-access-fields"><label>Öffentliche Titan-Adresse<input name="public_origin" type="url" placeholder="https://nas.example.de" value="${esc(remote.public_origin||'')}" ${disabled}></label><label>Tunnel-Connector<select name="connector" ${disabled}><option value="">Cloudflared im Host-Netz · selbst verwaltet</option>${(data.connectors||[]).map(row=>`<option value="${esc(row.id)}" ${row.id===remote.connector?'selected':''}>${esc(row.name)}</option>`).join('')}</select></label></div><p class="hint">Die lokale NAS-Adresse bleibt erhalten. Vorhandene Connectoren können weiter verwendet werden.</p>${remote.service_url?`<p class="hint">Bisheriges lokales Ziel: <code>${esc(remote.service_url)}</code></p>`:''}<details><summary>Öffentliche App-Adressen (${Object.keys(remote.app_urls||{}).length})</summary><p class="hint">Hier gelten die ausdrücklich in Cloudflare eingerichteten HTTPS-Adressen der Apps.</p><div class="web-access-fields">${(data.apps||[]).map(row=>`<label>${esc(row.name)}<input type="url" data-remote-app="${esc(row.id)}" value="${esc(remote.app_urls?.[row.id]||'')}" placeholder="https://app.example.de" ${disabled}></label>`).join('')||'<p class="hint">Noch keine Apps installiert.</p>'}</div></details><div class="form-actions"><button class="button" type="submit" ${disabled}>Erweiterte Einstellungen speichern</button></div></form></details>
   <div data-remote-checks>${checks(data.diagnosis)}</div><p class="hint" role="status" data-remote-status></p><p class="notice warning" role="alert" data-remote-error hidden></p>
  </section>`;
 }
 function dispose(){cleanup?.();cleanup=null;}
 function mount(scope,ctx){
  dispose();let panel=scope.querySelector('[data-remote-access]');if(!panel)return;
  let data=JSON.parse(panel.dataset.config),alive=true,busy=false,progressBusy=false,revision=0,resumeTimer=null;
  const controller=new AbortController(),query=selector=>panel.querySelector(selector),view=scope.ownerDocument?.defaultView||globalThis;
  function locked(value){for(const node of panel.querySelectorAll('button,input,select'))node.disabled=value||!!data.demo||!!data.setup?.running;const refresh=query('[data-remote-refresh]');if(refresh)refresh.disabled=value||!!data.demo;const diagnose=query('[data-remote-diagnose]');if(diagnose)diagnose.disabled=value||!!data.demo||!!data.setup?.running||!data.remote?.enabled;}
  function replace(value){if(!alive)return;data=value;const holder=panel.parentElement;panel.outerHTML=render(value);panel=holder.querySelector('[data-remote-access]');}
  function showError(error,token=''){const message=String(error?.message||'Die Einrichtung konnte nicht abgeschlossen werden.');query('[data-remote-error]').hidden=false;query('[data-remote-error]').textContent=token?message.split(token).join('[Token ausgeblendet]'):message;query('[data-remote-status]').textContent='';}
  function scheduleResume(){if(resumeTimer!==null||!alive||busy||!data.setup?.running||data.demo)return;resumeTimer=view.setTimeout(async()=>{resumeTimer=null;try{const value=await ctx.api('/api/remote-access',undefined,{signal:controller.signal});if(alive&&!busy){replace(value);scheduleResume();}}catch(error){if(alive&&error.name!=='AbortError')showError(error);}},2000);}
  async function refreshProgress(){if(!alive||progressBusy)return;progressBusy=true;const serial=revision;try{const value=await ctx.api('/api/remote-access',undefined,{signal:controller.signal});if(alive&&busy&&serial===revision){data.setup=value.setup;const node=query('[data-tunnel-progress]');if(node)node.outerHTML=progress(value.setup);}}catch{}finally{progressBusy=false;}}
  async function connect(){
   if(busy||data.demo||data.setup?.running)return;const form=query('[data-tunnel-form]'),token=form.elements.token.value.trim(),origin=form.elements.public_origin.value.trim();if(!token)return;
   busy=true;locked(true);query('[data-remote-error]').hidden=true;form.elements.token.value='';query('[data-remote-status]').textContent='Tunnel wird eingerichtet …';
   try{const result=await ctx.api('/api/remote-access/tunnel',{token,public_origin:origin,expected_revision:data.revision},{signal:controller.signal});if(!alive)return;
    await refreshProgress();if(!alive)return;const wait=ctx.waitForJob||((accepted,options)=>view.TitanJobs.wait(ctx.api,accepted.job,options));await wait(result,{signal:controller.signal,onProgress:()=>void refreshProgress()});if(!alive)return;
    revision++;const value=await ctx.api('/api/remote-access',undefined,{signal:controller.signal});if(!alive)return;replace(value);ctx.toast?.(value.setup?.phase==='ready'?'Tunnel eingerichtet und öffentlicher Zugang geprüft.':value.setup?.phase==='needs_domain'?'Connector verbunden. Ergänze jetzt die öffentliche Adresse.':'Connector eingerichtet. Prüfe die öffentliche Route in Cloudflare.');
   }catch(error){if(alive&&error.name!=='AbortError'){revision++;try{const value=await ctx.api('/api/remote-access',undefined,{signal:controller.signal});if(alive)replace(value);}catch{}if(alive)showError(error,token);}}
   finally{busy=false;if(alive){locked(false);scheduleResume();}}
  }
  async function perform(kind){
   if(busy||data.demo||data.setup?.running&&kind!=='refresh')return;busy=true;query('[data-remote-error]').hidden=true;
   try{
    let body,path='/api/remote-access';if(kind==='diagnose'){body={};path+='/diagnose';}
    else if(kind==='domain'){const form=query('[data-tunnel-domain-form]');path+='/tunnel-address';body={public_origin:form.elements.public_origin.value.trim(),expected_revision:data.revision};}
    else if(kind==='save'){const form=query('[data-remote-form]');body={enabled:form.elements.enabled.checked,public_origin:form.elements.public_origin.value.trim(),connector:form.elements.connector.value,app_urls:{},expected_revision:data.revision};for(const input of panel.querySelectorAll('[data-remote-app]'))if(input.value.trim())body.app_urls[input.dataset.remoteApp]=input.value.trim();}
    query('[data-remote-status]').textContent=kind==='diagnose'?'Öffentliche Verbindung wird geprüft …':kind==='refresh'?'Status wird aktualisiert …':'Fernzugriff wird gespeichert …';locked(true);
    const value=await ctx.api(path,body,{signal:controller.signal});if(!alive)return;
    if(kind==='domain'){
     await refreshProgress();if(!alive)return;const wait=ctx.waitForJob||((accepted,options)=>view.TitanJobs.wait(ctx.api,accepted.job,options));await wait(value,{signal:controller.signal,onProgress:()=>void refreshProgress()});if(!alive)return;
     revision++;const fresh=await ctx.api('/api/remote-access',undefined,{signal:controller.signal});if(!alive)return;replace(fresh);ctx.toast?.(fresh.setup?.phase==='ready'?'Adresse gespeichert und öffentlicher Zugang geprüft.':'Adresse gespeichert. Prüfe die öffentliche Route in Cloudflare.');
    }else if(kind==='diagnose'){const fresh=await ctx.api('/api/remote-access',undefined,{signal:controller.signal});if(!alive)return;replace({...fresh,diagnosis:value});ctx.toast?.(value.message);}
    else{replace(value);ctx.toast?.(kind==='refresh'?'Status aktualisiert.':'Fernzugriff gespeichert.');}
   }catch(error){if(alive&&error.name!=='AbortError'){if(kind==='domain'){revision++;try{const fresh=await ctx.api('/api/remote-access',undefined,{signal:controller.signal});if(alive)replace(fresh);}catch{}}if(alive)showError(error);}}
   finally{busy=false;if(alive){locked(false);scheduleResume();}}
  }
  const submit=event=>{if(event.target.matches?.('[data-tunnel-form]')){event.preventDefault();void connect();}else if(event.target.matches?.('[data-tunnel-domain-form]')){event.preventDefault();void perform('domain');}else if(event.target.matches?.('[data-remote-form]')){event.preventDefault();void perform('save');}};
  const click=event=>{if(event.target.closest?.('[data-remote-diagnose]')&&!event.target.disabled){event.preventDefault();void perform('diagnose');}else if(event.target.closest?.('[data-remote-refresh]')&&!event.target.disabled){event.preventDefault();void perform('refresh');}};
  scope.addEventListener('submit',submit);scope.addEventListener('click',click);scheduleResume();cleanup=()=>{alive=false;revision++;controller.abort();if(resumeTimer!==null)view.clearTimeout(resumeTimer);scope.removeEventListener('submit',submit);scope.removeEventListener('click',click);};
 }
 return {render,checks,progress,mount,dispose};
});
