'use strict';
(function(root){
 function render(data,snapshots,system,{esc,bytes,pill,button,systemPanel}){
  const volumes=data.volumes||[],pools=data.pools||[],datasets=data.datasets||[],existing=data.existing_filesystems||[];
  const meter=(used,total)=>Number.isFinite(used)&&total>0?`<meter min="0" max="${total}" value="${Math.min(total,Math.max(0,used))}" aria-label="Belegter Speicher"></meter>`:'';
  const capacity=(used,total,free)=>`<div class="storage-capacity"><strong>${Number.isFinite(total)?bytes(total):'—'}</strong><span>${Number.isFinite(used)?bytes(used)+' belegt':'Belegung unbekannt'} · ${Number.isFinite(free)?bytes(free)+' frei':'Freier Platz unbekannt'}</span></div>${meter(used,total)}`;
  let result=`<div class="storage-workspace">${systemPanel?.(system.data,system.error)||''}`;
  if(volumes.length||pools.length)result+='<section class="panel"><div class="panel-heading"><h2>Deine Datenbereiche</h2><span class="hint">Nur eingerichteter Speicher</span></div><div class="storage-card-grid">'+volumes.map(v=>`<article class="storage-volume"><div class="panel-heading"><h3>${esc(v.name)}</h3>${pill(v.filesystem.toUpperCase(),'purple')}</div>${v.mounted?capacity(v.total-v.free,v.total,v.free):'<p class="notice warning">Nicht eingehängt · keine Messwerte verfügbar</p>'}<details><summary>Laufwerk und Einbindung</summary><p>${esc(v.disk)} · ${esc(v.mountpoint)}</p><small>UUID ${esc(v.uuid)}</small></details>${v.error?`<p class="notice warning">${esc(v.error)}</p>`:''}<div class="form-actions">${v.mounted?'<a class="button small" href="#shares">Freigabe erstellen</a>':button('Verbinden','volume-mount',`data-name="${esc(v.name)}" ${['format_failed','formatting'].includes(v.phase)?'disabled':''}`,'small')}</div></article>`).join('')+pools.map(p=>`<article class="storage-volume"><div class="panel-heading"><h3>${esc(p.name)}</h3>${pill('ZFS · '+p.health,p.health==='ONLINE'?'':'red')}</div>${capacity(p.used,p.size,p.free)}<div class="form-actions">${button('Speicherbereich hinzufügen','dataset-create',`data-parent="${esc(p.name)}"`,'small')}${button('Daten prüfen','scrub',`data-pool="${esc(p.name)}"`,'small')}</div></article>`).join('')+'</div></section>';
  else result+='<section class="panel storage-empty"><h2>Dein Systemlaufwerk ist bereit</h2><p>Für zusätzlichen Speicher ein leeres Laufwerk auswählen und einrichten. Erst danach erscheinen hier dessen Belegung und Freigabeoptionen.</p>'+button('Speicher einrichten','storage-create','','primary')+'</section>';
  if(datasets.length)result+='<section class="panel"><h2>Speicherbereiche im ZFS-Verbund</h2>'+datasets.map(d=>`<div class="storage-dataset"><strong>${esc(d.name)}</strong><span>${bytes(d.used)} belegt · ${bytes(d.available)} frei</span>${button('Wiederherstellungspunkt erstellen','snapshot-create',`data-dataset="${esc(d.name)}"`,'small')}</div>`).join('')+'</section>';
  if(snapshots.length)result+='<details class="panel"><summary>Wiederherstellungspunkte · '+snapshots.length+'</summary>'+snapshots.map(s=>`<p>${esc(s.name)} · ${bytes(s.used)}</p>`).join('')+'</details>';
  const managed=new Set([...volumes.map(v=>v.disk),system.data?.partition]);const other=existing.filter(x=>!managed.has(x.name));
  if(other.length)result+='<details class="panel"><summary>Weitere erkannte Dateisysteme · '+other.length+'</summary>'+other.map(x=>`<p>${esc(x.name)} · ${esc(x.fstype)} · ${bytes(x.size)}<br><small>${esc((x.mountpoints||[]).filter(Boolean).join(', ')||'Nicht verbunden')}</small></p>`).join('')+'</details>';
  result+='<details class="panel"><summary>Physische Laufwerke · '+(data.disks||[]).length+'</summary><div class="storage-card-grid">'+(data.disks||[]).map(d=>`<article class="storage-volume"><h3>${esc(d.model||'Laufwerk')}</h3><p>${esc(d.name)} · ${bytes(d.size)}</p><small>${esc(d.fstype||(d.children?.length?'Enthält Partitionen':'Leer'))}</small><div>${button('Laufwerkszustand','smart',`data-disk="${esc(d.name)}"`,'small')}</div></article>`).join('')+'</div></details>';
  if(pools.length)result+='<details class="panel"><summary>Technische ZFS-Diagnose</summary><pre class="code">'+esc(data.status)+'</pre></details>';
  return result+'</div>';
 }
 const ui={render};if(root)root.TitanStorage=ui;if(typeof module==='object')module.exports=ui;
})(typeof window==='undefined'?null:window);
