'use strict';
(function(root,factory){const ui=factory(root);if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanUnifiedUpdates=ui;})(typeof window==='undefined'?null:window,function(root){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const busy=new Set(['queued','web_starting','web_wait','system_queued','system_running']);
 function view(value={}){const state=value.state||'unchecked';return {title:state==='completed'?'Update abgeschlossen':state==='current'?'Alles aktuell':state==='ready'?'Update verfügbar':state==='restart_required'||state==='existing_restart'?'Bereit zum Neustart':busy.has(state)?'Titan wird aktualisiert':state==='failed'||state==='check_failed'||state==='blocked'?'Update benötigt Aufmerksamkeit':'Titan aktuell halten',label:state==='ready'?'Jetzt aktualisieren':state==='restart_required'||state==='existing_restart'?'Neu starten und abschließen':busy.has(state)?'Aktualisierung läuft …':'Nach Updates suchen',disabled:busy.has(state),action:state==='ready'?'install':state==='restart_required'||state==='existing_restart'?'reboot':'check'};}
 function panel(value={}){const v=view(value);return `<section class="panel unified-update-card" data-unified-updates><img class="update-product-icon" src="/app-icons/titan-updates.svg" alt="" width="80" height="80"><p class="eyebrow">TITAN UPDATE</p><h2 data-unified-title>${esc(v.title)}</h2><p data-unified-message role="status" aria-live="polite">${esc(value.message||'Titan prüft alle benötigten Updates gemeinsam.')}</p><p data-unified-target>${value.target?'Titan '+esc(value.target):''}</p><div class="form-actions"><button type="button" class="button primary" data-unified-primary ${v.disabled?'disabled':''}>${esc(v.label)}</button></div><p class="hint">Titan wählt die passenden Updates automatisch. Ein nötiger NAS-Neustart wird vorher bestätigt.</p><details data-unified-errors ${value.details?.length?'':'hidden'}><summary>Prüfdetails</summary><ul>${(value.details||[]).map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></details></section>`;}
 let cleanup=null;
 function dispose(){cleanup?.();cleanup=null;}
 function mount(node,{api,confirm,reboot,version,onJob,reload=()=>root.top.location.reload()}){
  dispose();const box=node.querySelector('[data-unified-updates]');if(!box)return;
  const button=box.querySelector('[data-unified-primary]');let alive=true,pending=false,state={},job=null,timer=null,refreshing=false;
  function paint(){const v=view(state);box.querySelector('[data-unified-title]').textContent=v.title;box.querySelector('[data-unified-message]').textContent=state.message||'Titan prüft alle benötigten Updates gemeinsam.';box.querySelector('[data-unified-target]').textContent=state.target?'Titan '+state.target:'';button.textContent=pending?'Bitte warten …':v.label;button.disabled=pending||v.disabled;const details=box.querySelector('[data-unified-errors]');details.hidden=!state.details?.length;details.querySelector('ul').innerHTML=(state.details||[]).map(x=>'<li>'+esc(x)+'</li>').join('');}
  async function refresh(){if(!alive||refreshing)return;refreshing=true;clearTimeout(timer);try{const value=await api('/api/updates/unified');if(!alive)return;state=value;if(value.current&&value.current!==version){dispose();reload();return;}if(job){const jobs=await api('/api/jobs');if(!alive)return;const result=jobs.find(x=>x.id===job);if(result&&['failed','completed'].includes(result.status)){pending=false;job=null;if(result.status==='failed')state={...state,state:'failed',message:result.result?.error||'Der Auftrag konnte nicht abgeschlossen werden.'};}}paint();}catch(error){if(alive)box.querySelector('[data-unified-message]').textContent='Verbindung wird wiederhergestellt. '+error.message;}finally{refreshing=false;if(alive)timer=setTimeout(refresh,3000);}}
  button.onclick=async()=>{if(pending)return;const action=view(state).action;if(action==='reboot'){await reboot();return;}if(action==='install'&&!await confirm(state))return;pending=true;paint();try{const result=await api('/api/updates/unified',action==='install'?{action,plan:state.id}:{action});if(!alive)return;job=result.job;onJob?.(job);await refresh();}catch(error){if(alive){pending=false;state={...state,state:'failed',message:error.message};paint();}}};
  cleanup=()=>{alive=false;clearTimeout(timer);button.onclick=null;};refresh();
 }
 return {view,panel,mount,dispose};
});
