'use strict';
(function(root){
 let current=null;const histories=new Map();
 const finite=value=>typeof value==='number'&&Number.isFinite(value)&&value>=0;
 function render(vm,{bytes,esc,compact=false}){
  const m=vm.metrics||{},number=value=>Number(value).toLocaleString('de-DE',{maximumFractionDigits:1}),running=vm.state==='running',rate=value=>running?(finite(value)?bytes(value)+'/s':'—'):'0 B/s';
  const cpu=!['running','paused','blocked','in shutdown','pmsuspended'].includes(vm.state)?'0 %':finite(m.cpu_percent)?number(m.cpu_percent)+' %':vm.state==='running'?'Messung läuft':'—';
  const active=['running','paused','blocked','in shutdown','pmsuspended'].includes(vm.state);
  const ram=active?m.memory_resident_bytes:0,ramLabel='RAM auf NAS (RSS)';
  const capacity=Object.hasOwn(vm,'disk_total_capacity_bytes')?vm.disk_total_capacity_bytes:(vm.virtual_size||Number(vm.disk_gb)*1024**3);
  const history=histories.get(vm.id)||[],line=history.map((value,index)=>`${index*100/Math.max(1,history.length-1)},${30-value*.3}`).join(' ');
  const resources=`<div><small>CPU live · ${esc(vm.cpus)} vCPU</small><strong>${cpu}</strong>${!compact&&history.length>1?`<svg class="vm-sparkline" viewBox="0 0 100 30" role="img" aria-label="CPU-Verlauf"><polyline points="${line}" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>`:''}</div><div><small title="Residenter Speicher des VM-Prozesses auf dem NAS, einschließlich Verwaltungsaufwand.">${ramLabel}</small><strong>${finite(ram)?bytes(ram):'—'}</strong>${compact?'':`<span>${active?bytes(Number(vm.memory_mb)*1024**2)+' Gast-RAM konfiguriert':'VM ausgeschaltet'}</span>`}</div>`;
  return `<div class="vm-live-grid${compact?' is-compact':''}">${resources}${compact?'':`<div><small>${Number(vm.disk_count)>1?'Laufwerke belegt':'Laufwerk belegt'}</small><strong>${finite(m.disk_allocated_bytes)?bytes(m.disk_allocated_bytes):'—'}</strong><span>${finite(capacity)?bytes(capacity):'—'} Kapazität${Number(vm.disk_count)>1?' · '+Number(vm.disk_count)+' Laufwerke':''}</span></div><div><small>Laufwerk lesen / schreiben</small><strong>${rate(m.disk_read_bps)} / ${rate(m.disk_write_bps)}</strong><span>Netzwerk ↓ ${rate(m.network_rx_bps)} ↑ ${rate(m.network_tx_bps)}</span></div>`}</div>`;
 }
 function record(vm){if(!['running','paused','blocked','in shutdown','pmsuspended'].includes(vm.state)){histories.delete(vm.id);return;}if(finite(vm.metrics?.cpu_percent)){const history=histories.get(vm.id)||[];history.push(vm.metrics.cpu_percent);histories.set(vm.id,history.slice(-30));}}
 function dispose(){current?.destroy();current=null;}
 function mount(main,{api,bytes,esc,onStateChange}){dispose();if(!main.querySelector('[data-vm-live],[data-vm-total-memory]'))return;let alive=true,busy=false;const doc=main.ownerDocument;
  async function refresh(){if(!alive||busy||doc.hidden)return;const targets=[...main.querySelectorAll('.vm-master-pane,[data-vm-total-memory]')];if(!targets.some(node=>!node.closest('[hidden]')))return;busy=true;try{const data=await api('/api/vms');if(!alive)return;const rows=[...main.querySelectorAll('[data-vm-live]')],ids=new Set(rows.map(node=>node.dataset.vmLive));if(onStateChange&&((data.vms||[]).length!==ids.size||(data.vms||[]).some(vm=>!ids.has(vm.id)))){onStateChange();return;}for(const vm of data.vms||[]){record(vm);for(const node of rows)if(node.dataset.vmLive===vm.id){if(node.dataset.vmState&&node.dataset.vmState!==vm.state){onStateChange?.();return;}node.dataset.vmState=vm.state;node.innerHTML=render(vm,{bytes,esc,compact:Object.hasOwn(node.dataset,'vmLiveCompact')});}}const active=(data.vms||[]).filter(vm=>['running','paused','blocked','in shutdown','pmsuspended'].includes(vm.state)),known=active.every(vm=>finite(vm.metrics?.memory_resident_bytes)),total=active.reduce((sum,vm)=>sum+(vm.metrics?.memory_resident_bytes||0),0);main.querySelectorAll('[data-vm-total-memory]').forEach(node=>node.textContent=known?bytes(total):'Nicht ermittelt');}catch{if(alive){for(const node of main.querySelectorAll('[data-vm-live]'))node.innerHTML='<p class="vm-live-unavailable">Messwerte momentan nicht erreichbar.</p>';main.querySelectorAll('[data-vm-total-memory]').forEach(node=>node.textContent='Nicht erreichbar');}}finally{busy=false;}}
  const timer=setInterval(refresh,5000);const visibility=()=>{if(!doc.hidden)refresh();};doc.addEventListener('visibilitychange',visibility);current={destroy(){alive=false;clearInterval(timer);doc.removeEventListener('visibilitychange',visibility);}};refresh();
 }
 const ui={render,record,mount,dispose};if(root)root.TitanVMLive=ui;if(typeof module==='object')module.exports=ui;
})(typeof window==='undefined'?null:window);
