(function(root){
 'use strict';
 const panel=()=>'<section class="panel web-update-panel" data-web-updates><header class="panel-heading"><h2>Weboberfläche</h2><div class="form-actions"><button type="button" class="button" data-web-check>Jetzt prüfen</button><button type="button" class="button primary" data-web-install hidden>Aktualisieren</button><button type="button" class="button" data-web-rollback hidden>Vorherige Webversion</button></div></header><p>Separates Update ohne NAS-Neustart. Apps und VMs laufen weiter; Uploads und Konsolen vorher abschließen.</p><p data-web-update-status role="status">Nach einer neuen Webversion suchen.</p></section>';
 function mount(node,{api,toast}){
  const box=node.querySelector('[data-web-updates]');if(!box||box.dataset.bound)return;box.dataset.bound='true';let offer=null,busy=false;
  const status=box.querySelector('[data-web-update-status]'),check=box.querySelector('[data-web-check]'),install=box.querySelector('[data-web-install]'),rollback=box.querySelector('[data-web-rollback]');
  function buttons(disabled){for(const button of [check,install,rollback])button.disabled=disabled;}
  check.onclick=async()=>{if(busy)return;busy=true;buttons(true);status.textContent='Signierte Veröffentlichungen werden geprüft …';try{offer=await api('/api/web-updates',{action:'check'});status.textContent=offer.demo?'Demo: Webupdates werden hier nur dargestellt.':offer.available?`Installiert: ${offer.current} · Verfügbar: ${offer.latest.version}`:`Weboberfläche ${offer.current} ist aktuell.`;install.hidden=!offer.available;rollback.hidden=!offer.previous;}catch(error){status.textContent=error.message;}finally{busy=false;buttons(false);}};
  async function change(action,version){if(busy||!version)return;busy=true;buttons(true);try{await api('/api/web-updates',{action,...(action==='release'?{version}:{})});status.textContent='Image wird geprüft und gewechselt. Die Oberfläche lädt nach erfolgreicher Prüfung neu.';const deadline=Date.now()+600000;const wait=async()=>{if(!box.isConnected)return;try{const value=await api('/api/health');if(value.version===version){root.top.location.reload();return;}}catch{}if(Date.now()<deadline)setTimeout(wait,3000);else{status.textContent='Wechsel nicht bestätigt. Bitte erneut prüfen; Details stehen im Systemprotokoll titan-web-switch.';busy=false;buttons(false);}};setTimeout(wait,3000);}catch(error){status.textContent=error.message;toast(error.message,true);busy=false;buttons(false);}}
  install.onclick=()=>change('release',offer?.latest?.version);rollback.onclick=()=>change('rollback',offer?.previous);
 }
 root.TitanWebUpdates={panel,mount};
})(window);
