'use strict';
// Each internal app keeps its own document, selection, forms and live connection.
(function(root,factory){const ui=factory();if(typeof module==='object'&&module.exports)module.exports=ui;if(root)root.TitanWorkspace=ui;})(typeof window==='undefined'?null:window,function(){
 const clamp=(n,low,high)=>Math.max(low,Math.min(high,Number.isFinite(n)?n:low));
 function geometry(value={},bounds={width:1200,height:800},index=0){
  const width=clamp(Number(value.width)||Math.min(980,bounds.width*.88),Math.min(320,bounds.width),bounds.width),height=clamp(Number(value.height)||Math.min(680,bounds.height*.88),Math.min(240,bounds.height),bounds.height);
  return {width,height,x:clamp(Number.isFinite(value.x)?value.x:24+index*28,0,Math.max(0,bounds.width-width)),y:clamp(Number.isFinite(value.y)?value.y:24+index*28,0,Math.max(0,bounds.height-height))};
 }
 function defaultGeometry(id,bounds={width:1200,height:800},index=0){
  const profiles={apps:[1360,840],docker:[1320,820],vms:[1320,820],files:[1260,800],storage:[1180,780],settings:[1100,740],security:[1020,700],users:[1100,740],terminal:[1180,760],updates:[1040,720]};
  const [width,height]=profiles[id]||[1120,760],margin=16;
  const availableWidth=Math.min(width,bounds.width-margin*2),availableHeight=Math.min(height,bounds.height-margin*2);
  return geometry({width:availableWidth,height:availableHeight,x:Math.max(margin,(bounds.width-availableWidth)/2)+index*18,y:Math.max(margin,(bounds.height-availableHeight)/2)+index*18},bounds,index);
 }
 function desktopPreferences(value={}){return {color_mode:['light','dark','system'].includes(value?.color_mode)?value.color_mode:'light',background_click:value?.background_click==='minimize'?'minimize':'none',dock_auto_hide:value?.dock_auto_hide===true,transparency:Number.isInteger(value?.transparency)&&value.transparency>=0&&value.transparency<=100?value.transparency:40};}
 function preferences(value,allowed){
  const safe=value&&typeof value==='object'?value:{};
  const layouts={};for(const id of allowed)if(safe.layouts?.[id]&&typeof safe.layouts[id]==='object')layouts[id]={geometry:safe.layouts[id].geometry||{},maximized:safe.layouts[id].maximized===true};
  return {dock_version:safe.dock_version===1?1:0,desktop:desktopPreferences(safe.desktop),active:allowed.includes(safe.active)?safe.active:null,layouts,theme:['fjord','sky','dusk','forest'].includes(safe.theme)?safe.theme:'fjord',pins:[...new Set(Array.isArray(safe.pins)?safe.pins:[])].filter(id=>allowed.includes(id)),windows:(Array.isArray(safe.windows)?safe.windows:[]).filter(item=>item&&allowed.includes(item.id)).filter((item,i,all)=>all.findIndex(row=>row.id===item.id)===i).slice(0,16).map(item=>({id:item.id,minimized:item.minimized===true,maximized:item.maximized===true,geometry:item.geometry||{}}))};
 }
 let current=null;
 function mount({doc=document,user,tools,icon,esc,api,toast,confirm,logout}={}){
  current?.destroy();const shell=doc.querySelector('#shell'),workspace=doc.querySelector('.workspace'),main=doc.querySelector('#main');
  const win=doc.defaultView,allowed=tools.map(t=>t[0]),titles=new Map(tools.map(t=>[t[0],t[1]]));
  const key='titan-desktop-v2:'+encodeURIComponent(user.name);let storage;try{storage=win.localStorage;}catch{}
  let saved;try{saved=JSON.parse(storage?.getItem(key)||'{}');}catch{}let prefs=preferences(saved,allowed),active=null,z=10,alive=true,gesture=null,pendingFrame=null;
  let shortcuts=null;let restoring=true;const frames=new Map(),closingFrames=new Set();shell.dataset.desktop='true';shell.dataset.wallpaper=prefs.theme;applyAppearance();
  const layer=doc.createElement('div');layer.className='desktop-window-layer';layer.setAttribute('aria-label','Geöffnete Anwendungen');workspace.append(layer);
  const tasks=doc.querySelector('#desktop-tasks'),dock=doc.createElement('nav');dock.className='desktop-dock';dock.setAttribute('aria-label','Desktop-Dock');
  const dockNodes=[doc.querySelector('#show-desktop'),doc.querySelector('#main-menu'),tasks].filter(Boolean),dockOrigins=dockNodes.map(node=>({node,parent:node.parentElement,next:node.nextSibling}));
  dockNodes.forEach(node=>dock.append(node));workspace.append(dock);
  const dockReveal=doc.createElement('button');dockReveal.type='button';dockReveal.className='desktop-dock-reveal';dockReveal.textContent='Dock anzeigen';dockReveal.setAttribute('aria-label','Dock anzeigen');dockReveal.onclick=()=>dock.querySelector('button,a')?.focus();workspace.append(dockReveal);
  if(!prefs.dock_version&&!prefs.pins.length)prefs.pins=['files','apps','vms','settings','resources'].filter(id=>allowed.includes(id));prefs.dock_version=1;
  let observer=typeof win.ResizeObserver==='function'?new win.ResizeObserver(()=>resize()):null;observer?.observe(doc.querySelector('.topbar'));observer?.observe(dock);const menu=doc.createElement('dialog');menu.className='desktop-menu-dialog';menu.setAttribute('aria-label','Hauptmenü');doc.body.append(menu);
  menu.addEventListener('click',event=>{if(event.target!==menu)return;const rect=menu.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom){menu.close();desktop();}});
  menu.addEventListener('cancel',event=>{event.preventDefault();menu.close();desktop();});
  menu.addEventListener('close',()=>doc.querySelector('#main-menu')?.setAttribute('aria-expanded','false'));
  const account=doc.createElement('div');account.className='desktop-account shortcut-context';account.hidden=true;account.setAttribute('role','dialog');account.setAttribute('aria-label','Desktop und Konto');account.innerHTML=`<header class="desktop-account-header"><span class="desktop-account-avatar" aria-hidden="true">${esc(user.name.slice(0,1).toUpperCase())}</span><div><strong>${esc(user.name)}</strong><small>Dein Desktop</small></div></header>${controls()}<div class="desktop-account-actions"><button data-widgets-picker>＋ Widgets hinzufügen</button><button data-action="profile-menu">Persönliche Einstellungen</button></div><div class="desktop-account-actions">${user.role==='admin'?'<button data-action="system-reboot">Neu starten</button><button data-action="system-shutdown">Herunterfahren</button>':''}<button data-action="logout">Abmelden</button></div>`;doc.body.append(account);
  function controls(){const p=prefs.desktop,disabled=!shortcuts||shortcuts.desktopWritable?.()===false?' disabled':'';return `<section class="desktop-preferences" data-desktop-preferences role="group" aria-label="Desktop-Einstellungen"><strong class="desktop-preferences-title">Darstellung</strong><div class="desktop-mode-choices" role="group" aria-label="Darstellungsmodus">${[['light','☀','Hell'],['dark','☾','Dunkel'],['system','◐','Auto']].map(([value,glyph,label])=>`<button type="button" data-desktop-color-choice="${value}" aria-pressed="${p.color_mode===value}"${disabled}><span aria-hidden="true">${glyph}</span>${label}</button>`).join('')}</div><label class="desktop-transparency-label">Transparenz <output data-desktop-transparency-output>${p.transparency}%</output><input type="range" min="0" max="100" step="1" value="${p.transparency}" data-desktop-transparency aria-label="Desktop-Transparenz" aria-valuetext="${p.transparency} Prozent"${disabled}></label><div class="desktop-range-labels" aria-hidden="true"><span>Deckend</span><span>Transparent</span></div><label>Klick auf freien Desktop<select data-desktop-background-click${disabled}><option value="none" ${p.background_click==='none'?'selected':''}>Nichts</option><option value="minimize" ${p.background_click==='minimize'?'selected':''}>Alle Fenster minimieren</option></select></label><label class="desktop-dock-choice"><input type="checkbox" data-desktop-dock-auto-hide ${p.dock_auto_hide?'checked':''}${disabled}>Dock bei maximierten Fenstern ausblenden</label><p class="hint">Wird für dein Konto gespeichert.</p></section>`;}
  function applyAppearance(){shell.dataset.dockAutoHide=String(prefs.desktop.dock_auto_hide);win.TitanTheme?.set(prefs.desktop);doc.documentElement?.style.setProperty('--desktop-glass-opacity',String(1-prefs.desktop.transparency/100));}
  function syncControls(){const disabled=!shortcuts||shortcuts.desktopWritable?.()===false;doc.querySelectorAll('[data-desktop-dock-auto-hide]').forEach(node=>{node.disabled=disabled;node.checked=prefs.desktop.dock_auto_hide;});doc.querySelectorAll('[data-desktop-color-choice]').forEach(node=>{node.disabled=disabled;node.setAttribute('aria-pressed',String(node.dataset.desktopColorChoice===prefs.desktop.color_mode));});doc.querySelectorAll('[data-desktop-color-mode]').forEach(node=>{node.disabled=disabled;node.value=prefs.desktop.color_mode;});doc.querySelectorAll('[data-desktop-transparency]').forEach(node=>{node.disabled=disabled;node.value=String(prefs.desktop.transparency);node.setAttribute('aria-valuetext',prefs.desktop.transparency+' Prozent');});doc.querySelectorAll('[data-desktop-transparency-output]').forEach(node=>node.textContent=prefs.desktop.transparency+'%');doc.querySelectorAll('[data-desktop-background-click]').forEach(node=>{node.disabled=disabled;node.value=prefs.desktop.background_click;});}
  function updateDesktop(value){if(!alive||!shortcuts||shortcuts.desktopWritable?.()===false)return;prefs.desktop=desktopPreferences({...prefs.desktop,...value});applyAppearance();syncControls();save();shortcuts.setDesktop?.(prefs.desktop);}
  function appearanceInput(event){const target=event.target;if(event.type==='change'&&target.matches('[data-desktop-dock-auto-hide]')){updateDesktop({dock_auto_hide:target.checked});resize();}if(event.type==='change'&&target.matches('[data-desktop-color-mode]'))updateDesktop({color_mode:target.value});if(target.matches('[data-desktop-transparency]'))updateDesktop({transparency:Number(target.value)});if(event.type==='change'&&target.matches('[data-desktop-background-click]'))updateDesktop({background_click:target.value});}
  function closeAccount(){account.hidden=true;doc.querySelector('#profile')?.setAttribute('aria-expanded','false');}
  function showPreferences(){if(menu.open)menu.close();account.hidden=false;doc.querySelector('#profile')?.setAttribute('aria-expanded','true');account.querySelector('[data-desktop-color-choice]')?.focus();}
  function bounds(){layer.style.top=doc.querySelector('.topbar').getBoundingClientRect().height+'px';return win.matchMedia('(max-width: 760px)').matches?{width:1200,height:800}:{width:layer.clientWidth,height:layer.clientHeight};}
  function save(){if(restoring)return;prefs.active=active;for(const item of frames.values())prefs.layouts[item.id]={geometry:item.geometry,maximized:item.maximized};prefs.windows=[...frames.values()].map(item=>({id:item.id,minimized:item.minimized,maximized:item.maximized,geometry:item.geometry}));try{storage?.setItem(key,JSON.stringify(prefs));}catch{}}
  function place(item){item.geometry=geometry(item.geometry,bounds());const g=item.geometry;item.node.classList.toggle('desktop-maximized',item.maximized);for(const [field,value]of Object.entries(g))item.node.style[field==='x'?'left':field==='y'?'top':field]=value+'px';item.node.hidden=item.minimized;item.node.inert=item.minimized;item.node.setAttribute('aria-hidden',String(item.minimized));const maximize=item.node.querySelector('[data-frame-maximize]');maximize.setAttribute('aria-pressed',String(item.maximized));maximize.setAttribute('aria-label',titles.get(item.id)+': '+(item.maximized?'Wiederherstellen':'Maximieren'));maximize.setAttribute('title',item.maximized?'Wiederherstellen':'Maximieren');maximize.innerHTML=item.maximized?'<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M7 3h10v10M3 7h10v10H3Z"/></svg>':'<svg viewBox="0 0 20 20" aria-hidden="true"><rect x="4" y="4" width="12" height="12" rx="1"/></svg>';}
  function cancelAnimation(item){if(item.animationTimer!==undefined){(win.clearTimeout||globalThis.clearTimeout).call(win,item.animationTimer);delete item.animationTimer;}const animation=item.animation;item.animation=null;animation?.cancel();}
  function animate(item,keyframes,{duration=300,done}={}){
   cancelAnimation(item);if(!item.node.animate||doc.hidden||win.matchMedia('(prefers-reduced-motion: reduce)').matches||restoring){done?.();return;}
   const animation=item.node.animate(keyframes,{duration,easing:'cubic-bezier(.2,.75,.25,1)',fill:'both'});item.animation=animation;
   // Background documents can leave finished pending. Effects never own app state.
   const finish=()=>{if(item.animation!==animation)return;cancelAnimation(item);if(alive)done?.();};
   item.animationTimer=(win.setTimeout||globalThis.setTimeout).call(win,finish,duration+80);animation.finished.then(finish,finish);
  }
  function dockTransform(item){const rect=item.node.getBoundingClientRect(),anchor=(tasks.querySelector(`[data-desktop-task="${item.id}"]`)||dock).getBoundingClientRect();return `translate(${anchor.left+anchor.width/2-rect.left-rect.width/2}px,${anchor.top+anchor.height/2-rect.top-rect.height/2}px) scale(.12)`;}
  function minimize(item){item.minimized=true;item.node.inert=true;item.node.setAttribute('aria-hidden','true');if(!item.node.animate||win.matchMedia('(prefers-reduced-motion: reduce)').matches){place(item);return;}animate(item,[{opacity:1,transform:'none'},{opacity:0,transform:dockTransform(item)}],{duration:260,done:()=>{if(item.minimized)item.node.hidden=true;}});}
  function taskbar(){const focusedTask=doc.activeElement?.closest?.('[data-desktop-task]')?.dataset.desktopTask;tasks.innerHTML=[...new Set([...prefs.pins,...frames.keys()])].map(id=>{const item=frames.get(id),pressed=id===active&&!item?.minimized;return `<button class="desktop-task ${item?'is-open':''} ${pressed?'is-active':''}" data-desktop-task="${id}" aria-label="${esc(titles.get(id))}${item?.minimized?' · minimiert':''}" aria-pressed="${pressed}" title="${esc(titles.get(id))}${item?.minimized?' · minimiert':''}">${win.TitanArtwork?.tool(id)||icon(id)}<span>${esc(titles.get(id))}</span></button>`;}).join('');tasks.querySelector('[aria-pressed="true"]')?.scrollIntoView?.({block:'nearest',inline:'nearest'});if(focusedTask)tasks.querySelector(`[data-desktop-task="${focusedTask}"]`)?.focus({preventScroll:true});shell.dataset.activeApp=active||'';for(const item of frames.values())item.node.dataset.mobileActive=String(item.id===active&&!item.minimized);}
  function focus(id){const item=frames.get(id);if(!item||item.closing)return;const returning=item.minimized;cancelAnimation(item);item.minimized=false;active=id;item.node.style.zIndex=String(++z);place(item);taskbar();if(returning)animate(item,[{opacity:0,transform:dockTransform(item)},{opacity:1,transform:'none'}],{duration:320});save();}
  function desktop(){for(const item of frames.values())if(!item.minimized)minimize(item);active=null;taskbar();save();win.history.replaceState(null,'','#dashboard');doc.querySelector('#show-desktop')?.focus();}
  function route(hash){let id=String(hash||'').replace(/^#/,'').split('?')[0];if(id==='dashboard'||!id){desktop();return;}if(id==='control')id='settings';if(!allowed.includes(id))return;
   const params=new URLSearchParams(String(hash).split('?')[1]||''),app=params.get('app'),section=params.get('section');const appId=app&&/^[a-zA-Z0-9_-]{1,64}$/.test(app)?app:null;const vm=params.get('vm'),vmId=id==='vms'&&/^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(vm||'')?vm:null;const suffix=vmId?'?vm='+vmId+'&tab=console':appId?'?app='+encodeURIComponent(appId):section&&/^[a-z-]{1,40}$/.test(section)?'?section='+encodeURIComponent(section):'';
   menu.close();if(frames.has(id)){focus(id);if(section&&id==='settings')sendWhenReady(frames.get(id),{type:'titan-navigate',hash:'#settings'+suffix});if(appId)sendWhenReady(frames.get(id),{type:'titan-manage-app',id:appId});if(vmId)sendWhenReady(frames.get(id),{type:'titan-open-vm',id:vmId,tab:'console'});return;}
   const old=prefs.windows.find(item=>item.id===id)||prefs.layouts[id];const item={id,ready:false,pendingRoute:null,routeSerial:0,minimized:false,maximized:old?.maximized||false,geometry:old?.geometry?geometry(old.geometry,bounds(),frames.size):defaultGeometry(id,bounds(),frames.size)};
   const node=doc.createElement('section');node.className='desktop-window';node.setAttribute('aria-label',titles.get(id));node.dataset.frame=id;
   node.innerHTML=`<header class="desktop-window-titlebar"><div class="desktop-window-caption">${win.TitanArtwork?.tool(id)||icon(id)}<strong>${esc(titles.get(id))}</strong></div><div class="desktop-window-controls"><button data-frame-pin title="Im Dock anheften" aria-label="${esc(titles.get(id))}: Anheften" aria-pressed="${prefs.pins.includes(id)}"><svg viewBox="0 0 20 20" aria-hidden="true"><path d="m10 2 2.3 4.7 5.2.8-3.8 3.7.9 5.2-4.6-2.5-4.6 2.5.9-5.2L2.5 7.5l5.2-.8Z"/></svg></button><button data-frame-minimize title="Minimieren" aria-label="${esc(titles.get(id))}: Minimieren"><svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4 11h12"/></svg></button><button data-frame-maximize aria-pressed="false" aria-label="${esc(titles.get(id))}: Maximieren"></button><button data-frame-close title="Schließen" aria-label="${esc(titles.get(id))}: Schließen"><svg viewBox="0 0 20 20" aria-hidden="true"><path d="m5 5 10 10M15 5 5 15"/></svg></button></div></header><iframe allow="fullscreen" class="desktop-app-frame" title="${esc(titles.get(id))}" src="/?desktop-app=1#${id}${suffix}"></iframe><button class="desktop-window-resize" aria-label="Fenstergröße ändern: Pfeiltasten verwenden" title="Größe ändern" data-frame-resize>◢</button>`;
   item.node=node;frames.set(id,item);const appFrame=node.querySelector('iframe');appFrame.addEventListener('load',()=>{item.ready=false;appFrame.contentWindow.postMessage({type:'titan-request-app-ready'},win.location.origin);});layer.append(node);place(item);focus(id);animate(item,[{opacity:0,transform:'translateY(22px) scale(.96)'},{opacity:1,transform:'none'}],{duration:340});
   node.addEventListener('pointerdown',()=>{if(active!==id)focus(id);});
   node.querySelector('[data-frame-pin]').onclick=e=>{prefs.pins=prefs.pins.includes(id)?prefs.pins.filter(key=>key!==id):[...prefs.pins,id];e.currentTarget.setAttribute('aria-pressed',String(prefs.pins.includes(id)));taskbar();save();};
   node.querySelector('[data-frame-minimize]').onclick=()=>{minimize(item);active=null;taskbar();tasks.querySelector(`[data-desktop-task="${id}"]`)?.focus({preventScroll:true});save();};
   node.querySelector('[data-frame-maximize]').onclick=()=>{cancelAnimation(item);const before=node.getBoundingClientRect();item.maximized=!item.maximized;place(item);const after=node.getBoundingClientRect();if(before.width&&after.width&&before.height&&after.height)animate(item,[{transformOrigin:'top left',transform:`translate(${before.left-after.left}px,${before.top-after.top}px) scale(${before.width/after.width},${before.height/after.height})`},{transformOrigin:'top left',transform:'none'}],{duration:300});save();};
   node.querySelector('[data-frame-close]').onclick=async()=>{if(item.closing||item.confirmingClose)return;item.confirmingClose=true;try{const child=node.querySelector('iframe').contentWindow;let dirty=false;try{dirty=child.titanHasUnsavedWork?.()===true;}catch{}if(dirty&&!await confirm('Offene Eingaben oder eine Konsolensitzung verwerfen und das Fenster schließen?'))return;if(!alive||frames.get(id)!==item)return;item.closing=true;if(gesture?.item===item)end();prefs.layouts[id]={geometry:item.geometry,maximized:item.maximized};frames.delete(id);closingFrames.add(item);if(active===id)active=null;node.inert=true;node.style.pointerEvents='none';node.setAttribute('aria-hidden','true');taskbar();save();doc.querySelector('#show-desktop')?.focus();animate(item,[{opacity:1,transform:'none'},{opacity:0,transform:'translateY(12px) scale(.97)'}],{duration:170,done:()=>{node.remove();closingFrames.delete(item);}});}finally{item.confirmingClose=false;}};
   const bar=node.querySelector('header'),grip=node.querySelector('[data-frame-resize]');bar.setAttribute('tabindex','0');bar.setAttribute('aria-label',titles.get(id)+': Fenster mit Pfeiltasten verschieben');bar.addEventListener('keydown',e=>{if(e.target!==bar||item.maximized||win.matchMedia('(max-width:760px)').matches||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();item.geometry.x+=e.key==='ArrowRight'?24:e.key==='ArrowLeft'?-24:0;item.geometry.y+=e.key==='ArrowDown'?24:e.key==='ArrowUp'?-24:0;place(item);save();});
   function start(event,resize){if(win.matchMedia('(max-width: 760px)').matches||item.maximized||(!resize&&event.target.closest('button')))return;if(event.button!==0)return;event.preventDefault();focus(id);gesture={item,resize,startX:event.clientX,startY:event.clientY,geometry:{...item.geometry},target:event.currentTarget,id:event.pointerId};shell.classList.add('desktop-moving');event.currentTarget.setPointerCapture(event.pointerId);}
   bar.addEventListener('pointerdown',e=>start(e,false));grip.addEventListener('pointerdown',e=>start(e,true));bar.addEventListener('dblclick',e=>{if(!e.target.closest('button'))node.querySelector('[data-frame-maximize]').click();});
   grip.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();item.geometry.width+=e.key==='ArrowRight'?24:e.key==='ArrowLeft'?-24:0;item.geometry.height+=e.key==='ArrowDown'?24:e.key==='ArrowUp'?-24:0;place(item);save();});
   return item;
  }
  function menuCard(key,name,detail,glyph){return `<div class="desktop-menu-entry" data-search="${esc((name+' '+detail).toLowerCase())}"><button class="desktop-menu-app" data-menu-launch="${esc(key)}"><span class="desktop-app-icon" data-app="${esc(glyph)}">${key.startsWith('app:')?(win.TitanArtwork?.render(key.slice(4))||icon('apps')):(win.TitanArtwork?.tool(glyph)||icon(glyph))}</span><strong>${esc(name)}</strong></button><button class="desktop-menu-more" data-menu-context="${esc(key)}" aria-haspopup="menu" aria-label="Schnellaktionen für ${esc(name)}" title="Schnellaktionen">···</button></div>`;}
  async function openMenu(){closeAccount();menu.innerHTML=`<div class="desktop-menu-heading"><div><h2>Apps & Werkzeuge</h2></div><div class="desktop-menu-tools"><button class="button" data-widgets-picker>＋ Widgets hinzufügen</button><button class="button" data-desktop-settings>Darstellung</button><button class="button desktop-menu-close" data-menu-close aria-label="Hauptmenü schließen">×</button></div></div><label class="desktop-search"><span class="sr-only">Anwendung suchen</span><input type="search" placeholder="Dateien, Docker, Einstellungen …" data-desktop-search></label>${[['Dateien & Apps',['files','apps','docker','vms']],['System',['settings','storage','resources','monitoring']],['Verwaltung',['backups','security','groups','services','terminal','logs']]].map(([label,ids])=>{const rows=ids.map(id=>tools.find(item=>item[0]===id)).filter(Boolean);return rows.length?`<section class="desktop-menu-section" data-menu-section><h3>${label}</h3><div class="desktop-menu-grid">${rows.map(([id,name,detail])=>menuCard('tool:'+id,name,detail,id)).join('')}</div></section>`:'';}).join('')}<p data-menu-empty hidden>Keine passende Anwendung gefunden.</p><section class="desktop-installed" data-menu-section><h3>Installierte Apps</h3><div data-installed-apps>Apps werden geladen …</div></section><details class="desktop-appearance"><summary>Desktop-Hintergrund</summary><div>${[['fjord','Fjord'],['sky','Küste'],['dusk','Abendsee'],['forest','Morgental']].map(([id,label])=>`<button class="button" data-wallpaper="${id}" aria-pressed="${prefs.theme===id}">${label}</button>`).join('')}</div></details>`;menu.showModal();doc.querySelector('#main-menu')?.setAttribute('aria-expanded','true');menu.querySelector('input').focus();
   if(user.role!=='admin'&&!user.permissions?.apps?.allowed){menu.querySelector('.desktop-installed').hidden=true;return;}
   await shortcuts?.refreshApps();if(!alive||!menu.open)return;
   menu.querySelector('[data-installed-apps]').innerHTML=(shortcuts?.entries()||[]).filter(([key])=>key.startsWith('app:')).map(([key,item])=>menuCard(key,item.name,item.detail,'apps')).join('')||'<p>Noch keine Apps installiert.</p>';search({target:menu.querySelector('[data-desktop-search]')});
  }
  function click(e){
   const source=e.target,surface=doc.querySelector('#desktop-surface'),background=[surface,main,workspace,layer].includes(source)||source.matches?.('.desktop-watermark');
   if(background&&!e.defaultPrevented&&(e.button===undefined||e.button===0)&&prefs.desktop.background_click==='minimize'&&shortcuts?.backgroundClickAllowed?.()!==false){closeAccount();desktop();return;}
   if(!account.hidden&&!account.contains(source)&&!source.closest('#profile'))closeAccount();
   const target=source.closest('button,a');if(!target)return;
   if(target.id==='profile'){account.hidden=!account.hidden;target.setAttribute('aria-expanded',String(!account.hidden));if(!account.hidden)account.querySelector('button')?.focus();return;}
   if(target.dataset.desktopColorChoice){e.preventDefault?.();updateDesktop({color_mode:target.dataset.desktopColorChoice});return;}
   if(target.hasAttribute('data-desktop-settings')){e.preventDefault?.();showPreferences();return;}
   if(target.hasAttribute('data-widgets-picker')){if(menu.open)menu.close();closeAccount();return;}
   if(!account.hidden)closeAccount();
   if(target.dataset.menuAdd){if(shortcuts?.add(target.dataset.menuAdd)){target.disabled=true;target.textContent='Auf dem Desktop';}return;}
   if(target.dataset.menuLaunch){const key=target.dataset.menuLaunch;menu.close();if(key.startsWith('app:'))shortcuts?.open(key);else route('#'+key.slice(5));return;}
   if(target.id==='main-menu'){e.preventDefault();void openMenu();return;}
   if(target.id==='show-desktop'||target.classList.contains('desktop-brand')){e.preventDefault();desktop();return;}
   if(target.dataset.desktopOpen){route('#'+target.dataset.desktopOpen+(target.dataset.appId?'?app='+encodeURIComponent(target.dataset.appId):''));win.history.replaceState(null,'','#'+target.dataset.desktopOpen);return;}
   if(target.dataset.desktopTask){const item=frames.get(target.dataset.desktopTask);if(item&&!item.minimized&&active===item.id){minimize(item);active=null;taskbar();save();}else {win.history.replaceState(null,'','#'+target.dataset.desktopTask);route('#'+target.dataset.desktopTask);}return;}
   if(target.hasAttribute('data-menu-close'))menu.close();
   if(target.dataset.wallpaper){prefs.theme=target.dataset.wallpaper;shell.dataset.wallpaper=prefs.theme;menu.querySelectorAll('[data-wallpaper]').forEach(b=>b.setAttribute('aria-pressed',String(b===target)));save();}
   if(target.matches('a[href^="#"]')&&!target.classList.contains('skip-link')&&!target.dataset.action){e.preventDefault();const hash=target.getAttribute('href');win.history.replaceState(null,'',hash);route(hash);}
  }
  function search(e){if(!e.target.matches('[data-desktop-search]'))return;const words=e.target.value.toLowerCase().trim().split(/\s+/);let count=0;menu.querySelectorAll('[data-search]').forEach(item=>{item.hidden=!words.every(word=>item.dataset.search.includes(word));if(!item.hidden)count++;});menu.querySelectorAll('[data-menu-section]').forEach(section=>{section.hidden=![...section.querySelectorAll('[data-search]')].some(item=>!item.hidden);});menu.querySelector('[data-menu-empty]').hidden=count>0;}
  function move(e){if(!gesture||e.pointerId!==gesture.id)return;const g=gesture,dx=e.clientX-g.startX,dy=e.clientY-g.startY;g.item.geometry={...g.geometry,...(g.resize?{width:g.geometry.width+dx,height:g.geometry.height+dy}:{x:g.geometry.x+dx,y:g.geometry.y+dy})};if(!win.requestAnimationFrame){place(g.item);return;}if(pendingFrame===null)pendingFrame=win.requestAnimationFrame(()=>{pendingFrame=null;if(gesture===g&&alive)place(g.item);});}
  function end(){if(!gesture)return;const g=gesture;if(pendingFrame!==null){win.cancelAnimationFrame?.(pendingFrame);pendingFrame=null;}place(g.item);gesture=null;shell.classList.remove('desktop-moving');save();}
  function resize(){bounds();for(const item of frames.values())place(item);}
  function postRoute(item){item.node.querySelector('iframe').contentWindow.postMessage(item.pendingRoute,win.location.origin);}
  function sendWhenReady(item,payload){item.pendingRoute={...payload,requestId:++item.routeSerial};if(item.ready)postRoute(item);}
  function message(e){if(e.origin!==win.location.origin)return;const item=[...frames.values()].find(item=>item.node.querySelector('iframe').contentWindow===e.source);if(!item)return;if(e.data?.type==='titan-pin-shortcut'&&typeof e.data.key==='string'){const key=e.data.key;Promise.resolve(key.startsWith('vm:')?shortcuts?.refreshVMs():null).then(()=>{if(shortcuts?.add(key))toast('Verknüpfung zum Desktop hinzugefügt.');else if(shortcuts?.contains(key))toast('Verknüpfung liegt bereits auf dem Desktop.');});return;}if(e.data?.type==='titan-app-route-accepted'){if(item.pendingRoute?.requestId===e.data.requestId)item.pendingRoute=null;return;}if(e.data?.type==='titan-app-ready'){item.ready=true;if(item.pendingRoute)postRoute(item);return;}if(e.data?.type==='titan-open'&&typeof e.data.hash==='string')route(e.data.hash);if(e.data?.type==='titan-focus'&&active!==item.id)focus(item.id);if(e.data?.type==='titan-logout')logout();if(e.data?.type==='titan-apps-changed'){void shortcuts?.refreshApps();const store=frames.get('apps');if(store&&store!==item)store.node.querySelector('iframe').contentWindow.postMessage({type:'titan-apps-invalidated'},win.location.origin);}}
  function keys(e){if(e.key==='Escape'&&!account.hidden){closeAccount();doc.querySelector('#profile')?.focus();}if(e.key==='Escape'&&menu.open){e.preventDefault();menu.close();desktop();}if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();void openMenu();}}
  doc.addEventListener('titan-desktop-preferences',showPreferences);doc.addEventListener('click',click,true);doc.addEventListener('input',search);doc.addEventListener('input',appearanceInput);doc.addEventListener('change',appearanceInput);doc.addEventListener('pointermove',move);doc.addEventListener('pointerup',end);doc.addEventListener('pointercancel',end);doc.addEventListener('keydown',keys);win.addEventListener('resize',resize);win.addEventListener('message',message);
  for(const old of prefs.windows.slice()){route('#'+old.id);const item=frames.get(old.id);item.minimized=old.minimized;place(item);}restoring=false;const resumed=prefs.active;active=null;if(resumed&&frames.has(resumed)&&!frames.get(resumed).minimized)focus(resumed);taskbar();
  current={route,desktop,openMenu,controls,desktopPreferences:()=>({...prefs.desktop}),setDesktopPreferences:updateDesktop,setShortcuts(value){shortcuts=value;if(value?.desktop&&value.desktopWritable?.()!==false){prefs.desktop=desktopPreferences(value.desktop());applyAppearance();save();}syncControls();},destroy(){alive=false;observer?.disconnect();end();for(const item of [...frames.values(),...closingFrames]){cancelAnimation(item);item.node.remove();}frames.clear();closingFrames.clear();layer.remove();menu.remove();account.remove();tasks.innerHTML='';for(const original of dockOrigins){if(original.parent){if(original.next?.parentElement===original.parent)original.parent.insertBefore(original.node,original.next);else original.parent.append(original.node);}}dockReveal.remove();dock.remove();delete shell.dataset.dockAutoHide;delete shell.dataset.desktop;doc.documentElement?.style.removeProperty('--desktop-glass-opacity');doc.removeEventListener('titan-desktop-preferences',showPreferences);doc.removeEventListener('click',click,true);doc.removeEventListener('input',search);doc.removeEventListener('input',appearanceInput);doc.removeEventListener('change',appearanceInput);doc.removeEventListener('pointermove',move);doc.removeEventListener('pointerup',end);doc.removeEventListener('pointercancel',end);doc.removeEventListener('keydown',keys);win.removeEventListener('resize',resize);win.removeEventListener('message',message);}};return current;
 }
 return {geometry,defaultGeometry,preferences,desktopPreferences,mount,dispose(){current?.destroy();current=null;}};
});
