'use strict';
const assert=require('node:assert/strict');
const backup=require('../titan/web/backup_center.js');
const settings={target:'/mnt/archive',apps:['db'],app_data:[],shares:[],include_config:false,retention:7,window_day:0,window_hour:3};
const data={available_apps:[{id:'db',name:'Database <script>'}],items:[{id:'b-one',type:'bundle',apps:['db'],app_data:['db'],shares:[],bytes:10,created:1}]};
const ctx={bytes:String,date:String,button:(label,action,attrs='')=>`<button data-action="${action}" ${attrs}>${label}</button>`};
let html=backup.render(data,settings,[],{items:[]},ctx);
assert(html.includes('name="apps" value="db" checked'));
assert(html.includes('name="app_data" value="db" >'));
assert(html.includes('Database &lt;script&gt;'));
assert(!html.includes('<script>'));
assert(html.includes('data-backup-command="restore-app"'));
assert(html.includes('data-has-data="true"'));
assert(!html.includes('data-backup-command="browse"'));
html=backup.render(data,{...settings,delegated:true},[],{items:[]},ctx);
assert(!html.includes('name="apps"'));
assert(!html.includes('restore-app'));
assert(backup.summary({...settings,app_data:['db']},{items:[]}).includes('Mit Nutzdaten: db'));
const listeners=new Set(),app={name:'apps',value:'db',checked:false},userData={name:'app_data',value:'db',checked:true};
const form={addEventListener:(name,fn)=>listeners.add(fn),removeEventListener:(name,fn)=>listeners.delete(fn),querySelectorAll:name=>name==='[name="apps"]'?[app]:[userData]};
const dispose=backup.wireAppFields(form);
for(const callback of listeners)callback({target:userData});
assert(app.checked,'explicit user data selection selects its app too');
app.checked=false;for(const callback of listeners)callback({target:app});assert(!userData.checked,'removing an app also removes user data');
dispose();assert.equal(listeners.size,0);
let request,dialogHtml,submit;
backup.openAppRestore('b-one','db',true,{dialog(title,body,callback){dialogHtml=body;submit=callback;},action(...args){request=args;}});
assert(dialogHtml.includes('name="include_data"'));
assert(!dialogHtml.includes('name="include_data" checked'));
assert(dialogHtml.includes('App bleibt nach der Wiederherstellung gestoppt'));
submit(new Map());assert.deepEqual(request,['backup_app_restore',{backup:'b-one',app:'db',confirmation:'b-one',include_data:false},{wait:true}]);
submit(new Map([['include_data','on']]));assert.equal(request[1].include_data,true);
backup.openAppRestore('b-two','db',false,{dialog(title,body){dialogHtml=body;}});assert(!dialogHtml.includes('name="include_data"'));
console.log('App backup UI: explicit data selection, safe rendering, delegated restrictions, restore confirmation and stopped-state messaging passed.');
