'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const ui=require('../titan/web/apps_center.js'),{fixture:domFixture}=require('./desktop_test_dom.cjs');
const APP='titan-cloudflared',STATUS='/api/app-install?app='+APP,keys=['docker','files','pull','create','start','connection','proxy','public_check'];
const initial={app:APP,revision:'rev-initial',status:'idle',resumable:false,installed:false,available:true,setup:{phase:''},runtime:{state:'missing',cloudflare_connected:false,public_ready:false,public_origin:'',service_url:'http://127.0.0.1:5102',enabled:false},steps:keys.map(id=>({id,status:'pending',label:'Step '+id,message:''}))};
const state=(status,extra={})=>({...initial,status,...extra,runtime:{...initial.runtime,...extra.runtime},setup:{...initial.setup,...extra.setup}});
const deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
const settle=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
function fixture(installation=initial,extra={}){
 const f=domFixture(),scope=f.doc.createElement('section'),calls=[],waits=[],actions=[],toasts=[],opened=[],replacements=[];f.doc.body.append(scope);
 const context={admin:true,demo:false,installed:{installed:[{id:'legacy-app',name:'Photos <private>',status:'running',options:{password:'legacy-password'}}]},installation,...extra};let markup=ui.render(context),changed=0;
 function hydrate(){const panel=scope.querySelector('[data-apps-center]');for(const form of panel.querySelectorAll('form')){form.elements={};for(const input of form.querySelectorAll('input')){input.value=input.getAttribute('value')||'';form.elements[input.getAttribute('name')]=input;}}Object.defineProperty(panel,'outerHTML',{set(value){markup=value;replacements.push(value);scope.innerHTML=value;hydrate();}});}
 scope.innerHTML=markup;hydrate();
 const api=(path,body,options)=>{const value=deferred();calls.push({path,body,options,...value});return value.promise;};
 const waitForJob=(accepted,options)=>{const value=deferred();waits.push({accepted,options,...value});return value.promise;};
 const action=(operation,args,options)=>{const value=deferred();actions.push({operation,args,options,...value});return value.promise;};
 const query=selector=>scope.querySelector(selector),submit=selector=>f.doc.dispatch(query(selector),'submit'),click=selector=>f.doc.dispatch(query(selector),'click');
 const mount=(options={})=>ui.mount(scope,{api,action,waitForJob,admin:context.admin,demo:context.demo,toast:text=>toasts.push(text),openPackage:id=>opened.push(id),onAppsChanged:()=>changed++,...options});
 return {...f,scope,context,calls,waits,actions,toasts,opened,replacements,query,submit,click,mount,api,get markup(){return markup;},get changed(){return changed;}};
}
function request(f,index,path,body){const call=f.calls[index];assert(call,`Missing request ${index} ${path}`);assert.equal(call.path,path);assert.deepEqual(call.body,body);assert(call.options.signal instanceof AbortSignal);return call;}
async function reply(f,index,value){f.calls[index].resolve(value);await settle();}
async function rendering(){
 const f=fixture({...initial,options:{tunnel_token:'never-render-this'},token:'secret-extra',runtime:{...initial.runtime,password:'runtime-secret'}});f.mount();
 assert.match(f.markup,/<h1>App Store<\/h1>/);assert.match(f.markup,/Photos &lt;private&gt;/);assert.equal(f.query('[name="tunnel_token"]').getAttribute('value'),null);assert.equal(f.query('[name="tunnel_token"]').getAttribute('type'),'password');assert(f.query('[name="public_origin"]'));assert.equal(f.query('[name="admin_password"]'),null);
 assert(!/never-render-this|secret-extra|runtime-secret|legacy-password|BigBear|GPU|Speicherziel/.test(f.markup),'Hydration contains only explicitly safe display fields');
 assert.equal(f.query('[data-apps-timeline]').querySelectorAll('[data-app-step]').length,8);assert(f.query('[data-app-step="docker"]').classList.contains('is-pending'));
 f.click('[data-apps-open]');assert.equal(f.doc.activeElement,f.query('[data-apps-detail]'));f.click('[data-apps-package]');assert.deepEqual(f.opened,['legacy-app']);assert.equal(f.calls.length,0);
 const unrelated=f.doc.createElement('form');f.scope.append(unrelated);assert.equal(f.doc.dispatch(unrelated,'submit').defaultPrevented,false);ui.dispose();
 assert.equal(ui.publicUrl('https://user:secret@example.de'),'');assert.equal(ui.publicUrl('javascript:alert(1)'),'');assert.equal(ui.publicUrl('http://nas.example.de'),'');assert.equal(ui.publicUrl('https://nas.example.de'),'https://nas.example.de/');
 const unsafe=ui.render({admin:true,installation:state('completed',{installed:true,runtime:{public_origin:'https://user:pass@nas.example.de',service_url:'http://user:pass@127.0.0.1',enabled:true}})});assert(!unsafe.includes('user:pass'));assert(!unsafe.includes('Zugang öffnen'));
 const failure=fixture();failure.mount({openPackage:()=>Promise.reject(Error('Bestandsapp nicht verfügbar'))});failure.click('[data-apps-package]');await settle();assert.equal(failure.query('[data-apps-error]').textContent,'Bestandsapp nicht verfügbar');ui.dispose();
}
async function compactDisclosure(){
 const f=fixture();const controller=f.mount();assert.equal(f.query('[data-apps-detail]').hidden,true,'An idle uninstalled app starts as one compact card');assert.equal(f.query('[data-apps-open]').getAttribute('aria-expanded'),'false');assert.equal(f.query('[data-apps-open]').textContent,'Installieren');f.click('[data-apps-open]');assert.equal(f.query('[data-apps-detail]').hidden,false);assert.equal(f.query('[data-apps-open]').getAttribute('aria-expanded'),'true');assert.equal(f.query('[data-apps-open]').textContent,'Details');assert.equal(f.doc.activeElement,f.query('[data-apps-detail]'));
 const refresh=controller.refresh();request(f,0,STATUS,undefined);await reply(f,0,initial);await refresh;assert.equal(f.query('[data-apps-detail]').hidden,false,'A manually opened setup stays open after status replacement');assert.equal(f.query('[data-apps-open]').getAttribute('aria-expanded'),'true');ui.dispose();
 for(const installation of [state('running'),state('failed'),state('interrupted')]){const automatic=fixture(installation);automatic.mount();assert.equal(automatic.query('[data-apps-detail]').hidden,false,'Unfinished installations expose their state immediately');assert.equal(automatic.query('[data-apps-open]').getAttribute('aria-expanded'),'true');ui.dispose();}
 const installed=fixture(state('completed',{installed:true}));installed.mount();assert.equal(installed.query('[data-apps-detail]').hidden,true,'A completed installation opens the storefront, with details on request');ui.dispose();
 const demo=fixture({...initial,available:false,demo:true},{demo:true});demo.mount();demo.click('[data-apps-open]');assert(!demo.markup.includes('Docker ist derzeit nicht bereit'),'Preview availability is not a real Docker failure');assert.match(demo.markup,/Demo · Installationen/);ui.dispose();
 const native=fixture({...initial,available:false});native.mount();native.click('[data-apps-open]');assert.match(native.markup,/Docker ist derzeit nicht bereit/);ui.dispose();
}
async function installAndAddress(){
 const f=fixture();f.mount();f.click('[data-apps-open]');const token='PRIVATE-CLOUDFLARE-TOKEN',form=f.query('[data-apps-install-form]');form.elements.tunnel_token.value=' '+token+' ';form.elements.public_origin.value=' ';
 form.elements.tunnel_token.focus();assert(f.submit('[data-apps-install-form]').defaultPrevented);assert.equal(form.elements.tunnel_token.value,'','Token is cleared before any asynchronous request settles');f.submit('[data-apps-install-form]');assert.equal(f.calls.length,1);
 request(f,0,'/api/app-install',{app:APP,options:{tunnel_token:token,public_origin:''},expected_revision:'rev-initial'});assert(!f.markup.includes(token));assert(f.query('[name="tunnel_token"]').disabled);
 await reply(f,0,{job:'install-job'});request(f,1,STATUS,undefined);assert.equal(f.waits.length,0);
 await reply(f,1,state('running',{current_step:'pull',steps:keys.map(id=>({id,status:id==='docker'?'completed':id==='pull'?'running':'pending'}))}));assert.equal(f.waits.length,1);assert.deepEqual(f.waits[0].accepted,{job:'install-job'});assert(f.waits[0].options.signal instanceof AbortSignal);assert(f.query('[data-app-step="docker"]').classList.contains('is-completed'));assert(f.query('[data-app-step="pull"]').classList.contains('is-running'));assert(f.query('[data-app-step="public_check"]').classList.contains('is-pending'),'Public access must never appear ready because image pull is running');
 f.waits[0].options.onProgress();f.waits[0].options.onProgress();assert.equal(f.calls.length,3,'Progress reads are coalesced');request(f,2,STATUS,undefined);await reply(f,2,state('running',{current_step:'connection'}));
 f.waits[0].resolve({status:'completed'});await settle();request(f,3,STATUS,undefined);await reply(f,3,state('completed',{revision:'rev-address',installed:true,setup:{phase:'needs_domain',needs_domain:true},runtime:{state:'running',cloudflare_connected:true}}));
 assert.match(f.query('[data-apps-status]').textContent,/Öffentliche Adresse ergänzen/);assert.match(f.query('.ac-runtime').textContent,/Mit Cloudflare verbunden/);assert.match(f.query('.ac-runtime').textContent,/Noch nicht bestätigt/);assert.equal(f.query('[name="tunnel_token"]').value,'');assert(!f.markup.includes(token));assert.equal(f.changed,1);assert.equal(f.doc.activeElement,f.query('[data-apps-status]'),'Keyboard focus follows the result after the submitted form is replaced');
 const domain=f.query('[data-apps-address-form]');domain.elements.public_origin.value=' https://nas.example.de ';f.submit('[data-apps-address-form]');f.submit('[data-apps-address-form]');request(f,4,'/api/app-install/address',{app:APP,public_origin:'https://nas.example.de',expected_revision:'rev-address'});assert.equal(f.calls.length,5);
 await reply(f,4,{job:'address-job'});await reply(f,5,state('running',{installed:true,current_step:'proxy'}));assert.equal(f.waits.length,2);f.waits[1].resolve({status:'completed'});await settle();request(f,6,STATUS,undefined);
 await reply(f,6,state('completed',{revision:'rev-ready',installed:true,runtime:{state:'running',cloudflare_connected:true,public_origin:'https://nas.example.de',enabled:true,public_ready:true},diagnosis:{checks:[{name:'<route>',message:'<reachable>',ok:true}]}}));assert(f.query('[data-apps-status]').classList.contains('is-ready'));assert.equal(f.scope.querySelectorAll('a').find(node=>node.getAttribute('href')==='https://nas.example.de/').getAttribute('rel'),'noopener noreferrer');assert.match(f.markup,/&lt;reachable&gt;/);assert.equal(f.query('[data-apps-lifecycle="start"]').disabled,true);assert.equal(f.query('[data-apps-lifecycle="stop"]').disabled,false);assert.equal(f.changed,2);ui.dispose();
}
async function resumeLifecycleAndFallback(){
 let f=fixture(state('failed',{revision:'failed-rev',installed:true,resumable:true,runtime:{state:'stopped'},steps:[{id:'pull',status:'failed',message:'Image nicht erreichbar <blocked>'}]}));f.mount();assert.match(f.markup,/Image nicht erreichbar &lt;blocked&gt;/);f.click('[data-apps-resume]');f.click('[data-apps-resume]');request(f,0,'/api/app-install/resume',{app:APP,expected_revision:'failed-rev'});assert.equal(f.calls.length,1);await reply(f,0,{job:'resume-job'});await reply(f,1,state('running'));f.waits[0].resolve({status:'completed'});await settle();await reply(f,2,state('completed',{installed:true,runtime:{state:'stopped'}}));
 f.click('[data-apps-lifecycle="start"]');assert.equal(f.actions.length,1);assert.equal(f.actions[0].operation,'app_action');assert.deepEqual(f.actions[0].args,{app:APP,action:'start'});assert.equal(f.actions[0].options.wait,true);assert(f.actions[0].options.signal instanceof AbortSignal);f.click('[data-apps-lifecycle="start"]');assert.equal(f.actions.length,1);f.actions[0].resolve({ok:true});await settle();await reply(f,3,state('completed',{installed:true,runtime:{state:'running',cloudflare_connected:true}}));
 f.click('[data-apps-lifecycle="stop"]');assert.deepEqual(f.actions[1].args,{app:APP,action:'stop'});f.actions[1].resolve({ok:true});await settle();await reply(f,4,state('completed',{installed:true,runtime:{state:'stopped'}}));assert.match(f.query('[data-apps-status]').textContent,/App gestoppt/);ui.dispose();
 f=fixture();let wait;f.win.TitanJobs={wait(api,job,options){assert.equal(api,f.api);wait={job,options,...deferred()};return wait.promise;}};f.mount({waitForJob:undefined});f.query('[name="tunnel_token"]').value='fallback-token';f.submit('[data-apps-install-form]');await reply(f,0,{job:'string-job-id'});await reply(f,1,state('running'));assert.equal(wait.job,'string-job-id');wait.resolve({status:'completed'});await settle();await reply(f,2,state('completed'));ui.dispose();
}
async function failuresAndSecrets(){
 let f=fixture();f.mount();const token='private-token-123';f.query('[name="tunnel_token"]').value=token;f.submit('[data-apps-install-form]');f.calls[0].reject(Error(`Rejected ${token}; ${token} <script>bad</script>`));await settle();request(f,1,STATUS,undefined);await reply(f,1,state('failed',{resumable:true,message:'failed '+token,steps:[{id:'files',status:'failed',message:token}]}));
 assert.equal(f.query('[data-apps-error]').textContent,'Rejected [Token ausgeblendet]; [Token ausgeblendet] <script>bad</script>');assert.equal(f.query('[data-apps-error]').children.length,0);assert(!f.markup.includes(token),'Both error and refreshed server history redact the submitted token');assert.equal(f.query('[name="tunnel_token"]').value,'');assert.equal(f.query('[data-apps-resume]').disabled,false);
 f.query('[name="tunnel_token"]').value=' ';f.submit('[data-apps-install-form]');assert.equal(f.calls.length,2);assert.match(f.query('[data-apps-error]').textContent,/Tunnel-Token/);f.query('[name="tunnel_token"]').value='new-token';f.submit('[data-apps-install-form]');assert.equal(f.calls.length,3);ui.dispose();f.calls[2].reject(Object.assign(Error('aborted'),{name:'AbortError'}));await settle();
 f=fixture(state('completed',{installed:true,revision:'domain-old'}));f.mount();f.query('[data-apps-address-form]').elements.public_origin.value='https://nas.example.de';f.submit('[data-apps-address-form]');await reply(f,0,{job:'failed-address'});await reply(f,1,state('running',{installed:true}));f.waits[0].reject(Error('Route nicht erreichbar'));await settle();await reply(f,2,state('failed',{installed:true,revision:'domain-failed',resumable:true}));assert.equal(f.query('[data-apps-error]').textContent,'Route nicht erreichbar');f.click('[data-apps-resume]');assert.equal(f.calls[3].body.expected_revision,'domain-failed');ui.dispose();f.calls[3].reject(Object.assign(Error('aborted'),{name:'AbortError'}));await settle();
}
async function permissions(){
 for(const extra of [{admin:false},{demo:true}]){const f=fixture(state('running',{installed:true,runtime:{state:'running',public_origin:'https://secret-internal.example.de'},steps:[{id:'files',message:'ADMIN-ONLY-DETAIL'}]}),extra);f.mount();f.click('[data-apps-open]');if(extra.admin===false){assert.equal(f.query('[data-apps-install-form]'),null);assert.equal(f.query('[data-apps-timeline]'),null);assert(!f.markup.includes('ADMIN-ONLY-DETAIL'));assert(!f.markup.includes('secret-internal'));}else{f.query('[name="tunnel_token"]').value='demo-token';f.submit('[data-apps-install-form]');f.click('[data-apps-refresh]');}f.advance(20000);assert.equal(f.calls.length,0);assert.equal(f.actions.length,0);ui.dispose();}
 const f=fixture();f.mount({admin:false});assert.equal(f.query('[name="tunnel_token"]'),null,'A stricter live session removes privileged hydrated forms');assert.equal(f.calls.length,0);ui.dispose();
}
async function pollingAndDisposal(){
 let f=fixture(state('running',{current_step:'pull'}));f.mount();f.advance(1999);assert.equal(f.calls.length,0);f.advance(1);request(f,0,STATUS,undefined);await reply(f,0,state('completed',{installed:true}));f.advance(10000);assert.equal(f.calls.length,1);ui.dispose();
 f=fixture(state('running'));f.mount();f.advance(2000);ui.dispose();await reply(f,0,state('completed'));assert.equal(f.replacements.length,0);assert(f.calls[0].options.signal.aborted);f.advance(10000);assert.equal(f.calls.length,1);
 f=fixture();f.mount();f.query('[name="tunnel_token"]').value='late-token';f.submit('[data-apps-install-form]');ui.dispose();await reply(f,0,{job:'late-job'});assert.equal(f.calls.length,1);assert.equal(f.waits.length,0);assert.equal(f.toasts.length,0);assert.equal(f.replacements.length,0);assert(f.calls[0].options.signal.aborted);assert.equal(f.scope.events.get('submit').length,0);
 f=fixture();f.mount();f.query('[name="tunnel_token"]').value='late-progress';f.submit('[data-apps-install-form]');await reply(f,0,{job:'late-progress-job'});ui.dispose();await reply(f,1,state('running'));assert.equal(f.waits.length,0);
 f=fixture();f.mount();f.query('[name="tunnel_token"]').value='stale-token';f.submit('[data-apps-install-form]');await reply(f,0,{job:'stale-job'});await reply(f,1,state('running'));f.waits[0].options.onProgress();request(f,2,STATUS,undefined);f.waits[0].resolve({status:'completed'});await settle();await reply(f,3,state('completed',{installed:true,runtime:{public_ready:true}}));await reply(f,2,state('running'));assert(f.query('[data-apps-status]').classList.contains('is-ready'),'Late progress must not overwrite the final result');ui.dispose();
 f=fixture();f.mount();f.query('[name="tunnel_token"]').value='dispose-wait';f.submit('[data-apps-install-form]');await reply(f,0,{job:'disposed-wait'});await reply(f,1,state('running'));ui.dispose();f.waits[0].options.onProgress();f.waits[0].resolve({status:'completed'});await settle();assert.equal(f.calls.length,2);assert(f.waits[0].options.signal.aborted);
}
function settingsAndLayout(){
 const settings=require('../titan/web/settings_center.js');let calls=0;globalThis.TitanRemoteAccess={render(){calls++;return 'OLD-CLOUDFLARE-SETTINGS';}};globalThis.TitanWebAccess={render(){return 'LOCAL-WEB-ACCESS';}};
 try{const markup=settings.render({section:'general',remoteAccess:{},webAccess:{},settings:{},session:{}});assert.equal(calls,0);assert(!markup.includes('OLD-CLOUDFLARE-SETTINGS'));assert(markup.includes('LOCAL-WEB-ACCESS'));assert(!settings.render({}).toLowerCase().includes('cloudflare'));}finally{delete globalThis.TitanRemoteAccess;delete globalThis.TitanWebAccess;}
 const index=fs.readFileSync('titan/web/index.html','utf8');assert(index.includes('src="/apps_center.js"'));assert(index.includes('href="/apps_center.css"'));assert(!index.includes('section_layout.js'),'The retired store adapter is not loaded');
 const css=fs.readFileSync('titan/web/apps_center.css','utf8');assert(!/#[0-9a-fA-F]{3,8}\b/.test(css));assert.match(css,/@media\(max-width:480px\)/);assert.match(css,/:focus-visible/);assert.match(css,/var\(--panel\)/);assert.match(css,/var\(--text\)/);
}
(async()=>{await rendering();await compactDisclosure();await installAndAddress();await resumeLifecycleAndFallback();await failuresAndSecrets();await permissions();await pollingAndDisposal();settingsAndLayout();console.log('Apps center UI: compact idle disclosure/ARIA/preserved opening, mounted real Compose step history, token clearing/whitelist/redaction, exact install/address/resume jobs, permissions/demo, Start/Stop, legacy management, polling/stale response/disposal and settings migration passed.');})().catch(error=>{ui.dispose();console.error(error);process.exitCode=1;});
