'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function node(){const listeners={};return {listeners,value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,open:false,dataset:{},isConnected:true,focus(){this.focused=true;},setAttribute(key,value){this[key]=value;},addEventListener:(type,fn)=>listeners[type]=fn,removeEventListener:(type,fn)=>{if(listeners[type]===fn)delete listeners[type];},insertAdjacentHTML(where,html){this.innerHTML+=html;},get children(){return this.innerHTML.includes('data-location-folder')?[{}]:[];}};}
function widget(purpose,value){const w=node(),children=new Map();w.dataset.purpose=purpose;for(const name of ['root','value','browser','entries','up','current','status','next'])children.set('[data-location-'+name+']',node());children.get('[data-location-value]').value=value;w.querySelector=selector=>children.get(selector);return {w,get:name=>children.get('[data-location-'+name+']')};}
const context={window:{},URLSearchParams,console};vm.createContext(context);vm.runInContext(fs.readFileSync('titan/web/location_controls.js','utf8'),context);const UI=context.window.TitanLocations;
(async()=>{
 assert(UI.field('Ziel <script>','target','/media/<data>',{purpose:'backup',required:true}).includes('&lt;script&gt;'));assert(UI.field('Ziel','target','',{required:true}).includes('data-location-root required'));assert(UI.within('/data/photos','/data'));assert(!UI.within('/database','/data'));assert.equal(UI.clean('/var//media/'),'/var/media');
 const a=widget('backup','/var/media/usb/Archiv'),b=widget('directory',''),widgets=[a.w,b.w],root={querySelectorAll:()=>widgets,contains:element=>widgets.includes(element)},calls=[];
 const items=[{path:'/',label:'System',backup_eligible:false},{path:'/var/media/usb',label:'USB <data>',backup_eligible:true}];let response={entries:[{name:'Fotos <script>',directory:true},{name:'secret',directory:true,readable:false},{name:'link',directory:true,symlink:true},{name:'a.txt',directory:false}],offset:0,limit:200,total:350};
 const ctx={api:async url=>{calls.push(url);return url==='/api/storage-locations'?{items}:response;}};
 await UI.mount(root,ctx);assert.equal(a.get('root').value,'/var/media/usb');assert.equal(a.get('value').value,'/var/media/usb/Archiv');assert(!a.get('root').innerHTML.includes('>System'));assert(a.get('root').innerHTML.includes('&lt;data&gt;'));assert(b.get('root').innerHTML.includes('>System'));
 a.get('browser').open=true;await a.get('browser').listeners.toggle();assert(calls.at(-1).includes('path=var%2Fmedia%2Fusb%2FArchiv'));assert(a.get('entries').innerHTML.includes('Fotos &lt;script&gt;'));assert(!a.get('entries').innerHTML.includes('secret'));assert(!a.get('entries').innerHTML.includes('link'));assert(!a.get('entries').innerHTML.includes('a.txt'));assert(!a.get('next').hidden);
 await a.get('next').listeners.click();assert(calls.at(-1).includes('offset=200'));
 const folder={dataset:{locationFolder:'Fotos <script>'}};response={entries:[],total:0,limit:200};a.get('entries').listeners.click({target:{closest:()=>folder}});await new Promise(resolve=>setImmediate(resolve));assert.equal(a.get('value').value,'/var/media/usb/Archiv/Fotos <script>');assert(a.get('value').focused);assert.equal(a.get('current')['aria-live'],'polite');assert(a.get('status').textContent.includes('Keine weiteren'));
 a.get('up').listeners.click();await new Promise(resolve=>setImmediate(resolve));assert.equal(a.get('value').value,'/var/media/usb/Archiv');
 a.get('root').value='/var/media/usb';a.get('root').listeners.change();assert.equal(a.get('value').value,'/var/media/usb');assert(a.get('up').disabled);
 let finish;ctx.api=()=>new Promise(resolve=>finish=resolve);const pending=a.get('browser').listeners.toggle();const before=a.get('entries').innerHTML;UI.disposeWithin(root);finish({entries:[{name:'too-late',directory:true}],total:1});await pending;assert.equal(a.get('entries').innerHTML,before);assert(!a.get('root').listeners.change);assert(!b.get('entries').listeners.click);
 const missing=widget('backup','/missing'),emptyRoot={querySelectorAll:()=>[missing.w]};await UI.mount(emptyRoot,{api:async()=>({items:[]})});assert(missing.get('status').textContent.includes('Kein geeignetes externes Laufwerk'));assert.equal(missing.get('root').value,'');
 console.log('Location UI: eligible roots, preserved selected subfolders, escaped names, safe folders, pagination, navigation boundaries and disposed async response passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
