'use strict';
const assert=require('node:assert/strict'),ui=require('../titan/web/apps_center.js'),{fixture:domFixture}=require('./desktop_test_dom.cjs');
const IDS=['titan-immich','titan-adguard','titan-tailscale'],KEY='tskey-auth-deliberately-private-test-key',PATH='/api/app-install';
const deferred=()=>{let resolve,reject;const promise=new Promise((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
const settle=async()=>{for(let i=0;i<30;i++)await Promise.resolve();};
const status=(app,extra={})=>({app,revision:'initial-'+app,status:'idle',installed:false,resumable:false,message:'',runtime:{state:'missing',ready:false,services:[]},steps:['docker','files','pull','create','start','health','setup'].map(id=>({id,label:id,status:'pending',message:''})),...extra});
function fixture(extra={}){
 const f=domFixture(),scope=f.doc.createElement('section');f.doc.body.append(scope);const calls=[],waits=[],opened=[],toasts=[];
 scope.innerHTML=ui.renderNative({admin:true,catalog:{apps:IDS.map(id=>({id,name:id,description:'Eigene App',default_port:id==='titan-immich'?2283:id==='titan-adguard'?3000:0,note:'Hinweis',first_login:{instructions:'Erste Einrichtung'},options:{password:'never-serialize'},environment:{PRIVATE:'never-serialize'},install_schema:[{key:'password',default:'never-serialize'}]}))},...extra});
 for(const form of scope.querySelectorAll('form')){form.elements={};for(const node of form.querySelectorAll('input,select')){node.value=node.getAttribute('value')??node.querySelector('option')?.getAttribute('value')??'';form.elements[node.getAttribute('name')]=node;}}
 const api=(path,body,options)=>{const call={path,body,options,...deferred()};calls.push(call);return call.promise;},waitForJob=(result,options)=>{const wait={result,options,...deferred()};waits.push(wait);return wait.promise;};
 const panel=id=>scope.querySelector(`[data-native-app="${id}"]`),query=(id,selector)=>panel(id).querySelector(selector),click=(id,selector)=>f.doc.dispatch(query(id,selector),'click'),submit=id=>f.doc.dispatch(query(id,'[data-native-form]'),'submit');
 const controller=ui.mountNative(scope,{api,waitForJob,admin:extra.admin??true,demo:extra.demo??false,openPackage:id=>opened.push(id),toast:value=>toasts.push(value)});
 return {...f,scope,calls,waits,opened,toasts,query,panel,click,submit,controller};
}
async function reply(f,index,value){assert(f.calls[index],'missing request '+index);f.calls[index].resolve(value);await settle();}
async function idle(f){for(let index=0;index<3;index++)await reply(f,index,status(IDS[index]));}
const storage={default_storage:'pool:photos',storage:[{id:'system',label:'Interner Speicher',filesystem:'ext4',available:true,capabilities:['apps','files']},{id:'pool:photos',label:'Fotos',filesystem:'zfs',available:true,capabilities:['apps','files']},{id:'external:backup',label:'Backup only',available:true,capabilities:['files','backups']}]};
async function formsAndLiveStatus(){
 const f=fixture();assert(!f.scope.innerHTML.includes('never-serialize'));assert.equal(f.scope.querySelectorAll('[data-native-app]').length,3);await idle(f);
 const id='titan-tailscale';f.click(id,'[data-native-toggle]');assert.equal(f.query(id,'[data-native-detail]').hidden,false);assert.equal(f.doc.activeElement,f.query(id,'[data-native-detail]'));assert.equal(f.query(id,'[type="submit"]').disabled,true,'Install waits for an authoritative storage choice');
 await reply(f,3,status(id));await reply(f,4,storage);assert.equal(f.query(id,'[name="storage_id"]').value,'pool:photos');assert(!f.query(id,'[name="storage_id"]').innerHTML.includes('Backup only'));
 const form=f.query(id,'[data-native-form]');form.elements.hostname.value='my-titan';form.elements.auth_key.value=KEY;form.elements.nas_address.value='192.168.1.10';form.elements.subnet_routing.value='enabled';form.elements.subnet_routes.value='192.168.1.0/24';f.doc.dispatch(form.elements.subnet_routing,'change');assert.equal(f.query(id,'[data-native-routes]').hidden,false);
 f.submit(id);assert.equal(form.elements.auth_key.value,'','Auth key is cleared synchronously');f.submit(id);await settle();assert.equal(f.calls.length,6,'Duplicate submit is ignored');await reply(f,5,status(id));assert.equal(f.calls[6].path,PATH);assert.deepEqual(f.calls[6].body,{app:id,expected_revision:'initial-'+id,options:{storage_id:'pool:photos',resource_profile:'balanced',hostname:'my-titan',auth_key:KEY,nas_address:'192.168.1.10',subnet_routing:'enabled',subnet_routes:'192.168.1.0/24'}});assert(f.calls[6].options.signal instanceof AbortSignal);
 await reply(f,6,{job:'native-install'});await reply(f,7,status(id,{status:'running',current_step:'pull',steps:[{id:'pull',label:'Image laden',status:'running',message:'Lädt'}]}));assert.equal(f.waits.length,1);assert.equal(f.query(id,'[data-native-form]'),form,'Polling retains the form and user edits');assert.equal(form.elements.hostname.value,'my-titan');assert(f.query(id,'[data-app-step="pull"]').classList.contains('is-running'));
 f.waits[0].options.onProgress();f.waits[0].options.onProgress();assert.equal(f.calls.length,9,'Progress reads are coalesced');await reply(f,8,status(id,{status:'running'}));f.waits[0].resolve({status:'completed'});await settle();await reply(f,9,status(id,{revision:'done',status:'completed',installed:true,runtime:{state:'running',ready:true,connected:true,addresses:['100.64.1.2'],subnet_routing:true,subnet_routes:'192.168.1.0/24',routes_approval:'not_verified',services:[{name:'Tailscale',ready:true}]}}));
 assert.equal(form.hidden,true);assert.match(f.query(id,'[data-native-status]').textContent,/externe Erreichbarkeit ist noch nicht bestätigt/);assert.match(f.query(id,'[data-native-status]').textContent,/100.64.1.2/);assert.equal(f.query(id,'[data-native-manage]').hidden,false);f.click(id,'[data-native-manage]');assert.deepEqual(f.opened,[id]);assert(!f.scope.innerHTML.includes(KEY));f.controller.dispose();assert(f.calls.every(call=>call.options.signal.aborted));
}
async function resumeAndErrors(){
 const f=fixture();await reply(f,0,status(IDS[0],{status:'failed',resumable:true,installed:true,revision:'failed'}));await reply(f,1,status(IDS[1]));await reply(f,2,status(IDS[2]));const id=IDS[0];assert.equal(f.query(id,'[data-native-detail]').hidden,false);assert.equal(f.query(id,'[data-native-resume]').hidden,false);f.click(id,'[data-native-resume]');await settle();await reply(f,3,status(id,{status:'failed',revision:'failed',resumable:true,installed:true}));assert.deepEqual(f.calls[4].body,{app:id,expected_revision:'failed'});assert.equal(f.calls[4].path,PATH+'/resume');f.calls[4].reject(Error('Download nicht verfügbar'));await settle();await reply(f,5,status(id,{status:'failed',revision:'failed2',resumable:true,installed:true}));assert.equal(f.query(id,'[data-native-error]').textContent,'Download nicht verfügbar');assert.equal(f.query(id,'[data-native-resume]').disabled,false);f.controller.dispose();
 const secret=fixture();await idle(secret);secret.click(IDS[2],'[data-native-toggle]');await reply(secret,3,status(IDS[2]));await reply(secret,4,storage);secret.query(IDS[2],'[name="auth_key"]').value=KEY;secret.submit(IDS[2]);await settle();await reply(secret,5,status(IDS[2]));secret.calls[6].reject(Error('Rejected '+KEY));await settle();await reply(secret,7,status(IDS[2],{status:'failed'}));assert.equal(secret.query(IDS[2],'[data-native-error]').textContent,'Rejected [Schlüssel ausgeblendet]');assert(!secret.scope.innerHTML.includes(KEY));secret.controller.dispose();
}
async function permissionsStorageAndDisposal(){
 for(const options of [{admin:false},{demo:true}]){const f=fixture(options);assert.equal(f.calls.length,0);f.click(IDS[0],'[data-native-toggle]');assert.equal(f.calls.length,0);if(options.admin===false)assert.equal(f.query(IDS[0],'[data-native-form]'),null);else assert.equal(f.query(IDS[0],'[type="submit"]').disabled,true);f.controller.dispose();}
 const f=fixture();await idle(f);f.click(IDS[0],'[data-native-toggle]');await reply(f,3,status(IDS[0]));await reply(f,4,{storage:[]});assert.equal(f.query(IDS[0],'[type="submit"]').disabled,true);assert.match(f.query(IDS[0],'[data-native-error]').textContent,/Kein beschreibbarer App-Speicher/);f.submit(IDS[0]);assert.equal(f.calls.length,5);f.controller.dispose();
 const pending=fixture();pending.controller.dispose();await reply(pending,0,status(IDS[0],{status:'running'}));pending.advance(20000);assert.equal(pending.calls.length,3);assert.equal(pending.query(IDS[0],'[data-native-detail]').hidden,true);
}
async function failedTailscaleKeyReplacement(){
 const f=fixture();await reply(f,0,status(IDS[0]));await reply(f,1,status(IDS[1]));await reply(f,2,status(IDS[2],{status:'failed',installed:true,resumable:true,configuration:{hostname:'saved-nas',nas_address:'192.168.3.10',subnet_routing:'enabled',subnet_routes:'192.168.3.0/24',storage_id:'system'}}));
 assert.equal(f.calls[3].path,'/api/storage-locations');await reply(f,3,storage);const form=f.query(IDS[2],'[data-native-form]');assert.equal(form.hidden,false);assert.equal(form.elements.hostname.value,'saved-nas');assert.equal(form.elements.storage_id.value,'system');assert.equal(form.elements.auth_key.value,'');assert.match(form.querySelector('[type="submit"]').textContent,/Auth-Key ersetzen/);assert.equal(form.querySelector('[type="submit"]').disabled,false);f.controller.dispose();
}
async function cloudflareRefreshPreservesNativeIsland(){
 const f=domFixture(),scope=f.doc.createElement('section');f.doc.body.append(scope);const calls=[],catalog={apps:IDS.map(id=>({id,name:id,description:'Native app',default_port:2283}))},cf={app:'titan-cloudflared',revision:'cf',status:'idle',runtime:{state:'missing'}};
 scope.className='nas-window-content';scope.scrollTop=0;scope.scrollLeft=0;scope.innerHTML=ui.render({admin:true,catalog,installation:cf});
 function hydrate(){const panel=scope.querySelector('[data-apps-center]');for(const form of panel.querySelectorAll('form')){form.elements={};for(const input of form.querySelectorAll('input,select')){input.value=input.getAttribute('value')??input.querySelector('option')?.getAttribute('value')??'';form.elements[input.getAttribute('name')]=input;}}panel.insertBefore=function(node,before){node.remove();node.parentElement=this;const index=this.children.indexOf(before);this.children.splice(index<0?this.children.length:index,0,node);};Object.defineProperty(panel,'outerHTML',{set(markup){scope.scrollTop=0;scope.scrollLeft=0;scope.innerHTML=markup;hydrate();}});}
 hydrate();const api=(path,body,options)=>{const call={path,body,options,...deferred()};calls.push(call);return call.promise;},controller=ui.mount(scope,{api,admin:true});
 const island=scope.querySelector('[data-native-apps]');assert.equal(island.parentElement,scope.querySelector('[data-apps-center]'));
 for(let index=0;index<3;index++){calls[index].resolve(status(IDS[index]));await settle();}
 const cloudToggle=scope.querySelector('[data-apps-open]');f.doc.dispatch(cloudToggle,'click');assert.equal(scope.querySelector('[data-apps-detail]').hidden,false);f.doc.dispatch(cloudToggle,'click');assert.equal(scope.querySelector('[data-apps-detail]').hidden,true,'Cloudflare details can be collapsed');
 f.doc.dispatch(island.querySelector('[data-native-app="titan-tailscale"] [data-native-toggle]')||island.querySelectorAll('[data-native-toggle]')[2],'click');
 calls[3].resolve(status(IDS[2]));calls[4].resolve(storage);await settle();const input=island.querySelector('[name="hostname"]');input.value='keep-my-edit';input.focus();assert.equal(input.disabled,false);
 scope.scrollTop=137;scope.scrollLeft=4;const refresh=controller.refresh();assert.equal(input.disabled,false,'Cloudflare action does not lock unrelated native fields');calls[5].resolve(cf);await refresh;assert.equal(scope.querySelector('[data-native-apps]'),island,'Cloudflare refresh retains the native DOM island');assert.equal(input.value,'keep-my-edit');assert.equal(f.doc.activeElement,input);assert.equal(scope.scrollTop,137,'Cloudflare refresh preserves content scroll after DOM replacement');assert.equal(scope.scrollLeft,4);assert.equal(scope.querySelector('[data-apps-detail]').hidden,true,'Refresh does not reopen collapsed details');assert(island.parentElement.children.indexOf(island)<island.parentElement.children.indexOf(island.parentElement.querySelector('.ac-existing')));ui.dispose();
 assert.equal(ui.state({admin:true,installation:{installed:true}}).details_open,false);assert.equal(ui.state({admin:true,details_open:false,installation:{installed:true,status:'running'}}).details_open,false,'An explicitly collapsed detail stays collapsed during polling');
}

async function pollingAndRecipeOptions(){
 const f=fixture();await reply(f,0,status(IDS[0],{status:'running'}));await reply(f,1,status(IDS[1]));await reply(f,2,status(IDS[2]));f.advance(2000);assert.equal(f.calls[3].path,PATH+'?app='+IDS[0]);await reply(f,3,status(IDS[0],{status:'completed',installed:true}));f.advance(10000);assert.equal(f.calls.length,4);f.controller.dispose();
 assert.deepEqual(ui.nativeOptions('titan-adguard',{elements:{storage_id:{value:'pool:apps'},port:{value:'3000'},dns_port:{value:'53'}}}),{storage_id:'pool:apps',resource_profile:'balanced',port:3000,stack_port_adguard_53_tcp:53,stack_port_adguard_53_udp:53});
 const options=ui.nativeOptions('titan-tailscale',{elements:{storage_id:{value:'system'},hostname:{value:'titan'},auth_key:{value:KEY},subnet_routing:{value:'disabled'},subnet_routes:{value:'192.168.1.0/24'}}});assert.equal(options.subnet_routes,'','Hidden route values are never advertised while disabled');
}
(async()=>{await formsAndLiveStatus();await resumeAndErrors();await permissionsStorageAndDisposal();await failedTailscaleKeyReplacement();await cloudflareRefreshPreservesNativeIsland();await pollingAndRecipeOptions();console.log('Native apps UI: safe metadata, stable forms/Cloudflare isolation, authoritative storage, private auth key/replacement, actual progress, resume/errors, route approval, permissions/demo and cleanup passed.');})().catch(error=>{console.error(error);process.exitCode=1;});
