'use strict';
const assert=require('node:assert/strict'),ui=require('../titan/web/control_panel.js'),{fixture}=require('./desktop_test_dom.cjs');
const turn=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 const f=fixture(),requests=[],stored=new Map();f.win.localStorage={getItem:key=>stored.get(key),setItem:(key,value)=>stored.set(key,value)};f.win.location={hostname:'nas.local',hash:'#settings'};
 f.surface.innerHTML=ui.render('','',{icon:name=>`<svg data-icon="${name}"></svg>`});const root=f.surface.querySelector('[data-control-panel]');
 const status={hostname:'linux-host',uptime:90540,cpu_percent:22,cpus:8,memory_used:13*1024**3,memory_total:32*1024**3,storage:{used:2*1024**4,total:8*1024**4}};
 const mount=ui.mount(f.surface,{userName:'admin',session:{version:'0.6.0',demo:false},api:async path=>{requests.push(path);return path==='/api/settings'?{hostname:'Mein Titan'}:status;}});await turn();
 assert.equal(root.dataset.view,'list');assert.equal(root.querySelector('[data-cp-device-name]').textContent,'Mein Titan');assert.equal(root.querySelector('[data-cp-device-version]').textContent,'v0.6.0');assert.equal(root.querySelector('[data-cp-device-address]').textContent,'nas.local');assert.equal(root.querySelector('[data-cp-device-uptime]').textContent,'1 Tage 1 Std.');
 const cpu=root.querySelector('[data-cp-metric="cpu"]'),meter=root.querySelector('[data-cp-meter="cpu"]');assert.equal(cpu.textContent,'22 %');assert.equal(meter.style.width,'22%');assert.equal(meter.parentElement.getAttribute('aria-valuenow'),'22');
 const category=root.querySelector('[data-cp-category-filter="2"]');f.doc.dispatch(category,'click');assert.equal(category.getAttribute('aria-selected'),'true');assert.deepEqual(root.querySelectorAll('[data-cp-item]').filter(item=>!item.hidden).map(item=>item.querySelector('strong').textContent),['Dienste','Datensicherung','Protokoll']);
 f.doc.dispatch(category,'keydown',{key:'ArrowLeft'});assert.equal(root.querySelector('[data-cp-category-filter="1"]').getAttribute('aria-selected'),'true');assert.equal(f.doc.activeElement,root.querySelector('[data-cp-category-filter="1"]')); f.doc.dispatch(root.querySelector('[data-cp-category-filter="all"]'),'click');const search=root.querySelector('[data-cp-search]');search.value='Kennwörter';f.doc.dispatch(search,'input');assert.equal(root.querySelectorAll('[data-cp-item]').filter(item=>!item.hidden).length,1);assert.equal(root.querySelector('[data-cp-category="0"]').hidden,false);assert.equal(root.querySelector('[data-cp-category="1"]').hidden,true);f.doc.dispatch(search,'keydown',{key:'Escape'});assert.equal(search.value,'');
 const pin=root.querySelector('[data-cp-pin="backups"]');f.doc.dispatch(pin,'click');assert.equal(pin.getAttribute('aria-pressed'),'true');assert.equal(root.querySelector('[data-cp-favorites]').hidden,false);
 mount.paint({...status,cpu_percent:53});assert.equal(root.querySelector('[data-cp-metric="cpu"]'),cpu,'Metric updates retain existing nodes and focus targets');assert.equal(root.querySelector('[data-cp-meter="cpu"]'),meter);assert.equal(cpu.textContent,'53 %');assert.equal(root.querySelector('[data-cp-device-name]').textContent,'Mein Titan','Chosen display name survives periodic status updates');
 mount.paint({});assert.equal(cpu.textContent,'—');assert.equal(meter.parentElement.getAttribute('aria-valuenow'),null);assert.equal(meter.parentElement.getAttribute('aria-valuetext'),'Nicht verfügbar');
 ui.dispose();const requestCount=requests.length;await mount.refresh();assert.equal(requests.length,requestCount,'Disposed windows do not poll');assert([...f.doc.events.values()].every(events=>events.length===0),'Document listeners removed');
 // A response completing after navigation cannot paint a removed settings window.
 const other=fixture();other.win.location={hostname:'other.local'};other.surface.innerHTML=ui.render('','');let release;ui.mount(other.surface,{api:path=>path==='/api/settings'?Promise.resolve({hostname:'Other'}):new Promise(resolve=>release=resolve)});ui.dispose();release(status);await turn();assert.equal(other.surface.querySelector('[data-cp-metric="cpu"]').textContent,'—');
 assert.equal(ui.compactBytes(null),'—');assert.equal(ui.compactBytes(0),'0 B');assert.equal(ui.deviceValues({cpu_percent:null}).cpu.percent,null);
 console.log('Settings design: real category/search/favorites, authenticated device values, display-name persistence, retained metric nodes, unavailable measurements, late-response and listener teardown passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
