'use strict';
const assert=require('node:assert/strict'),terminal=require('../titan/web/terminal_controls.js'),{fixture}=require('./desktop_test_dom.cjs');
const flush=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 const f=fixture(),main=f.surface,doc=f.doc,win=f.win;main.innerHTML='<section class="terminal-panel"><p id="terminal-state"></p><div id="terminal-screen"></div><div data-terminal-menu hidden><button data-terminal-action="copy">Kopieren</button><button data-terminal-action="paste">Einfügen</button><button data-terminal-action="selectAll">Alles markieren</button><button data-terminal-action="fullscreen">Vollbild</button></div></section>';
 const menu=main.querySelector('[data-terminal-menu]'),screen=main.querySelector('#terminal-screen');menu.hidden=true;let writes=[],pastes=[],scheduled=[];const timeout=win.setTimeout;win.setTimeout=(fn,ms)=>{scheduled.push(fn);return timeout(fn,ms);};win.navigator={clipboard:{writeText:async text=>writes.push(text),readText:async()=>'Zwischenablage'}};win.EventSource=class{addEventListener(){}close(){}};doc.fullscreenElement=null;main.querySelector('.terminal-panel').requestFullscreen=async()=>{doc.fullscreenElement=main;};doc.exitFullscreen=async()=>doc.fullscreenElement=null;
 const term={options:{},cols:80,rows:24,selection:'Text',open(){},loadAddon(){},attachCustomKeyEventHandler(fn){this.key=fn;},onData(fn){this.data=fn;return {dispose(){}};},onBinary(){return {dispose(){}};},resize(){},getSelection(){return this.selection;},hasSelection(){return !!this.selection;},selectAll(){this.all=true;},paste:text=>pastes.push(text),focus(){this.focused=true;},dispose(){},clear(){this.cleared=true;}};
 const controller=terminal.mount(main,{api:async(path,body)=>body.action==='create'?{id:'demo-session',cols:80,rows:24}:{ok:true},terminalFactory:()=>term,toast(){}});await controller.open();
 let prevented=false;assert.equal(term.key({type:'keydown',key:'Insert',shiftKey:true,preventDefault(){prevented=true;}}),false);await flush();assert(prevented);assert.deepEqual(pastes,['Zwischenablage']);
 assert.equal(term.key({type:'keydown',key:'F10',shiftKey:true,preventDefault(){}}),false);assert(!menu.hidden);doc.dispatch(menu.querySelector('[data-terminal-action="copy"]'),'click');await flush();assert.deepEqual(writes,['Text']);assert(menu.hidden);
 doc.dispatch(screen,'contextmenu');doc.dispatch(menu.querySelector('[data-terminal-action="selectAll"]'),'click');assert(term.all);assert(menu.hidden);
 doc.dispatch(screen,'contextmenu');doc.dispatch(doc.activeElement,'keydown',{key:'End'});assert.equal(doc.activeElement,menu.querySelectorAll('button:not(:disabled)').at(-1));doc.dispatch(doc.activeElement,'keydown',{key:'Escape'});assert(menu.hidden);assert(term.focused);
 doc.dispatch(screen,'pointerdown',{pointerType:'touch'});const canceled=scheduled.at(-1);doc.dispatch(screen,'pointercancel');canceled();assert(menu.hidden,'A canceled callback cannot open a menu');
 doc.dispatch(screen,'pointerdown',{pointerType:'touch'});f.advance(550);assert(!menu.hidden);doc.dispatch(menu.querySelector('[data-terminal-action="fullscreen"]'),'click');await flush();assert(doc.fullscreenElement);await controller.fullscreen();assert.equal(doc.fullscreenElement,null);
 controller.dispose();doc.dispatch(screen,'contextmenu');assert(menu.hidden);console.log('Terminal menu, touch cancellation, keyboard focus, Shift+Insert, selection, fullscreen and cleanup passed.');
})();
