'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes=new Map(),node=selector=>{if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',hidden:false,open:false,addEventListener(){},querySelectorAll:()=>[],querySelector:node,showModal(){this.open=true;},close(){this.open=false;},focus(){},textContent:''});return nodes.get(selector);};
let replies={},requests=[],timers=[],cleared=[];
const context={window:{addEventListener(){}},document:{hidden:false,querySelector:node,querySelectorAll:()=>[],addEventListener(){},createElement(){return {innerHTML:'',querySelector:node};}},location:{hash:'#updates',hostname:'nas.local'},URL,URLSearchParams,FormData,console,setTimeout:()=>0,setInterval:(fn,delay)=>{timers.push({fn,delay});return timers.length;},clearInterval:id=>cleared.push(id),fetch:async(path,options)=>{requests.push({path,options});assert(Object.hasOwn(replies,path),'Unexpected API '+path);return {ok:true,json:async()=>replies[path]};}};
vm.createContext(context);vm.runInContext(fs.readFileSync('titan/web/settings_center.js','utf8'),context);vm.runInContext(fs.readFileSync('titan/web/update_controls.js','utf8'),context);vm.runInContext(fs.readFileSync('titan/web/app.js','utf8').replace(/boot\(\)\.catch\(error=>toast\(error.message,true\)\);\s*$/,''),context);const evaluate=code=>vm.runInContext(code,context);
const previous={version:'0.4.1',digest:'sha256:'+'a'.repeat(64),image:'ghcr.io/ra5on/titan@sha256:'+'a'.repeat(64)},current={version:'0.4.2',digest:'sha256:'+'b'.repeat(64),image:'ghcr.io/ra5on/titan@sha256:'+'b'.repeat(64)};
const ui=context.window.TitanUpdates;
assert.equal(ui.progress({status:'idle'}),'');
assert(ui.progress({status:'running',phase:'download',received:512,total:1024}).includes('value="50"'));
assert(!ui.progress({status:'running',phase:'writing'}).includes('<progress'));
assert(ui.progress({status:'interrupted',phase:'writing',message:'<script>'}).includes('&lt;script&gt;'));
assert.equal(ui.rollbackChoices({rollback:previous}).length,1);assert.equal(ui.rollbackChoices({rollback_options:[{digest:'bad'}]}).length,0);let html=ui.panel({booted:current,rollback:null,rollback_available:false,rollback_reason:'Noch kein Update durchgeführt.'});assert(html.includes('Keine Version'));assert(html.includes('id="rollback-version" disabled'));assert(html.includes('Kein vorheriger Systemstand verfügbar'));assert(html.includes('Noch kein Update'));assert(/data-action="update-rollback" disabled/.test(html));html=ui.panel({booted:current,rollback:previous,rollback_available:true,rollback_queued:true,reboot_required:true,next_boot:previous});assert(html.includes('Neustart erforderlich'));assert(html.includes('v0.4.1'));assert(html.includes('Datensicherung'));assert(!html.includes('<script>'));assert(ui.panel({},'Fehler <script>').includes('Fehler &lt;script&gt;'));
const older={version:'0.4.0',digest:'sha256:'+'c'.repeat(64),slot:'B',installed_at:1790841600};
html=ui.panel({booted:current,rollback_options:[previous,older],rollback_available:true});
assert(html.includes('v0.4.0'));assert(html.includes('Slot B'));
assert.equal((html.match(/<option value=/g)||[]).length,2);
html=ui.panel({booted:current,rollback_options:[],rollback_available:true});
assert(/data-action="update-rollback" disabled/.test(html),'No usable versions means no rollback action, even with a stale availability flag');
html=ui.panel({booted:current,rollback_options:[older],rollback_available:true,reboot_scheduled:true});
assert(html.includes('id="rollback-version" disabled'));
assert(/data-action="update-rollback" disabled/.test(html));
(async()=>{
 evaluate('session={version:"0.4.2",stage:"alpha",demo:false,user:{role:"admin"}}');
 replies['/api/settings']={channel:'alpha',repository:'ra5on/Titan',installation:'manual'};replies['/api/updates']={channel:'alpha',latest:'v0.4.3',available:true,signed:true};replies['/api/updates/system']={booted:current,rollback:previous,rollback_available:true,next_boot:current};
 let replaced=false;const originalCreate=context.document.createElement;
 context.document.createElement=()=>({innerHTML:'',querySelector:()=>({id:'updated-offer'})});
 node('#update-offer').replaceWith=()=>{replaced=true;};node('#settings-form').innerHTML='unsaved settings';
 evaluate("page='updates'");await evaluate('refreshUpdateOffer()');assert(replaced);assert.equal(node('#settings-form').innerHTML,'unsaved settings');
 context.document.createElement=originalCreate;
 const page=await evaluate('pages.updates()');assert(page.includes('Systemversionen'));assert(page.includes('Systemimage vorbereiten'));assert(requests.some(item=>item.path==='/api/updates/system'));
 replies['/api/updates/system'].reboot_required=true;const pending=await evaluate('pages.updates()');assert(!pending.includes('data-action="update-install"'),'A live pending deployment hides an obsolete cached offer');
 await evaluate('actions["update-rollback"]({closest:()=>({querySelector:()=>({value:"sha256:"+ "a".repeat(64)})})})');assert(node('#dialog-body').innerHTML.includes('>Ja</button>')&&node('#dialog-body').innerHTML.includes('>Nein</button>'));assert(!node('#dialog-body').innerHTML.includes('name="confirmation"'));assert(node('#dialog-body').innerHTML.includes('v0.4.1'));
 replies['/api/updates/system']={booted:current,rollback_options:[previous,older],rollback_available:true,next_boot:current};
 await evaluate('actions["update-rollback"]({closest:()=>({querySelector:()=>({value:"sha256:"+ "c".repeat(64)})})})');assert(node('#dialog-body').innerHTML.includes('v0.4.0'),'Confirmation must use the selected version, not the first option');
 replies['/api/updates/system'].rollback_options=[previous];
 await assert.rejects(evaluate('actions["update-rollback"]({closest:()=>({querySelector:()=>({value:"sha256:"+ "c".repeat(64)})})})'),/nicht mehr verfügbar/);
 await evaluate('actions["system-reboot"]()');assert(node('#dialog-body').innerHTML.includes('>Ja</button>')&&node('#dialog-body').innerHTML.includes('>Nein</button>'));assert(!node('#dialog-body').innerHTML.includes('name="confirmation"'));assert(node('#dialog-body').innerHTML.includes('nicht zwangsweise'));
 replies['/api/updates/system']={rollback_available:false,rollback_reason:'Keine vorherige Version.'};await assert.rejects(evaluate('actions["update-rollback"]({closest:()=>({querySelector:()=>({value:"sha256:"+ "a".repeat(64)})})})'),/Keine vorherige/);
 let captured;context.dialog=(title,body,submit)=>{captured={title,body,submit};};
 const mutations=[];context.action=async(operation,args)=>mutations.push({operation,args});
 replies['/api/updates/system']={booted:current,rollback:previous,rollback_available:true,next_boot:current};
 await evaluate('actions["system-reboot"]()');assert.equal(mutations.length,0,'Opening confirmation must not reboot');
 await captured.submit(new Map());assert.equal(mutations[0].operation,'system_reboot');assert.equal(mutations[0].args.expected_digest,current.digest);assert.equal(mutations[0].args.confirmation,'NEUSTART');
 await evaluate('actions["update-rollback"]({closest:()=>({querySelector:()=>({value:"sha256:"+ "a".repeat(64)})})})');assert.equal(mutations.length,1,'Opening confirmation must not stage rollback');
 await captured.submit(new Map());assert.equal(mutations[1].operation,'update_rollback');assert.equal(mutations[1].args.expected_digest,previous.digest);assert.equal(mutations[1].args.confirmation,'ROLLBACK');
 const root={querySelector:()=>({})};ui.mount(root,{api:async()=>({})});assert.equal(timers.at(-1).delay,3000);ui.dispose();assert(cleared.length);
 console.log('Update UI: live deployments, initial no-rollback state, cached-offer suppression, captured rollback/reboot confirmation and polling disposal passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
